// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetMeetingDurations = `-- name: AdminGetMeetingDurations :many
SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    COALESCE(SUM(EXTRACT(EPOCH FROM (r.ended_at - r.started_at))), 0)::bigint AS total_duration_seconds
FROM tenants t
LEFT JOIN rooms r ON r.tenant_id = t.id AND r.ended_at IS NOT NULL
GROUP BY t.id, t.name
ORDER BY total_duration_seconds DESC
`

type AdminGetMeetingDurationsRow struct {
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	TenantName           string    `db:"tenant_name" json:"tenant_name"`
	TotalDurationSeconds int64     `db:"total_duration_seconds" json:"total_duration_seconds"`
}

func (q *Queries) AdminGetMeetingDurations(ctx context.Context) ([]AdminGetMeetingDurationsRow, error) {
	rows, err := q.db.Query(ctx, adminGetMeetingDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetMeetingDurationsRow{}
	for rows.Next() {
		var i AdminGetMeetingDurationsRow
		if err := rows.Scan(&i.TenantID, &i.TenantName, &i.TotalDurationSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetOverview = `-- name: AdminGetOverview :one

SELECT
    (SELECT COUNT(*) FROM tenants WHERE is_active = true) AS active_tenants,
    (SELECT COUNT(*) FROM rooms WHERE status = 'active') AS active_rooms,
    (SELECT COUNT(*) FROM rooms) AS total_rooms,
    (SELECT COUNT(*) FROM recordings) AS total_recordings,
    (SELECT COALESCE(SUM(size_bytes), 0) FROM recordings WHERE status IN ('ready', 'archived')) AS total_storage_bytes,
    (SELECT COUNT(*) FROM participants WHERE left_at IS NULL) AS active_participants
`

type AdminGetOverviewRow struct {
	ActiveTenants      int64       `db:"active_tenants" json:"active_tenants"`
	ActiveRooms        int64       `db:"active_rooms" json:"active_rooms"`
	TotalRooms         int64       `db:"total_rooms" json:"total_rooms"`
	TotalRecordings    int64       `db:"total_recordings" json:"total_recordings"`
	TotalStorageBytes  interface{} `db:"total_storage_bytes" json:"total_storage_bytes"`
	ActiveParticipants int64       `db:"active_participants" json:"active_participants"`
}

// Admin Queries
// Cross-tenant queries for the admin dashboard
func (q *Queries) AdminGetOverview(ctx context.Context) (AdminGetOverviewRow, error) {
	row := q.db.QueryRow(ctx, adminGetOverview)
	var i AdminGetOverviewRow
	err := row.Scan(
		&i.ActiveTenants,
		&i.ActiveRooms,
		&i.TotalRooms,
		&i.TotalRecordings,
		&i.TotalStorageBytes,
		&i.ActiveParticipants,
	)
	return i, err
}

const adminGetRoom = `-- name: AdminGetRoom :one
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata,
    t.name AS tenant_name,
    (SELECT COUNT(*) FROM participants p WHERE p.room_id = r.id AND p.left_at IS NULL) AS active_participant_count
FROM rooms r
JOIN tenants t ON t.id = r.tenant_id
WHERE r.id = $1
`

type AdminGetRoomRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	TenantName             string             `db:"tenant_name" json:"tenant_name"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) AdminGetRoom(ctx context.Context, id uuid.UUID) (AdminGetRoomRow, error) {
	row := q.db.QueryRow(ctx, adminGetRoom, id)
	var i AdminGetRoomRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.TenantName,
		&i.ActiveParticipantCount,
	)
	return i, err
}

const adminGetStorageByProvider = `-- name: AdminGetStorageByProvider :many
SELECT
    COALESCE(storage_provider, 'unknown') AS storage_provider,
    COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes,
    COUNT(*) AS recording_count
FROM recordings
WHERE status IN ('ready', 'archived')
GROUP BY storage_provider
`

type AdminGetStorageByProviderRow struct {
	StorageProvider string `db:"storage_provider" json:"storage_provider"`
	TotalBytes      int64  `db:"total_bytes" json:"total_bytes"`
	RecordingCount  int64  `db:"recording_count" json:"recording_count"`
}

func (q *Queries) AdminGetStorageByProvider(ctx context.Context) ([]AdminGetStorageByProviderRow, error) {
	rows, err := q.db.Query(ctx, adminGetStorageByProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetStorageByProviderRow{}
	for rows.Next() {
		var i AdminGetStorageByProviderRow
		if err := rows.Scan(&i.StorageProvider, &i.TotalBytes, &i.RecordingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetWebhookStats = `-- name: AdminGetWebhookStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'delivered') AS delivered,
    COUNT(*) FILTER (WHERE status = 'failed' AND attempts >= max_attempts) AS failed,
    COUNT(*) FILTER (WHERE status IN ('pending', 'sending')) AS pending,
    COUNT(*) AS total
FROM webhook_deliveries
`

type AdminGetWebhookStatsRow struct {
	Delivered int64 `db:"delivered" json:"delivered"`
	Failed    int64 `db:"failed" json:"failed"`
	Pending   int64 `db:"pending" json:"pending"`
	Total     int64 `db:"total" json:"total"`
}

func (q *Queries) AdminGetWebhookStats(ctx context.Context) (AdminGetWebhookStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetWebhookStats)
	var i AdminGetWebhookStatsRow
	err := row.Scan(
		&i.Delivered,
		&i.Failed,
		&i.Pending,
		&i.Total,
	)
	return i, err
}

const adminListAuditLogs = `-- name: AdminListAuditLogs :many
SELECT
    al.id, al.tenant_id, al.room_id, al.actor_id, al.action, al.resource_type, al.resource_id, al.metadata, al.ip_address, al.created_at,
    t.name AS tenant_name,
    r.name AS room_name
FROM audit_logs al
LEFT JOIN tenants t ON t.id = al.tenant_id
LEFT JOIN rooms r ON r.id = al.room_id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListAuditLogsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListAuditLogsRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	RoomID       pgtype.UUID `db:"room_id" json:"room_id"`
	ActorID      *string     `db:"actor_id" json:"actor_id"`
	Action       string      `db:"action" json:"action"`
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	TenantName   *string     `db:"tenant_name" json:"tenant_name"`
	RoomName     *string     `db:"room_name" json:"room_name"`
}

func (q *Queries) AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]AdminListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditLogsRow{}
	for rows.Next() {
		var i AdminListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
			&i.TenantName,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRecordings = `-- name: AdminListRecordings :many
SELECT
    rec.id, rec.room_id, rec.cloudflare_recording_id, rec.storage_provider, rec.storage_path, rec.size_bytes, rec.duration_seconds, rec.status, rec.started_at, rec.ended_at, rec.archived_at, rec.created_at, rec.metadata,
    r.name AS room_name,
    t.name AS tenant_name
FROM recordings rec
JOIN rooms r ON r.id = rec.room_id
JOIN tenants t ON t.id = r.tenant_id
ORDER BY rec.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListRecordingsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListRecordingsRow struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	RoomID                uuid.UUID          `db:"room_id" json:"room_id"`
	CloudflareRecordingID *string            `db:"cloudflare_recording_id" json:"cloudflare_recording_id"`
	StorageProvider       *string            `db:"storage_provider" json:"storage_provider"`
	StoragePath           *string            `db:"storage_path" json:"storage_path"`
	SizeBytes             *int64             `db:"size_bytes" json:"size_bytes"`
	DurationSeconds       *int32             `db:"duration_seconds" json:"duration_seconds"`
	Status                string             `db:"status" json:"status"`
	StartedAt             pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt               pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ArchivedAt            pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	Metadata              []byte             `db:"metadata" json:"metadata"`
	RoomName              *string            `db:"room_name" json:"room_name"`
	TenantName            string             `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) AdminListRecordings(ctx context.Context, arg AdminListRecordingsParams) ([]AdminListRecordingsRow, error) {
	rows, err := q.db.Query(ctx, adminListRecordings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRecordingsRow{}
	for rows.Next() {
		var i AdminListRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CloudflareRecordingID,
			&i.StorageProvider,
			&i.StoragePath,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.RoomName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRoomParticipants = `-- name: AdminListRoomParticipants :many
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at, metadata FROM participants
WHERE room_id = $1
ORDER BY joined_at DESC
`

func (q *Queries) AdminListRoomParticipants(ctx context.Context, roomID uuid.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, adminListRoomParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CloudflareParticipantID,
			&i.ExternalUserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRooms = `-- name: AdminListRooms :many
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata,
    t.name AS tenant_name,
    (SELECT COUNT(*) FROM participants p WHERE p.room_id = r.id AND p.left_at IS NULL) AS active_participant_count
FROM rooms r
JOIN tenants t ON t.id = r.tenant_id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListRoomsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListRoomsRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	TenantName             string             `db:"tenant_name" json:"tenant_name"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) AdminListRooms(ctx context.Context, arg AdminListRoomsParams) ([]AdminListRoomsRow, error) {
	rows, err := q.db.Query(ctx, adminListRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRoomsRow{}
	for rows.Next() {
		var i AdminListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.TenantName,
			&i.ActiveParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTenants = `-- name: AdminListTenants :many
SELECT
    t.id, t.name, t.api_key_hash, t.config, t.max_concurrent_rooms, t.max_participants_per_room, t.max_recording_duration_minutes, t.max_total_minutes_of_meetings, t.is_active, t.created_at, t.updated_at, t.whiteboard_config, t.tenant_config,
    (SELECT COUNT(*) FROM rooms r WHERE r.tenant_id = t.id AND r.status = 'active') AS active_rooms,
    (SELECT COUNT(*) FROM rooms r WHERE r.tenant_id = t.id) AS total_rooms,
    (SELECT COUNT(*) FROM recordings rec JOIN rooms r ON r.id = rec.room_id WHERE r.tenant_id = t.id) AS total_recordings,
    (SELECT COALESCE(SUM(rec.size_bytes), 0) FROM recordings rec JOIN rooms r ON r.id = rec.room_id WHERE r.tenant_id = t.id AND rec.status IN ('ready', 'archived')) AS storage_bytes,
    (SELECT COUNT(*) FROM participants p JOIN rooms r ON r.id = p.room_id WHERE r.tenant_id = t.id) AS total_participants
FROM tenants t
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListTenantsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListTenantsRow struct {
	ID                          uuid.UUID   `db:"id" json:"id"`
	Name                        string      `db:"name" json:"name"`
	ApiKeyHash                  string      `db:"api_key_hash" json:"api_key_hash"`
	Config                      []byte      `db:"config" json:"config"`
	MaxConcurrentRooms          int32       `db:"max_concurrent_rooms" json:"max_concurrent_rooms"`
	MaxParticipantsPerRoom      int32       `db:"max_participants_per_room" json:"max_participants_per_room"`
	MaxRecordingDurationMinutes int32       `db:"max_recording_duration_minutes" json:"max_recording_duration_minutes"`
	MaxTotalMinutesOfMeetings   int32       `db:"max_total_minutes_of_meetings" json:"max_total_minutes_of_meetings"`
	IsActive                    bool        `db:"is_active" json:"is_active"`
	CreatedAt                   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                   time.Time   `db:"updated_at" json:"updated_at"`
	WhiteboardConfig            []byte      `db:"whiteboard_config" json:"whiteboard_config"`
	TenantConfig                []byte      `db:"tenant_config" json:"tenant_config"`
	ActiveRooms                 int64       `db:"active_rooms" json:"active_rooms"`
	TotalRooms                  int64       `db:"total_rooms" json:"total_rooms"`
	TotalRecordings             int64       `db:"total_recordings" json:"total_recordings"`
	StorageBytes                interface{} `db:"storage_bytes" json:"storage_bytes"`
	TotalParticipants           int64       `db:"total_participants" json:"total_participants"`
}

func (q *Queries) AdminListTenants(ctx context.Context, arg AdminListTenantsParams) ([]AdminListTenantsRow, error) {
	rows, err := q.db.Query(ctx, adminListTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTenantsRow{}
	for rows.Next() {
		var i AdminListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.Config,
			&i.MaxConcurrentRooms,
			&i.MaxParticipantsPerRoom,
			&i.MaxRecordingDurationMinutes,
			&i.MaxTotalMinutesOfMeetings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardConfig,
			&i.TenantConfig,
			&i.ActiveRooms,
			&i.TotalRooms,
			&i.TotalRecordings,
			&i.StorageBytes,
			&i.TotalParticipants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTranscripts = `-- name: AdminListTranscripts :many
SELECT
    pmt.id, pmt.recording_id, pmt.room_id, pmt.transcript_text, pmt.transcript_json, pmt.language, pmt.duration_seconds, pmt.word_count, pmt.provider, pmt.summary, pmt.action_items, pmt.status, pmt.error_message, pmt.created_at, pmt.completed_at,
    r.name AS room_name,
    t.name AS tenant_name,
    rec.duration_seconds AS recording_duration_seconds
FROM post_meeting_transcripts pmt
JOIN rooms r ON r.id = pmt.room_id
JOIN recordings rec ON rec.id = pmt.recording_id
JOIN tenants t ON t.id = r.tenant_id
ORDER BY pmt.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListTranscriptsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListTranscriptsRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	RecordingID              uuid.UUID          `db:"recording_id" json:"recording_id"`
	RoomID                   uuid.UUID          `db:"room_id" json:"room_id"`
	TranscriptText           *string            `db:"transcript_text" json:"transcript_text"`
	TranscriptJson           []byte             `db:"transcript_json" json:"transcript_json"`
	Language                 *string            `db:"language" json:"language"`
	DurationSeconds          *int32             `db:"duration_seconds" json:"duration_seconds"`
	WordCount                *int32             `db:"word_count" json:"word_count"`
	Provider                 *string            `db:"provider" json:"provider"`
	Summary                  *string            `db:"summary" json:"summary"`
	ActionItems              []string           `db:"action_items" json:"action_items"`
	Status                   string             `db:"status" json:"status"`
	ErrorMessage             *string            `db:"error_message" json:"error_message"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	CompletedAt              pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	RoomName                 *string            `db:"room_name" json:"room_name"`
	TenantName               string             `db:"tenant_name" json:"tenant_name"`
	RecordingDurationSeconds *int32             `db:"recording_duration_seconds" json:"recording_duration_seconds"`
}

func (q *Queries) AdminListTranscripts(ctx context.Context, arg AdminListTranscriptsParams) ([]AdminListTranscriptsRow, error) {
	rows, err := q.db.Query(ctx, adminListTranscripts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTranscriptsRow{}
	for rows.Next() {
		var i AdminListTranscriptsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RoomID,
			&i.TranscriptText,
			&i.TranscriptJson,
			&i.Language,
			&i.DurationSeconds,
			&i.WordCount,
			&i.Provider,
			&i.Summary,
			&i.ActionItems,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.RoomName,
			&i.TenantName,
			&i.RecordingDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListWebhookDeliveries = `-- name: AdminListWebhookDeliveries :many
SELECT
    wd.id, wd.tenant_id, wd.room_id, wd.recording_id, wd.transcript_id, wd.event_type, wd.webhook_url, wd.payload, wd.status, wd.attempts, wd.max_attempts, wd.last_error, wd.next_retry_at, wd.delivered_at, wd.created_at,
    t.name AS tenant_name,
    r.name AS room_name
FROM webhook_deliveries wd
JOIN tenants t ON t.id = wd.tenant_id
JOIN rooms r ON r.id = wd.room_id
ORDER BY wd.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListWebhookDeliveriesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListWebhookDeliveriesRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TenantID     uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	RoomID       uuid.UUID          `db:"room_id" json:"room_id"`
	RecordingID  pgtype.UUID        `db:"recording_id" json:"recording_id"`
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	EventType    string             `db:"event_type" json:"event_type"`
	WebhookUrl   string             `db:"webhook_url" json:"webhook_url"`
	Payload      []byte             `db:"payload" json:"payload"`
	Status       string             `db:"status" json:"status"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	MaxAttempts  int32              `db:"max_attempts" json:"max_attempts"`
	LastError    *string            `db:"last_error" json:"last_error"`
	NextRetryAt  pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	DeliveredAt  pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	TenantName   string             `db:"tenant_name" json:"tenant_name"`
	RoomName     *string            `db:"room_name" json:"room_name"`
}

func (q *Queries) AdminListWebhookDeliveries(ctx context.Context, arg AdminListWebhookDeliveriesParams) ([]AdminListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, adminListWebhookDeliveries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWebhookDeliveriesRow{}
	for rows.Next() {
		var i AdminListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.RecordingID,
			&i.TranscriptID,
			&i.EventType,
			&i.WebhookUrl,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.TenantName,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateWhiteboardConfig = `-- name: AdminUpdateWhiteboardConfig :one
UPDATE tenants
SET whiteboard_config = $2
WHERE id = $1
RETURNING id, name, api_key_hash, config, max_concurrent_rooms, max_participants_per_room, max_recording_duration_minutes, max_total_minutes_of_meetings, is_active, created_at, updated_at, whiteboard_config, tenant_config
`

type AdminUpdateWhiteboardConfigParams struct {
	ID               uuid.UUID `db:"id" json:"id"`
	WhiteboardConfig []byte    `db:"whiteboard_config" json:"whiteboard_config"`
}

func (q *Queries) AdminUpdateWhiteboardConfig(ctx context.Context, arg AdminUpdateWhiteboardConfigParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, adminUpdateWhiteboardConfig, arg.ID, arg.WhiteboardConfig)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Config,
		&i.MaxConcurrentRooms,
		&i.MaxParticipantsPerRoom,
		&i.MaxRecordingDurationMinutes,
		&i.MaxTotalMinutesOfMeetings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardConfig,
		&i.TenantConfig,
	)
	return i, err
}
