// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	RoomID       pgtype.UUID `db:"room_id" json:"room_id"`
	ActorID      *string     `db:"actor_id" json:"actor_id"`
	Action       string      `db:"action" json:"action"`
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

type ChatAttachment struct {
	ID                      uuid.UUID   `db:"id" json:"id"`
	RoomID                  uuid.UUID   `db:"room_id" json:"room_id"`
	MessageID               pgtype.UUID `db:"message_id" json:"message_id"`
	UploadedByParticipantID uuid.UUID   `db:"uploaded_by_participant_id" json:"uploaded_by_participant_id"`
	FileName                string      `db:"file_name" json:"file_name"`
	MimeType                string      `db:"mime_type" json:"mime_type"`
	SizeBytes               int64       `db:"size_bytes" json:"size_bytes"`
	Kind                    string      `db:"kind" json:"kind"`
	StorageKey              string      `db:"storage_key" json:"storage_key"`
	Status                  string      `db:"status" json:"status"`
	CreatedAt               time.Time   `db:"created_at" json:"created_at"`
}

type ChatMessage struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	RoomID              uuid.UUID `db:"room_id" json:"room_id"`
	SenderParticipantID uuid.UUID `db:"sender_participant_id" json:"sender_participant_id"`
	SenderIdentityKey   string    `db:"sender_identity_key" json:"sender_identity_key"`
	SenderDisplayName   string    `db:"sender_display_name" json:"sender_display_name"`
	Content             string    `db:"content" json:"content"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
}

type ChatMessageRead struct {
	MessageID           uuid.UUID `db:"message_id" json:"message_id"`
	ReaderParticipantID uuid.UUID `db:"reader_participant_id" json:"reader_participant_id"`
	ReaderIdentityKey   string    `db:"reader_identity_key" json:"reader_identity_key"`
	ReaderDisplayName   string    `db:"reader_display_name" json:"reader_display_name"`
	ReadAt              time.Time `db:"read_at" json:"read_at"`
}

type OpsHeartbeatEvent struct {
	ID                uuid.UUID `db:"id" json:"id"`
	HeartbeatKey      string    `db:"heartbeat_key" json:"heartbeat_key"`
	Status            string    `db:"status" json:"status"`
	EventAt           time.Time `db:"event_at" json:"event_at"`
	IngestedAt        time.Time `db:"ingested_at" json:"ingested_at"`
	EventKey          string    `db:"event_key" json:"event_key"`
	ErrorMessage      *string   `db:"error_message" json:"error_message"`
	Details           []byte    `db:"details" json:"details"`
	ReportedSource    *string   `db:"reported_source" json:"reported_source"`
	ReportedEmitterID *string   `db:"reported_emitter_id" json:"reported_emitter_id"`
}

type OpsIncident struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	IncidentCode   string             `db:"incident_code" json:"incident_code"`
	Title          string             `db:"title" json:"title"`
	Summary        *string            `db:"summary" json:"summary"`
	Severity       string             `db:"severity" json:"severity"`
	Status         string             `db:"status" json:"status"`
	Visibility     string             `db:"visibility" json:"visibility"`
	SourceKind     string             `db:"source_kind" json:"source_kind"`
	SourceKey      *string            `db:"source_key" json:"source_key"`
	ComponentIds   []string           `db:"component_ids" json:"component_ids"`
	DedupeKey      *string            `db:"dedupe_key" json:"dedupe_key"`
	IdempotencyKey *string            `db:"idempotency_key" json:"idempotency_key"`
	PublicMessage  *string            `db:"public_message" json:"public_message"`
	PublicTitle    *string            `db:"public_title" json:"public_title"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	FirstSeenAt    time.Time          `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     time.Time          `db:"last_seen_at" json:"last_seen_at"`
	PublishedAt    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedBy      string             `db:"created_by" json:"created_by"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
}

type OpsIncidentEvent struct {
	ID             uuid.UUID `db:"id" json:"id"`
	IncidentID     uuid.UUID `db:"incident_id" json:"incident_id"`
	EventType      string    `db:"event_type" json:"event_type"`
	Visibility     string    `db:"visibility" json:"visibility"`
	ActorKind      string    `db:"actor_kind" json:"actor_kind"`
	ActorID        string    `db:"actor_id" json:"actor_id"`
	Message        string    `db:"message" json:"message"`
	Metadata       []byte    `db:"metadata" json:"metadata"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
	EventAt        time.Time `db:"event_at" json:"event_at"`
	IngestedAt     time.Time `db:"ingested_at" json:"ingested_at"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type OpsMaintenanceWindow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	Summary       *string            `db:"summary" json:"summary"`
	ComponentIds  []string           `db:"component_ids" json:"component_ids"`
	Visibility    string             `db:"visibility" json:"visibility"`
	Status        string             `db:"status" json:"status"`
	StartsAt      time.Time          `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time          `db:"ends_at" json:"ends_at"`
	CreatedBy     string             `db:"created_by" json:"created_by"`
	PublicMessage *string            `db:"public_message" json:"public_message"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	CancelledAt   pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
}

type OpsMonitorResult struct {
	ID                uuid.UUID `db:"id" json:"id"`
	MonitorKey        string    `db:"monitor_key" json:"monitor_key"`
	MonitorKind       string    `db:"monitor_kind" json:"monitor_kind"`
	Status            string    `db:"status" json:"status"`
	HttpStatus        *int32    `db:"http_status" json:"http_status"`
	LatencyMs         *int32    `db:"latency_ms" json:"latency_ms"`
	CheckedAt         time.Time `db:"checked_at" json:"checked_at"`
	IngestedAt        time.Time `db:"ingested_at" json:"ingested_at"`
	RunID             *string   `db:"run_id" json:"run_id"`
	ResultKey         string    `db:"result_key" json:"result_key"`
	ErrorCode         *string   `db:"error_code" json:"error_code"`
	ErrorMessage      *string   `db:"error_message" json:"error_message"`
	Details           []byte    `db:"details" json:"details"`
	ReportedSource    *string   `db:"reported_source" json:"reported_source"`
	ReportedEmitterID *string   `db:"reported_emitter_id" json:"reported_emitter_id"`
}

type OpsNotificationDelivery struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	IncidentID        pgtype.UUID        `db:"incident_id" json:"incident_id"`
	Channel           string             `db:"channel" json:"channel"`
	Recipient         string             `db:"recipient" json:"recipient"`
	DedupeKey         string             `db:"dedupe_key" json:"dedupe_key"`
	Template          string             `db:"template" json:"template"`
	Status            string             `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	Payload           []byte             `db:"payload" json:"payload"`
	Attempts          int32              `db:"attempts" json:"attempts"`
	LastError         *string            `db:"last_error" json:"last_error"`
	SentAt            pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	NextRetryAt       time.Time          `db:"next_retry_at" json:"next_retry_at"`
	CreatedAt         time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time          `db:"updated_at" json:"updated_at"`
}

type Participant struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	RoomID                  uuid.UUID          `db:"room_id" json:"room_id"`
	CloudflareParticipantID string             `db:"cloudflare_participant_id" json:"cloudflare_participant_id"`
	ExternalUserID          *string            `db:"external_user_id" json:"external_user_id"`
	DisplayName             *string            `db:"display_name" json:"display_name"`
	Role                    string             `db:"role" json:"role"`
	JoinedAt                pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt                  pgtype.Timestamptz `db:"left_at" json:"left_at"`
	CreatedAt               time.Time          `db:"created_at" json:"created_at"`
	Metadata                []byte             `db:"metadata" json:"metadata"`
}

type PostMeetingTranscript struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	RecordingID           uuid.UUID          `db:"recording_id" json:"recording_id"`
	RoomID                uuid.UUID          `db:"room_id" json:"room_id"`
	TranscriptText        *string            `db:"transcript_text" json:"transcript_text"`
	TranscriptJson        []byte             `db:"transcript_json" json:"transcript_json"`
	Language              *string            `db:"language" json:"language"`
	DurationSeconds       *int32             `db:"duration_seconds" json:"duration_seconds"`
	WordCount             *int32             `db:"word_count" json:"word_count"`
	Provider              *string            `db:"provider" json:"provider"`
	Summary               *string            `db:"summary" json:"summary"`
	ActionItems           []string           `db:"action_items" json:"action_items"`
	Status                string             `db:"status" json:"status"`
	ErrorMessage          *string            `db:"error_message" json:"error_message"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ProviderJobID         *string            `db:"provider_job_id" json:"provider_job_id"`
	ProviderErrorCode     *string            `db:"provider_error_code" json:"provider_error_code"`
	ProviderErrorMetadata []byte             `db:"provider_error_metadata" json:"provider_error_metadata"`
	DispatchedAt          pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
}

type Recording struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	RoomID                uuid.UUID          `db:"room_id" json:"room_id"`
	CloudflareRecordingID *string            `db:"cloudflare_recording_id" json:"cloudflare_recording_id"`
	StorageProvider       *string            `db:"storage_provider" json:"storage_provider"`
	StoragePath           *string            `db:"storage_path" json:"storage_path"`
	SizeBytes             *int64             `db:"size_bytes" json:"size_bytes"`
	DurationSeconds       *int32             `db:"duration_seconds" json:"duration_seconds"`
	Status                string             `db:"status" json:"status"`
	StartedAt             pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt               pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ArchivedAt            pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	Metadata              []byte             `db:"metadata" json:"metadata"`
	DeletedAt             pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Room struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TenantID            uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                *string            `db:"name" json:"name"`
	Config              []byte             `db:"config" json:"config"`
	Status              string             `db:"status" json:"status"`
	StartedAt           pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt             pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt           time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time          `db:"updated_at" json:"updated_at"`
	// Excalidraw state JSON (elements, files, appState)
	WhiteboardState       []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata              []byte             `db:"metadata" json:"metadata"`
	ScheduledStartAt      pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt        pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
	// Screen annotation state JSON (share session, items, access mode)
	ScreenAnnotationState []byte      `db:"screen_annotation_state" json:"screen_annotation_state"`
	WorkspaceID           pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID       pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
}

type Tenant struct {
	ID                          uuid.UUID `db:"id" json:"id"`
	Name                        string    `db:"name" json:"name"`
	ApiKeyHash                  string    `db:"api_key_hash" json:"api_key_hash"`
	Config                      []byte    `db:"config" json:"config"`
	MaxConcurrentRooms          int32     `db:"max_concurrent_rooms" json:"max_concurrent_rooms"`
	MaxParticipantsPerRoom      int32     `db:"max_participants_per_room" json:"max_participants_per_room"`
	MaxRecordingDurationMinutes int32     `db:"max_recording_duration_minutes" json:"max_recording_duration_minutes"`
	MaxTotalMinutesOfMeetings   int32     `db:"max_total_minutes_of_meetings" json:"max_total_minutes_of_meetings"`
	IsActive                    bool      `db:"is_active" json:"is_active"`
	CreatedAt                   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt                   time.Time `db:"updated_at" json:"updated_at"`
	// Whiteboard permission config: default_access (all/host_only/none), host_can_override (boolean)
	WhiteboardConfig []byte             `db:"whiteboard_config" json:"whiteboard_config"`
	TenantConfig     []byte             `db:"tenant_config" json:"tenant_config"`
	TenantKind       string             `db:"tenant_kind" json:"tenant_kind"`
	OwnerUserID      pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	ClaimedAt        pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	ApiKeyLookupHash *string            `db:"api_key_lookup_hash" json:"api_key_lookup_hash"`
}

type TenantClaim struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	SecretHash string             `db:"secret_hash" json:"secret_hash"`
	ExpiresAt  time.Time          `db:"expires_at" json:"expires_at"`
	UsedAt     pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
}

type Transcript struct {
	ID                      uuid.UUID   `db:"id" json:"id"`
	RoomID                  uuid.UUID   `db:"room_id" json:"room_id"`
	ParticipantID           pgtype.UUID `db:"participant_id" json:"participant_id"`
	CloudflareParticipantID *string     `db:"cloudflare_participant_id" json:"cloudflare_participant_id"`
	SpeakerName             string      `db:"speaker_name" json:"speaker_name"`
	Text                    string      `db:"text" json:"text"`
	Confidence              *float32    `db:"confidence" json:"confidence"`
	Language                *string     `db:"language" json:"language"`
	ExternalID              *string     `db:"external_id" json:"external_id"`
	Timestamp               time.Time   `db:"timestamp" json:"timestamp"`
	CreatedAt               time.Time   `db:"created_at" json:"created_at"`
}

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Email     string    `db:"email" json:"email"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        time.Time          `db:"expires_at" json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	IpAddress        *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent        *string            `db:"user_agent" json:"user_agent"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TenantID     uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	RoomID       uuid.UUID          `db:"room_id" json:"room_id"`
	RecordingID  pgtype.UUID        `db:"recording_id" json:"recording_id"`
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	EventType    string             `db:"event_type" json:"event_type"`
	WebhookUrl   string             `db:"webhook_url" json:"webhook_url"`
	Payload      []byte             `db:"payload" json:"payload"`
	Status       string             `db:"status" json:"status"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	MaxAttempts  int32              `db:"max_attempts" json:"max_attempts"`
	LastError    *string            `db:"last_error" json:"last_error"`
	NextRetryAt  pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	DeliveredAt  pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
}

type WhisperTranscriptionJob struct {
	ID                            uuid.UUID          `db:"id" json:"id"`
	TranscriptID                  uuid.UUID          `db:"transcript_id" json:"transcript_id"`
	RecordingID                   uuid.UUID          `db:"recording_id" json:"recording_id"`
	RoomID                        uuid.UUID          `db:"room_id" json:"room_id"`
	Provider                      string             `db:"provider" json:"provider"`
	WhisperJobID                  uuid.UUID          `db:"whisper_job_id" json:"whisper_job_id"`
	QueueKey                      string             `db:"queue_key" json:"queue_key"`
	AudioStoragePath              string             `db:"audio_storage_path" json:"audio_storage_path"`
	Traceparent                   *string            `db:"traceparent" json:"traceparent"`
	LanguageHint                  *string            `db:"language_hint" json:"language_hint"`
	Status                        string             `db:"status" json:"status"`
	QueueDepthAtEnqueue           *int64             `db:"queue_depth_at_enqueue" json:"queue_depth_at_enqueue"`
	ProcessingQueueDepthAtEnqueue *int64             `db:"processing_queue_depth_at_enqueue" json:"processing_queue_depth_at_enqueue"`
	QueueDepthAtTimeout           *int64             `db:"queue_depth_at_timeout" json:"queue_depth_at_timeout"`
	ProcessingQueueDepthAtTimeout *int64             `db:"processing_queue_depth_at_timeout" json:"processing_queue_depth_at_timeout"`
	ResultLanguage                *string            `db:"result_language" json:"result_language"`
	DurationSeconds               *int32             `db:"duration_seconds" json:"duration_seconds"`
	WordCount                     *int32             `db:"word_count" json:"word_count"`
	ErrorMessage                  *string            `db:"error_message" json:"error_message"`
	ErrorClass                    *string            `db:"error_class" json:"error_class"`
	ErrorStage                    *string            `db:"error_stage" json:"error_stage"`
	DownloadHttpStatus            *int32             `db:"download_http_status" json:"download_http_status"`
	DownloadSizeBytes             *int64             `db:"download_size_bytes" json:"download_size_bytes"`
	CreatedAt                     time.Time          `db:"created_at" json:"created_at"`
	CompletedAt                   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type WhiteboardPermission struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	RoomID        uuid.UUID   `db:"room_id" json:"room_id"`
	ParticipantID uuid.UUID   `db:"participant_id" json:"participant_id"`
	CanDraw       bool        `db:"can_draw" json:"can_draw"`
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

type Workspace struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	TenantID    uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
	Name        string      `db:"name" json:"name"`
	Kind        string      `db:"kind" json:"kind"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updated_at"`
}

type WorkspaceMembership struct {
	WorkspaceID uuid.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Role        string    `db:"role" json:"role"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}
