// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendOpsIncidentEvent = `-- name: AppendOpsIncidentEvent :one
INSERT INTO ops_incident_events (
    incident_id,
    event_type,
    visibility,
    actor_kind,
    actor_id,
    message,
    metadata,
    idempotency_key,
    event_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, incident_id, event_type, visibility, actor_kind, actor_id, message, metadata, idempotency_key, event_at, ingested_at, created_at
`

type AppendOpsIncidentEventParams struct {
	IncidentID     uuid.UUID `db:"incident_id" json:"incident_id"`
	EventType      string    `db:"event_type" json:"event_type"`
	Visibility     string    `db:"visibility" json:"visibility"`
	ActorKind      string    `db:"actor_kind" json:"actor_kind"`
	ActorID        string    `db:"actor_id" json:"actor_id"`
	Message        string    `db:"message" json:"message"`
	Metadata       []byte    `db:"metadata" json:"metadata"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
	EventAt        time.Time `db:"event_at" json:"event_at"`
}

func (q *Queries) AppendOpsIncidentEvent(ctx context.Context, arg AppendOpsIncidentEventParams) (OpsIncidentEvent, error) {
	row := q.db.QueryRow(ctx, appendOpsIncidentEvent,
		arg.IncidentID,
		arg.EventType,
		arg.Visibility,
		arg.ActorKind,
		arg.ActorID,
		arg.Message,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.EventAt,
	)
	var i OpsIncidentEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.EventType,
		&i.Visibility,
		&i.ActorKind,
		&i.ActorID,
		&i.Message,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.EventAt,
		&i.IngestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cancelOpsMaintenanceWindow = `-- name: CancelOpsMaintenanceWindow :one
UPDATE ops_maintenance_windows
SET
    status = 'cancelled',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, summary, component_ids, visibility, status, starts_at, ends_at, created_by, public_message, metadata, cancelled_at, created_at, updated_at
`

func (q *Queries) CancelOpsMaintenanceWindow(ctx context.Context, id uuid.UUID) (OpsMaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, cancelOpsMaintenanceWindow, id)
	var i OpsMaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.ComponentIds,
		&i.Visibility,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.PublicMessage,
		&i.Metadata,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOpsHeartbeatEvent = `-- name: CreateOpsHeartbeatEvent :one
INSERT INTO ops_heartbeat_events (
    heartbeat_key,
    status,
    event_at,
    event_key,
    error_message,
    details,
    reported_source,
    reported_emitter_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (event_key) DO UPDATE
SET
    heartbeat_key = EXCLUDED.heartbeat_key,
    status = EXCLUDED.status,
    event_at = EXCLUDED.event_at,
    error_message = EXCLUDED.error_message,
    details = EXCLUDED.details,
    reported_source = EXCLUDED.reported_source,
    reported_emitter_id = EXCLUDED.reported_emitter_id
RETURNING id, heartbeat_key, status, event_at, ingested_at, event_key, error_message, details, reported_source, reported_emitter_id
`

type CreateOpsHeartbeatEventParams struct {
	HeartbeatKey      string    `db:"heartbeat_key" json:"heartbeat_key"`
	Status            string    `db:"status" json:"status"`
	EventAt           time.Time `db:"event_at" json:"event_at"`
	EventKey          string    `db:"event_key" json:"event_key"`
	ErrorMessage      *string   `db:"error_message" json:"error_message"`
	Details           []byte    `db:"details" json:"details"`
	ReportedSource    *string   `db:"reported_source" json:"reported_source"`
	ReportedEmitterID *string   `db:"reported_emitter_id" json:"reported_emitter_id"`
}

func (q *Queries) CreateOpsHeartbeatEvent(ctx context.Context, arg CreateOpsHeartbeatEventParams) (OpsHeartbeatEvent, error) {
	row := q.db.QueryRow(ctx, createOpsHeartbeatEvent,
		arg.HeartbeatKey,
		arg.Status,
		arg.EventAt,
		arg.EventKey,
		arg.ErrorMessage,
		arg.Details,
		arg.ReportedSource,
		arg.ReportedEmitterID,
	)
	var i OpsHeartbeatEvent
	err := row.Scan(
		&i.ID,
		&i.HeartbeatKey,
		&i.Status,
		&i.EventAt,
		&i.IngestedAt,
		&i.EventKey,
		&i.ErrorMessage,
		&i.Details,
		&i.ReportedSource,
		&i.ReportedEmitterID,
	)
	return i, err
}

const createOpsIncident = `-- name: CreateOpsIncident :one

INSERT INTO ops_incidents (
    incident_code,
    title,
    summary,
    severity,
    status,
    visibility,
    source_kind,
    source_key,
    component_ids,
    dedupe_key,
    idempotency_key,
    public_message,
    public_title,
    metadata,
    first_seen_at,
    last_seen_at,
    published_at,
    resolved_at,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
)
RETURNING id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at
`

type CreateOpsIncidentParams struct {
	IncidentCode   string             `db:"incident_code" json:"incident_code"`
	Title          string             `db:"title" json:"title"`
	Summary        *string            `db:"summary" json:"summary"`
	Severity       string             `db:"severity" json:"severity"`
	Status         string             `db:"status" json:"status"`
	Visibility     string             `db:"visibility" json:"visibility"`
	SourceKind     string             `db:"source_kind" json:"source_kind"`
	SourceKey      *string            `db:"source_key" json:"source_key"`
	ComponentIds   []string           `db:"component_ids" json:"component_ids"`
	DedupeKey      *string            `db:"dedupe_key" json:"dedupe_key"`
	IdempotencyKey *string            `db:"idempotency_key" json:"idempotency_key"`
	PublicMessage  *string            `db:"public_message" json:"public_message"`
	PublicTitle    *string            `db:"public_title" json:"public_title"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	FirstSeenAt    time.Time          `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     time.Time          `db:"last_seen_at" json:"last_seen_at"`
	PublishedAt    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedBy      string             `db:"created_by" json:"created_by"`
}

// Ops incident platform queries
func (q *Queries) CreateOpsIncident(ctx context.Context, arg CreateOpsIncidentParams) (OpsIncident, error) {
	row := q.db.QueryRow(ctx, createOpsIncident,
		arg.IncidentCode,
		arg.Title,
		arg.Summary,
		arg.Severity,
		arg.Status,
		arg.Visibility,
		arg.SourceKind,
		arg.SourceKey,
		arg.ComponentIds,
		arg.DedupeKey,
		arg.IdempotencyKey,
		arg.PublicMessage,
		arg.PublicTitle,
		arg.Metadata,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.PublishedAt,
		arg.ResolvedAt,
		arg.CreatedBy,
	)
	var i OpsIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentCode,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Visibility,
		&i.SourceKind,
		&i.SourceKey,
		&i.ComponentIds,
		&i.DedupeKey,
		&i.IdempotencyKey,
		&i.PublicMessage,
		&i.PublicTitle,
		&i.Metadata,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PublishedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOpsMaintenanceWindow = `-- name: CreateOpsMaintenanceWindow :one
INSERT INTO ops_maintenance_windows (
    title,
    summary,
    component_ids,
    visibility,
    status,
    starts_at,
    ends_at,
    created_by,
    public_message,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, title, summary, component_ids, visibility, status, starts_at, ends_at, created_by, public_message, metadata, cancelled_at, created_at, updated_at
`

type CreateOpsMaintenanceWindowParams struct {
	Title         string    `db:"title" json:"title"`
	Summary       *string   `db:"summary" json:"summary"`
	ComponentIds  []string  `db:"component_ids" json:"component_ids"`
	Visibility    string    `db:"visibility" json:"visibility"`
	Status        string    `db:"status" json:"status"`
	StartsAt      time.Time `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time `db:"ends_at" json:"ends_at"`
	CreatedBy     string    `db:"created_by" json:"created_by"`
	PublicMessage *string   `db:"public_message" json:"public_message"`
	Metadata      []byte    `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateOpsMaintenanceWindow(ctx context.Context, arg CreateOpsMaintenanceWindowParams) (OpsMaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, createOpsMaintenanceWindow,
		arg.Title,
		arg.Summary,
		arg.ComponentIds,
		arg.Visibility,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
		arg.PublicMessage,
		arg.Metadata,
	)
	var i OpsMaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.ComponentIds,
		&i.Visibility,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.PublicMessage,
		&i.Metadata,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOpsMonitorResult = `-- name: CreateOpsMonitorResult :one
INSERT INTO ops_monitor_results (
    monitor_key,
    monitor_kind,
    status,
    http_status,
    latency_ms,
    checked_at,
    run_id,
    result_key,
    error_code,
    error_message,
    details,
    reported_source,
    reported_emitter_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (result_key) DO UPDATE
SET
    monitor_key = EXCLUDED.monitor_key,
    monitor_kind = EXCLUDED.monitor_kind,
    status = EXCLUDED.status,
    http_status = EXCLUDED.http_status,
    latency_ms = EXCLUDED.latency_ms,
    checked_at = EXCLUDED.checked_at,
    run_id = EXCLUDED.run_id,
    error_code = EXCLUDED.error_code,
    error_message = EXCLUDED.error_message,
    details = EXCLUDED.details,
    reported_source = EXCLUDED.reported_source,
    reported_emitter_id = EXCLUDED.reported_emitter_id
RETURNING id, monitor_key, monitor_kind, status, http_status, latency_ms, checked_at, ingested_at, run_id, result_key, error_code, error_message, details, reported_source, reported_emitter_id
`

type CreateOpsMonitorResultParams struct {
	MonitorKey        string    `db:"monitor_key" json:"monitor_key"`
	MonitorKind       string    `db:"monitor_kind" json:"monitor_kind"`
	Status            string    `db:"status" json:"status"`
	HttpStatus        *int32    `db:"http_status" json:"http_status"`
	LatencyMs         *int32    `db:"latency_ms" json:"latency_ms"`
	CheckedAt         time.Time `db:"checked_at" json:"checked_at"`
	RunID             *string   `db:"run_id" json:"run_id"`
	ResultKey         string    `db:"result_key" json:"result_key"`
	ErrorCode         *string   `db:"error_code" json:"error_code"`
	ErrorMessage      *string   `db:"error_message" json:"error_message"`
	Details           []byte    `db:"details" json:"details"`
	ReportedSource    *string   `db:"reported_source" json:"reported_source"`
	ReportedEmitterID *string   `db:"reported_emitter_id" json:"reported_emitter_id"`
}

func (q *Queries) CreateOpsMonitorResult(ctx context.Context, arg CreateOpsMonitorResultParams) (OpsMonitorResult, error) {
	row := q.db.QueryRow(ctx, createOpsMonitorResult,
		arg.MonitorKey,
		arg.MonitorKind,
		arg.Status,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.CheckedAt,
		arg.RunID,
		arg.ResultKey,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Details,
		arg.ReportedSource,
		arg.ReportedEmitterID,
	)
	var i OpsMonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorKey,
		&i.MonitorKind,
		&i.Status,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.CheckedAt,
		&i.IngestedAt,
		&i.RunID,
		&i.ResultKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Details,
		&i.ReportedSource,
		&i.ReportedEmitterID,
	)
	return i, err
}

const createOpsNotificationDelivery = `-- name: CreateOpsNotificationDelivery :one
INSERT INTO ops_notification_deliveries (
    incident_id,
    channel,
    recipient,
    dedupe_key,
    template,
    status,
    provider,
    payload,
    next_retry_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (channel, recipient, dedupe_key) DO UPDATE
SET
    payload = EXCLUDED.payload,
    next_retry_at = LEAST(ops_notification_deliveries.next_retry_at, EXCLUDED.next_retry_at)
RETURNING id, incident_id, channel, recipient, dedupe_key, template, status, provider, provider_message_id, payload, attempts, last_error, sent_at, next_retry_at, created_at, updated_at
`

type CreateOpsNotificationDeliveryParams struct {
	IncidentID  pgtype.UUID `db:"incident_id" json:"incident_id"`
	Channel     string      `db:"channel" json:"channel"`
	Recipient   string      `db:"recipient" json:"recipient"`
	DedupeKey   string      `db:"dedupe_key" json:"dedupe_key"`
	Template    string      `db:"template" json:"template"`
	Status      string      `db:"status" json:"status"`
	Provider    string      `db:"provider" json:"provider"`
	Payload     []byte      `db:"payload" json:"payload"`
	NextRetryAt time.Time   `db:"next_retry_at" json:"next_retry_at"`
}

func (q *Queries) CreateOpsNotificationDelivery(ctx context.Context, arg CreateOpsNotificationDeliveryParams) (OpsNotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createOpsNotificationDelivery,
		arg.IncidentID,
		arg.Channel,
		arg.Recipient,
		arg.DedupeKey,
		arg.Template,
		arg.Status,
		arg.Provider,
		arg.Payload,
		arg.NextRetryAt,
	)
	var i OpsNotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Channel,
		&i.Recipient,
		&i.DedupeKey,
		&i.Template,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Payload,
		&i.Attempts,
		&i.LastError,
		&i.SentAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldOpsHeartbeatEvents = `-- name: DeleteOldOpsHeartbeatEvents :exec
DELETE FROM ops_heartbeat_events
WHERE event_at < $1
`

func (q *Queries) DeleteOldOpsHeartbeatEvents(ctx context.Context, eventAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldOpsHeartbeatEvents, eventAt)
	return err
}

const deleteOldOpsMonitorResults = `-- name: DeleteOldOpsMonitorResults :exec
DELETE FROM ops_monitor_results
WHERE checked_at < $1
`

func (q *Queries) DeleteOldOpsMonitorResults(ctx context.Context, checkedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldOpsMonitorResults, checkedAt)
	return err
}

const getActiveOpsIncidentBySource = `-- name: GetActiveOpsIncidentBySource :one
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE source_kind = $1
  AND source_key = $2
  AND status <> 'resolved'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOpsIncidentBySourceParams struct {
	SourceKind string  `db:"source_kind" json:"source_kind"`
	SourceKey  *string `db:"source_key" json:"source_key"`
}

func (q *Queries) GetActiveOpsIncidentBySource(ctx context.Context, arg GetActiveOpsIncidentBySourceParams) (OpsIncident, error) {
	row := q.db.QueryRow(ctx, getActiveOpsIncidentBySource, arg.SourceKind, arg.SourceKey)
	var i OpsIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentCode,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Visibility,
		&i.SourceKind,
		&i.SourceKey,
		&i.ComponentIds,
		&i.DedupeKey,
		&i.IdempotencyKey,
		&i.PublicMessage,
		&i.PublicTitle,
		&i.Metadata,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PublishedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestOpsHeartbeatEvent = `-- name: GetLatestOpsHeartbeatEvent :one
SELECT id, heartbeat_key, status, event_at, ingested_at, event_key, error_message, details, reported_source, reported_emitter_id FROM ops_heartbeat_events
WHERE heartbeat_key = $1
ORDER BY event_at DESC, ingested_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOpsHeartbeatEvent(ctx context.Context, heartbeatKey string) (OpsHeartbeatEvent, error) {
	row := q.db.QueryRow(ctx, getLatestOpsHeartbeatEvent, heartbeatKey)
	var i OpsHeartbeatEvent
	err := row.Scan(
		&i.ID,
		&i.HeartbeatKey,
		&i.Status,
		&i.EventAt,
		&i.IngestedAt,
		&i.EventKey,
		&i.ErrorMessage,
		&i.Details,
		&i.ReportedSource,
		&i.ReportedEmitterID,
	)
	return i, err
}

const getLatestOpsMonitorIngestAt = `-- name: GetLatestOpsMonitorIngestAt :one
SELECT ingested_at
FROM ops_monitor_results
ORDER BY ingested_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOpsMonitorIngestAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLatestOpsMonitorIngestAt)
	var ingested_at time.Time
	err := row.Scan(&ingested_at)
	return ingested_at, err
}

const getLatestOpsMonitorResult = `-- name: GetLatestOpsMonitorResult :one
SELECT id, monitor_key, monitor_kind, status, http_status, latency_ms, checked_at, ingested_at, run_id, result_key, error_code, error_message, details, reported_source, reported_emitter_id FROM ops_monitor_results
WHERE monitor_key = $1
ORDER BY checked_at DESC, ingested_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOpsMonitorResult(ctx context.Context, monitorKey string) (OpsMonitorResult, error) {
	row := q.db.QueryRow(ctx, getLatestOpsMonitorResult, monitorKey)
	var i OpsMonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorKey,
		&i.MonitorKind,
		&i.Status,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.CheckedAt,
		&i.IngestedAt,
		&i.RunID,
		&i.ResultKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Details,
		&i.ReportedSource,
		&i.ReportedEmitterID,
	)
	return i, err
}

const getOpsIncidentByCode = `-- name: GetOpsIncidentByCode :one
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE incident_code = $1
LIMIT 1
`

func (q *Queries) GetOpsIncidentByCode(ctx context.Context, incidentCode string) (OpsIncident, error) {
	row := q.db.QueryRow(ctx, getOpsIncidentByCode, incidentCode)
	var i OpsIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentCode,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Visibility,
		&i.SourceKind,
		&i.SourceKey,
		&i.ComponentIds,
		&i.DedupeKey,
		&i.IdempotencyKey,
		&i.PublicMessage,
		&i.PublicTitle,
		&i.Metadata,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PublishedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOpsIncidents = `-- name: ListActiveOpsIncidents :many
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE status <> 'resolved'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveOpsIncidents(ctx context.Context) ([]OpsIncident, error) {
	rows, err := q.db.Query(ctx, listActiveOpsIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncident{}
	for rows.Next() {
		var i OpsIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentCode,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Visibility,
			&i.SourceKind,
			&i.SourceKey,
			&i.ComponentIds,
			&i.DedupeKey,
			&i.IdempotencyKey,
			&i.PublicMessage,
			&i.PublicTitle,
			&i.Metadata,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PublishedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePublicOpsIncidents = `-- name: ListActivePublicOpsIncidents :many
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE visibility = 'public'
  AND status <> 'resolved'
ORDER BY created_at DESC
`

func (q *Queries) ListActivePublicOpsIncidents(ctx context.Context) ([]OpsIncident, error) {
	rows, err := q.db.Query(ctx, listActivePublicOpsIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncident{}
	for rows.Next() {
		var i OpsIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentCode,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Visibility,
			&i.SourceKind,
			&i.SourceKey,
			&i.ComponentIds,
			&i.DedupeKey,
			&i.IdempotencyKey,
			&i.PublicMessage,
			&i.PublicTitle,
			&i.Metadata,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PublishedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePublicOpsMaintenanceWindows = `-- name: ListActivePublicOpsMaintenanceWindows :many
SELECT id, title, summary, component_ids, visibility, status, starts_at, ends_at, created_by, public_message, metadata, cancelled_at, created_at, updated_at FROM ops_maintenance_windows
WHERE visibility = 'public'
  AND status = 'scheduled'
  AND ends_at >= NOW()
ORDER BY starts_at ASC
`

func (q *Queries) ListActivePublicOpsMaintenanceWindows(ctx context.Context) ([]OpsMaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listActivePublicOpsMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsMaintenanceWindow{}
	for rows.Next() {
		var i OpsMaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.ComponentIds,
			&i.Visibility,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.PublicMessage,
			&i.Metadata,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestOpsHeartbeatEvents = `-- name: ListLatestOpsHeartbeatEvents :many
SELECT DISTINCT ON (heartbeat_key) id, heartbeat_key, status, event_at, ingested_at, event_key, error_message, details, reported_source, reported_emitter_id
FROM ops_heartbeat_events
ORDER BY heartbeat_key, event_at DESC, ingested_at DESC
`

func (q *Queries) ListLatestOpsHeartbeatEvents(ctx context.Context) ([]OpsHeartbeatEvent, error) {
	rows, err := q.db.Query(ctx, listLatestOpsHeartbeatEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsHeartbeatEvent{}
	for rows.Next() {
		var i OpsHeartbeatEvent
		if err := rows.Scan(
			&i.ID,
			&i.HeartbeatKey,
			&i.Status,
			&i.EventAt,
			&i.IngestedAt,
			&i.EventKey,
			&i.ErrorMessage,
			&i.Details,
			&i.ReportedSource,
			&i.ReportedEmitterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestOpsMonitorResults = `-- name: ListLatestOpsMonitorResults :many
SELECT DISTINCT ON (monitor_key) id, monitor_key, monitor_kind, status, http_status, latency_ms, checked_at, ingested_at, run_id, result_key, error_code, error_message, details, reported_source, reported_emitter_id
FROM ops_monitor_results
ORDER BY monitor_key, checked_at DESC, ingested_at DESC
`

func (q *Queries) ListLatestOpsMonitorResults(ctx context.Context) ([]OpsMonitorResult, error) {
	rows, err := q.db.Query(ctx, listLatestOpsMonitorResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsMonitorResult{}
	for rows.Next() {
		var i OpsMonitorResult
		if err := rows.Scan(
			&i.ID,
			&i.MonitorKey,
			&i.MonitorKind,
			&i.Status,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.CheckedAt,
			&i.IngestedAt,
			&i.RunID,
			&i.ResultKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Details,
			&i.ReportedSource,
			&i.ReportedEmitterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsIncidentEvents = `-- name: ListOpsIncidentEvents :many
SELECT id, incident_id, event_type, visibility, actor_kind, actor_id, message, metadata, idempotency_key, event_at, ingested_at, created_at FROM ops_incident_events
WHERE incident_id = $1
ORDER BY event_at ASC, created_at ASC
`

func (q *Queries) ListOpsIncidentEvents(ctx context.Context, incidentID uuid.UUID) ([]OpsIncidentEvent, error) {
	rows, err := q.db.Query(ctx, listOpsIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncidentEvent{}
	for rows.Next() {
		var i OpsIncidentEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.EventType,
			&i.Visibility,
			&i.ActorKind,
			&i.ActorID,
			&i.Message,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.EventAt,
			&i.IngestedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsIncidents = `-- name: ListOpsIncidents :many
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpsIncidentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListOpsIncidents(ctx context.Context, arg ListOpsIncidentsParams) ([]OpsIncident, error) {
	rows, err := q.db.Query(ctx, listOpsIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncident{}
	for rows.Next() {
		var i OpsIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentCode,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Visibility,
			&i.SourceKind,
			&i.SourceKey,
			&i.ComponentIds,
			&i.DedupeKey,
			&i.IdempotencyKey,
			&i.PublicMessage,
			&i.PublicTitle,
			&i.Metadata,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PublishedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsMaintenanceWindows = `-- name: ListOpsMaintenanceWindows :many
SELECT id, title, summary, component_ids, visibility, status, starts_at, ends_at, created_by, public_message, metadata, cancelled_at, created_at, updated_at FROM ops_maintenance_windows
ORDER BY starts_at DESC
`

func (q *Queries) ListOpsMaintenanceWindows(ctx context.Context) ([]OpsMaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listOpsMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsMaintenanceWindow{}
	for rows.Next() {
		var i OpsMaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.ComponentIds,
			&i.Visibility,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.PublicMessage,
			&i.Metadata,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOpsNotificationDeliveries = `-- name: ListPendingOpsNotificationDeliveries :many
SELECT id, incident_id, channel, recipient, dedupe_key, template, status, provider, provider_message_id, payload, attempts, last_error, sent_at, next_retry_at, created_at, updated_at FROM ops_notification_deliveries
WHERE status IN ('pending', 'retrying')
  AND next_retry_at <= NOW()
ORDER BY next_retry_at ASC, created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingOpsNotificationDeliveries(ctx context.Context, limit int32) ([]OpsNotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingOpsNotificationDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsNotificationDelivery{}
	for rows.Next() {
		var i OpsNotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Channel,
			&i.Recipient,
			&i.DedupeKey,
			&i.Template,
			&i.Status,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Payload,
			&i.Attempts,
			&i.LastError,
			&i.SentAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOpsIncidentEvents = `-- name: ListPublicOpsIncidentEvents :many
SELECT id, incident_id, event_type, visibility, actor_kind, actor_id, message, metadata, idempotency_key, event_at, ingested_at, created_at FROM ops_incident_events
WHERE incident_id = $1
  AND visibility = 'public'
ORDER BY event_at ASC, created_at ASC
`

func (q *Queries) ListPublicOpsIncidentEvents(ctx context.Context, incidentID uuid.UUID) ([]OpsIncidentEvent, error) {
	rows, err := q.db.Query(ctx, listPublicOpsIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncidentEvent{}
	for rows.Next() {
		var i OpsIncidentEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.EventType,
			&i.Visibility,
			&i.ActorKind,
			&i.ActorID,
			&i.Message,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.EventAt,
			&i.IngestedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOpsIncidents = `-- name: ListPublicOpsIncidents :many
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE visibility = 'public'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicOpsIncidentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicOpsIncidents(ctx context.Context, arg ListPublicOpsIncidentsParams) ([]OpsIncident, error) {
	rows, err := q.db.Query(ctx, listPublicOpsIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncident{}
	for rows.Next() {
		var i OpsIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentCode,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Visibility,
			&i.SourceKind,
			&i.SourceKey,
			&i.ComponentIds,
			&i.DedupeKey,
			&i.IdempotencyKey,
			&i.PublicMessage,
			&i.PublicTitle,
			&i.Metadata,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PublishedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentResolvedPublicOpsIncidents = `-- name: ListRecentResolvedPublicOpsIncidents :many
SELECT id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at FROM ops_incidents
WHERE visibility = 'public'
  AND status = 'resolved'
ORDER BY resolved_at DESC NULLS LAST, created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentResolvedPublicOpsIncidents(ctx context.Context, limit int32) ([]OpsIncident, error) {
	rows, err := q.db.Query(ctx, listRecentResolvedPublicOpsIncidents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsIncident{}
	for rows.Next() {
		var i OpsIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentCode,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Visibility,
			&i.SourceKind,
			&i.SourceKey,
			&i.ComponentIds,
			&i.DedupeKey,
			&i.IdempotencyKey,
			&i.PublicMessage,
			&i.PublicTitle,
			&i.Metadata,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.PublishedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOpsNotificationFailed = `-- name: MarkOpsNotificationFailed :exec
UPDATE ops_notification_deliveries
SET
    status = 'failed',
    attempts = attempts + 1,
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkOpsNotificationFailedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	LastError *string   `db:"last_error" json:"last_error"`
}

func (q *Queries) MarkOpsNotificationFailed(ctx context.Context, arg MarkOpsNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markOpsNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markOpsNotificationRetry = `-- name: MarkOpsNotificationRetry :exec
UPDATE ops_notification_deliveries
SET
    status = 'retrying',
    attempts = attempts + 1,
    last_error = $2,
    next_retry_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type MarkOpsNotificationRetryParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	LastError   *string   `db:"last_error" json:"last_error"`
	NextRetryAt time.Time `db:"next_retry_at" json:"next_retry_at"`
}

func (q *Queries) MarkOpsNotificationRetry(ctx context.Context, arg MarkOpsNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, markOpsNotificationRetry, arg.ID, arg.LastError, arg.NextRetryAt)
	return err
}

const markOpsNotificationSent = `-- name: MarkOpsNotificationSent :exec
UPDATE ops_notification_deliveries
SET
    status = 'sent',
    provider_message_id = $2,
    attempts = attempts + 1,
    last_error = NULL,
    sent_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkOpsNotificationSentParams struct {
	ID                uuid.UUID `db:"id" json:"id"`
	ProviderMessageID *string   `db:"provider_message_id" json:"provider_message_id"`
}

func (q *Queries) MarkOpsNotificationSent(ctx context.Context, arg MarkOpsNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markOpsNotificationSent, arg.ID, arg.ProviderMessageID)
	return err
}

const touchOpsIncidentObservation = `-- name: TouchOpsIncidentObservation :one
UPDATE ops_incidents
SET
    last_seen_at = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at
`

type TouchOpsIncidentObservationParams struct {
	LastSeenAt time.Time `db:"last_seen_at" json:"last_seen_at"`
	ID         uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchOpsIncidentObservation(ctx context.Context, arg TouchOpsIncidentObservationParams) (OpsIncident, error) {
	row := q.db.QueryRow(ctx, touchOpsIncidentObservation, arg.LastSeenAt, arg.ID)
	var i OpsIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentCode,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Visibility,
		&i.SourceKind,
		&i.SourceKey,
		&i.ComponentIds,
		&i.DedupeKey,
		&i.IdempotencyKey,
		&i.PublicMessage,
		&i.PublicTitle,
		&i.Metadata,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PublishedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOpsIncidentState = `-- name: UpdateOpsIncidentState :one
UPDATE ops_incidents
SET
    status = $1,
    summary = COALESCE($2, summary),
    visibility = COALESCE($3, visibility),
    public_message = COALESCE($4, public_message),
    public_title = COALESCE($5, public_title),
    last_seen_at = COALESCE($6, last_seen_at),
    resolved_at = COALESCE($7, resolved_at),
    published_at = COALESCE($8, published_at),
    metadata = COALESCE($9, metadata),
    updated_at = NOW()
WHERE id = $10
RETURNING id, incident_code, title, summary, severity, status, visibility, source_kind, source_key, component_ids, dedupe_key, idempotency_key, public_message, public_title, metadata, first_seen_at, last_seen_at, published_at, resolved_at, created_by, created_at, updated_at
`

type UpdateOpsIncidentStateParams struct {
	Status        string             `db:"status" json:"status"`
	Summary       *string            `db:"summary" json:"summary"`
	Visibility    *string            `db:"visibility" json:"visibility"`
	PublicMessage *string            `db:"public_message" json:"public_message"`
	PublicTitle   *string            `db:"public_title" json:"public_title"`
	LastSeenAt    pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	ResolvedAt    pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	ID            uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateOpsIncidentState(ctx context.Context, arg UpdateOpsIncidentStateParams) (OpsIncident, error) {
	row := q.db.QueryRow(ctx, updateOpsIncidentState,
		arg.Status,
		arg.Summary,
		arg.Visibility,
		arg.PublicMessage,
		arg.PublicTitle,
		arg.LastSeenAt,
		arg.ResolvedAt,
		arg.PublishedAt,
		arg.Metadata,
		arg.ID,
	)
	var i OpsIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentCode,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Visibility,
		&i.SourceKind,
		&i.SourceKey,
		&i.ComponentIds,
		&i.DedupeKey,
		&i.IdempotencyKey,
		&i.PublicMessage,
		&i.PublicTitle,
		&i.Metadata,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.PublishedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
