// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveParticipantsByRoom = `-- name: CountActiveParticipantsByRoom :one
SELECT COUNT(*) FROM participants
WHERE room_id = $1 AND left_at IS NULL
`

func (q *Queries) CountActiveParticipantsByRoom(ctx context.Context, roomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveParticipantsByRoom, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createParticipant = `-- name: CreateParticipant :one

INSERT INTO participants (
    room_id,
    cloudflare_participant_id,
    external_user_id,
    display_name,
    role,
    joined_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at
`

type CreateParticipantParams struct {
	RoomID                  uuid.UUID `db:"room_id" json:"room_id"`
	CloudflareParticipantID string    `db:"cloudflare_participant_id" json:"cloudflare_participant_id"`
	ExternalUserID          *string   `db:"external_user_id" json:"external_user_id"`
	DisplayName             *string   `db:"display_name" json:"display_name"`
	Role                    string    `db:"role" json:"role"`
}

// Participant Queries
// CRUD operations and participant management
func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.RoomID,
		arg.CloudflareParticipantID,
		arg.ExternalUserID,
		arg.DisplayName,
		arg.Role,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParticipant(ctx context.Context, id uuid.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByCloudflareID = `-- name: GetParticipantByCloudflareID :one
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE cloudflare_participant_id = $1 LIMIT 1
`

func (q *Queries) GetParticipantByCloudflareID(ctx context.Context, cloudflareParticipantID string) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByCloudflareID, cloudflareParticipantID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByExternalUserAndRoom = `-- name: GetParticipantByExternalUserAndRoom :one
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE room_id = $1 AND external_user_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetParticipantByExternalUserAndRoomParams struct {
	RoomID         uuid.UUID `db:"room_id" json:"room_id"`
	ExternalUserID *string   `db:"external_user_id" json:"external_user_id"`
}

func (q *Queries) GetParticipantByExternalUserAndRoom(ctx context.Context, arg GetParticipantByExternalUserAndRoomParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByExternalUserAndRoom, arg.RoomID, arg.ExternalUserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomHost = `-- name: GetRoomHost :one
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE room_id = $1 AND role = 'host' AND left_at IS NULL
ORDER BY joined_at ASC
LIMIT 1
`

func (q *Queries) GetRoomHost(ctx context.Context, roomID uuid.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getRoomHost, roomID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveParticipantsByRoom = `-- name: ListActiveParticipantsByRoom :many
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE room_id = $1 AND left_at IS NULL
ORDER BY joined_at ASC
`

func (q *Queries) ListActiveParticipantsByRoom(ctx context.Context, roomID uuid.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CloudflareParticipantID,
			&i.ExternalUserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByRoom = `-- name: ListParticipantsByRoom :many
SELECT id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at FROM participants
WHERE room_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListParticipantsByRoom(ctx context.Context, roomID uuid.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipantsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CloudflareParticipantID,
			&i.ExternalUserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsWithRoomInfo = `-- name: ListParticipantsWithRoomInfo :many
SELECT
    p.id, p.room_id, p.cloudflare_participant_id, p.external_user_id, p.display_name, p.role, p.joined_at, p.left_at, p.created_at,
    r.name as room_name,
    r.status as room_status
FROM participants p
JOIN rooms r ON r.id = p.room_id
WHERE p.external_user_id = $1
ORDER BY p.joined_at DESC
LIMIT $2 OFFSET $3
`

type ListParticipantsWithRoomInfoParams struct {
	ExternalUserID *string `db:"external_user_id" json:"external_user_id"`
	Limit          int32   `db:"limit" json:"limit"`
	Offset         int32   `db:"offset" json:"offset"`
}

type ListParticipantsWithRoomInfoRow struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	RoomID                  uuid.UUID          `db:"room_id" json:"room_id"`
	CloudflareParticipantID string             `db:"cloudflare_participant_id" json:"cloudflare_participant_id"`
	ExternalUserID          *string            `db:"external_user_id" json:"external_user_id"`
	DisplayName             *string            `db:"display_name" json:"display_name"`
	Role                    string             `db:"role" json:"role"`
	JoinedAt                pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt                  pgtype.Timestamptz `db:"left_at" json:"left_at"`
	CreatedAt               time.Time          `db:"created_at" json:"created_at"`
	RoomName                *string            `db:"room_name" json:"room_name"`
	RoomStatus              string             `db:"room_status" json:"room_status"`
}

func (q *Queries) ListParticipantsWithRoomInfo(ctx context.Context, arg ListParticipantsWithRoomInfoParams) ([]ListParticipantsWithRoomInfoRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsWithRoomInfo, arg.ExternalUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsWithRoomInfoRow{}
	for rows.Next() {
		var i ListParticipantsWithRoomInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CloudflareParticipantID,
			&i.ExternalUserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.RoomName,
			&i.RoomStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantLeave = `-- name: ParticipantLeave :one
UPDATE participants
SET left_at = NOW()
WHERE id = $1
RETURNING id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at
`

func (q *Queries) ParticipantLeave(ctx context.Context, id uuid.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, participantLeave, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const participantLeaveByCloudflareID = `-- name: ParticipantLeaveByCloudflareID :one
UPDATE participants
SET left_at = NOW()
WHERE cloudflare_participant_id = $1 AND left_at IS NULL
RETURNING id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at
`

func (q *Queries) ParticipantLeaveByCloudflareID(ctx context.Context, cloudflareParticipantID string) (Participant, error) {
	row := q.db.QueryRow(ctx, participantLeaveByCloudflareID, cloudflareParticipantID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateParticipant = `-- name: UpdateParticipant :one
UPDATE participants
SET
    display_name = COALESCE($2, display_name),
    role = COALESCE($3, role)
WHERE id = $1
RETURNING id, room_id, cloudflare_participant_id, external_user_id, display_name, role, joined_at, left_at, created_at
`

type UpdateParticipantParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	DisplayName *string   `db:"display_name" json:"display_name"`
	Role        *string   `db:"role" json:"role"`
}

func (q *Queries) UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipant, arg.ID, arg.DisplayName, arg.Role)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CloudflareParticipantID,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}
