// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_meeting_transcripts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostMeetingTranscript = `-- name: CreatePostMeetingTranscript :one

INSERT INTO post_meeting_transcripts (recording_id, room_id, provider, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at
`

type CreatePostMeetingTranscriptParams struct {
	RecordingID uuid.UUID `db:"recording_id" json:"recording_id"`
	RoomID      uuid.UUID `db:"room_id" json:"room_id"`
	Provider    *string   `db:"provider" json:"provider"`
}

// Post-Meeting Transcripts Queries
// CRUD operations for post-meeting transcription
func (q *Queries) CreatePostMeetingTranscript(ctx context.Context, arg CreatePostMeetingTranscriptParams) (PostMeetingTranscript, error) {
	row := q.db.QueryRow(ctx, createPostMeetingTranscript, arg.RecordingID, arg.RoomID, arg.Provider)
	var i PostMeetingTranscript
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.RoomID,
		&i.TranscriptText,
		&i.TranscriptJson,
		&i.Language,
		&i.DurationSeconds,
		&i.WordCount,
		&i.Provider,
		&i.Summary,
		&i.ActionItems,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingTranscripts = `-- name: GetPendingTranscripts :many
SELECT id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at FROM post_meeting_transcripts
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingTranscripts(ctx context.Context, limit int32) ([]PostMeetingTranscript, error) {
	rows, err := q.db.Query(ctx, getPendingTranscripts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostMeetingTranscript{}
	for rows.Next() {
		var i PostMeetingTranscript
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RoomID,
			&i.TranscriptText,
			&i.TranscriptJson,
			&i.Language,
			&i.DurationSeconds,
			&i.WordCount,
			&i.Provider,
			&i.Summary,
			&i.ActionItems,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostMeetingTranscript = `-- name: GetPostMeetingTranscript :one
SELECT id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at FROM post_meeting_transcripts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostMeetingTranscript(ctx context.Context, id uuid.UUID) (PostMeetingTranscript, error) {
	row := q.db.QueryRow(ctx, getPostMeetingTranscript, id)
	var i PostMeetingTranscript
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.RoomID,
		&i.TranscriptText,
		&i.TranscriptJson,
		&i.Language,
		&i.DurationSeconds,
		&i.WordCount,
		&i.Provider,
		&i.Summary,
		&i.ActionItems,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPostMeetingTranscriptByRecordingID = `-- name: GetPostMeetingTranscriptByRecordingID :one
SELECT id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at FROM post_meeting_transcripts
WHERE recording_id = $1 LIMIT 1
`

func (q *Queries) GetPostMeetingTranscriptByRecordingID(ctx context.Context, recordingID uuid.UUID) (PostMeetingTranscript, error) {
	row := q.db.QueryRow(ctx, getPostMeetingTranscriptByRecordingID, recordingID)
	var i PostMeetingTranscript
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.RoomID,
		&i.TranscriptText,
		&i.TranscriptJson,
		&i.Language,
		&i.DurationSeconds,
		&i.WordCount,
		&i.Provider,
		&i.Summary,
		&i.ActionItems,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProcessingTranscripts = `-- name: GetProcessingTranscripts :many
SELECT id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at FROM post_meeting_transcripts
WHERE status = 'processing'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetProcessingTranscripts(ctx context.Context, limit int32) ([]PostMeetingTranscript, error) {
	rows, err := q.db.Query(ctx, getProcessingTranscripts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostMeetingTranscript{}
	for rows.Next() {
		var i PostMeetingTranscript
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RoomID,
			&i.TranscriptText,
			&i.TranscriptJson,
			&i.Language,
			&i.DurationSeconds,
			&i.WordCount,
			&i.Provider,
			&i.Summary,
			&i.ActionItems,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostMeetingTranscriptsByRoom = `-- name: ListPostMeetingTranscriptsByRoom :many
SELECT id, recording_id, room_id, transcript_text, transcript_json, language, duration_seconds, word_count, provider, summary, action_items, status, error_message, created_at, completed_at FROM post_meeting_transcripts
WHERE room_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPostMeetingTranscriptsByRoom(ctx context.Context, roomID uuid.UUID) ([]PostMeetingTranscript, error) {
	rows, err := q.db.Query(ctx, listPostMeetingTranscriptsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostMeetingTranscript{}
	for rows.Next() {
		var i PostMeetingTranscript
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RoomID,
			&i.TranscriptText,
			&i.TranscriptJson,
			&i.Language,
			&i.DurationSeconds,
			&i.WordCount,
			&i.Provider,
			&i.Summary,
			&i.ActionItems,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostMeetingTranscriptFailed = `-- name: MarkPostMeetingTranscriptFailed :exec
UPDATE post_meeting_transcripts
SET status = 'failed', error_message = $2
WHERE id = $1
`

type MarkPostMeetingTranscriptFailedParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
}

func (q *Queries) MarkPostMeetingTranscriptFailed(ctx context.Context, arg MarkPostMeetingTranscriptFailedParams) error {
	_, err := q.db.Exec(ctx, markPostMeetingTranscriptFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markPostMeetingTranscriptProcessing = `-- name: MarkPostMeetingTranscriptProcessing :exec
UPDATE post_meeting_transcripts
SET status = 'processing'
WHERE id = $1
`

func (q *Queries) MarkPostMeetingTranscriptProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPostMeetingTranscriptProcessing, id)
	return err
}

const updatePostMeetingTranscriptAI = `-- name: UpdatePostMeetingTranscriptAI :exec
UPDATE post_meeting_transcripts
SET summary = $2, action_items = $3
WHERE id = $1
`

type UpdatePostMeetingTranscriptAIParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Summary     *string   `db:"summary" json:"summary"`
	ActionItems []string  `db:"action_items" json:"action_items"`
}

func (q *Queries) UpdatePostMeetingTranscriptAI(ctx context.Context, arg UpdatePostMeetingTranscriptAIParams) error {
	_, err := q.db.Exec(ctx, updatePostMeetingTranscriptAI, arg.ID, arg.Summary, arg.ActionItems)
	return err
}

const updatePostMeetingTranscriptResult = `-- name: UpdatePostMeetingTranscriptResult :exec
UPDATE post_meeting_transcripts
SET
    transcript_text = $2,
    transcript_json = $3,
    language = $4,
    duration_seconds = $5,
    word_count = $6,
    status = 'completed',
    completed_at = NOW()
WHERE id = $1
`

type UpdatePostMeetingTranscriptResultParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	TranscriptText  *string   `db:"transcript_text" json:"transcript_text"`
	TranscriptJson  []byte    `db:"transcript_json" json:"transcript_json"`
	Language        *string   `db:"language" json:"language"`
	DurationSeconds *int32    `db:"duration_seconds" json:"duration_seconds"`
	WordCount       *int32    `db:"word_count" json:"word_count"`
}

func (q *Queries) UpdatePostMeetingTranscriptResult(ctx context.Context, arg UpdatePostMeetingTranscriptResultParams) error {
	_, err := q.db.Exec(ctx, updatePostMeetingTranscriptResult,
		arg.ID,
		arg.TranscriptText,
		arg.TranscriptJson,
		arg.Language,
		arg.DurationSeconds,
		arg.WordCount,
	)
	return err
}

const updatePostMeetingTranscriptStatus = `-- name: UpdatePostMeetingTranscriptStatus :exec
UPDATE post_meeting_transcripts
SET status = $2, error_message = $3
WHERE id = $1
`

type UpdatePostMeetingTranscriptStatusParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Status       string    `db:"status" json:"status"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
}

func (q *Queries) UpdatePostMeetingTranscriptStatus(ctx context.Context, arg UpdatePostMeetingTranscriptStatusParams) error {
	_, err := q.db.Exec(ctx, updatePostMeetingTranscriptStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
