// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateScheduledRoom(ctx context.Context, id uuid.UUID) (Room, error)
	ActivateTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	AdminGetMeetingDurations(ctx context.Context) ([]AdminGetMeetingDurationsRow, error)
	// Admin Queries
	// Cross-tenant queries for the admin dashboard
	AdminGetOverview(ctx context.Context) (AdminGetOverviewRow, error)
	AdminGetRoom(ctx context.Context, id uuid.UUID) (AdminGetRoomRow, error)
	AdminGetStorageByProvider(ctx context.Context) ([]AdminGetStorageByProviderRow, error)
	AdminGetWebhookStats(ctx context.Context) (AdminGetWebhookStatsRow, error)
	AdminGetWhisperTranscriptionJobStats(ctx context.Context) (AdminGetWhisperTranscriptionJobStatsRow, error)
	AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]AdminListAuditLogsRow, error)
	AdminListRecordings(ctx context.Context, arg AdminListRecordingsParams) ([]AdminListRecordingsRow, error)
	AdminListRoomParticipants(ctx context.Context, roomID uuid.UUID) ([]Participant, error)
	AdminListRooms(ctx context.Context, arg AdminListRoomsParams) ([]AdminListRoomsRow, error)
	AdminListTenants(ctx context.Context, arg AdminListTenantsParams) ([]AdminListTenantsRow, error)
	AdminListTranscripts(ctx context.Context, arg AdminListTranscriptsParams) ([]AdminListTranscriptsRow, error)
	AdminListWebhookDeliveries(ctx context.Context, arg AdminListWebhookDeliveriesParams) ([]AdminListWebhookDeliveriesRow, error)
	AdminListWhisperTranscriptionJobs(ctx context.Context, arg AdminListWhisperTranscriptionJobsParams) ([]AdminListWhisperTranscriptionJobsRow, error)
	AdminListWhisperTranscriptionJobsByWhisperJobIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]AdminListWhisperTranscriptionJobsByWhisperJobIDsRow, error)
	AdminUpdateWhiteboardConfig(ctx context.Context, arg AdminUpdateWhiteboardConfigParams) (Tenant, error)
	ArchiveRecording(ctx context.Context, id uuid.UUID) (Recording, error)
	ArchiveRecordingWithPath(ctx context.Context, arg ArchiveRecordingWithPathParams) (Recording, error)
	BindInternalTenantToOwner(ctx context.Context, arg BindInternalTenantToOwnerParams) (Tenant, error)
	CompleteRecording(ctx context.Context, arg CompleteRecordingParams) (Recording, error)
	CountActiveParticipantsByRoom(ctx context.Context, roomID uuid.UUID) (int64, error)
	CountActiveRoomsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountActiveTenants(ctx context.Context) (int64, error)
	CountAuditLogsByAction(ctx context.Context, action string) (int64, error)
	CountAuditLogsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountMeetingsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountMeetingsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CountRoomsByTenantAndStatuses(ctx context.Context, arg CountRoomsByTenantAndStatusesParams) (int64, error)
	CountRoomsByWorkspaceAndStatuses(ctx context.Context, arg CountRoomsByWorkspaceAndStatusesParams) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountTranscriptsByRoom(ctx context.Context, roomID uuid.UUID) (int64, error)
	// Audit Log Queries
	// Logging operations for compliance and debugging
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Internal Tenant Queries
	// Chalk-owned app workspaces (web + mobile)
	CreateInternalTenant(ctx context.Context, arg CreateInternalTenantParams) (Tenant, error)
	// Participant Queries
	// CRUD operations and participant management
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error)
	// Post-Meeting Transcripts Queries
	// CRUD operations for post-meeting transcription
	CreatePostMeetingTranscript(ctx context.Context, arg CreatePostMeetingTranscriptParams) (PostMeetingTranscript, error)
	// Recording Queries
	// CRUD operations and recording management
	CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error)
	// Room Queries
	// CRUD operations and room management
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomWithID(ctx context.Context, arg CreateRoomWithIDParams) (Room, error)
	CreateScheduledRoom(ctx context.Context, arg CreateScheduledRoomParams) (Room, error)
	// Tenant Queries
	// CRUD operations and tenant-specific queries
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Tenant Claims Queries
	// Pre-signup internal tenant claim (single-use)
	CreateTenantClaim(ctx context.Context, arg CreateTenantClaimParams) (TenantClaim, error)
	// Transcript Queries
	// CRUD operations for meeting transcriptions
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error)
	// Users Queries
	// End-user auth for internal tenants
	CreateUser(ctx context.Context, email string) (User, error)
	// User Sessions Queries
	// Refresh sessions stored as hashed tokens
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	// Webhook Deliveries Queries
	// CRUD operations for webhook delivery tracking
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	// Whisper transcription job history
	CreateWhisperTranscriptionJob(ctx context.Context, arg CreateWhisperTranscriptionJobParams) (WhisperTranscriptionJob, error)
	// Workspace Queries
	// First-party ownership + collaboration scope under a shared tenant
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	CreateWorkspaceMembership(ctx context.Context, arg CreateWorkspaceMembershipParams) (WorkspaceMembership, error)
	DeactivateTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	DeleteOldAuditLogs(ctx context.Context, createdAt time.Time) error
	DeleteParticipant(ctx context.Context, id uuid.UUID) error
	DeleteRecording(ctx context.Context, id uuid.UUID) error
	DeleteRoom(ctx context.Context, id uuid.UUID) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteTranscriptsByRoom(ctx context.Context, roomID uuid.UUID) error
	EndRoom(ctx context.Context, id uuid.UUID) (Room, error)
	GetActiveRecordingByRoom(ctx context.Context, roomID uuid.UUID) (Recording, error)
	// Returns all allowed_origins from active tenants' tenant_config JSONB
	GetAllTenantAllowedOrigins(ctx context.Context) ([]string, error)
	GetAuditLog(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetAuditLogWithDetails(ctx context.Context, id uuid.UUID) (GetAuditLogWithDetailsRow, error)
	GetFailedWebhookDeliveries(ctx context.Context, arg GetFailedWebhookDeliveriesParams) ([]WebhookDelivery, error)
	GetInternalTenantByOwnerUserID(ctx context.Context, ownerUserID pgtype.UUID) (Tenant, error)
	GetParticipant(ctx context.Context, id uuid.UUID) (Participant, error)
	GetParticipantByCloudflareID(ctx context.Context, cloudflareParticipantID string) (Participant, error)
	GetParticipantByExternalUserAndRoom(ctx context.Context, arg GetParticipantByExternalUserAndRoomParams) (Participant, error)
	GetPendingTranscripts(ctx context.Context, limit int32) ([]PostMeetingTranscript, error)
	GetPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	GetPostMeetingTranscript(ctx context.Context, id uuid.UUID) (PostMeetingTranscript, error)
	GetPostMeetingTranscriptByRecordingID(ctx context.Context, recordingID uuid.UUID) (PostMeetingTranscript, error)
	GetProcessingTranscripts(ctx context.Context, limit int32) ([]PostMeetingTranscript, error)
	GetRecording(ctx context.Context, id uuid.UUID) (Recording, error)
	GetRecordingByCloudflareID(ctx context.Context, cloudflareRecordingID *string) (Recording, error)
	GetRecordingWithRoomInfo(ctx context.Context, id uuid.UUID) (GetRecordingWithRoomInfoRow, error)
	GetRoom(ctx context.Context, id uuid.UUID) (Room, error)
	GetRoomByCloudflareID(ctx context.Context, cloudflareMeetingID string) (Room, error)
	GetRoomByNameAndTenant(ctx context.Context, arg GetRoomByNameAndTenantParams) (Room, error)
	GetRoomHost(ctx context.Context, roomID uuid.UUID) (Participant, error)
	GetRoomWithParticipantCount(ctx context.Context, id uuid.UUID) (GetRoomWithParticipantCountRow, error)
	GetSharedInternalTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByAPIKeyHash(ctx context.Context, apiKeyHash string) (Tenant, error)
	GetTenantByAPIKeyLookupHash(ctx context.Context, apiKeyLookupHash *string) (Tenant, error)
	GetTenantByRoomID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantClaimBySecretHash(ctx context.Context, secretHash string) (TenantClaim, error)
	GetTotalRecordingStorageByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	GetTranscript(ctx context.Context, id uuid.UUID) (Transcript, error)
	GetTranscriptByExternalID(ctx context.Context, externalID *string) (Transcript, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetWebhookDeliveriesByRoom(ctx context.Context, roomID uuid.UUID) ([]WebhookDelivery, error)
	GetWebhookDeliveriesByTenant(ctx context.Context, arg GetWebhookDeliveriesByTenantParams) ([]WebhookDelivery, error)
	GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceByTenantAndOwner(ctx context.Context, arg GetWorkspaceByTenantAndOwnerParams) (Workspace, error)
	ListActiveParticipantsByRoom(ctx context.Context, roomID uuid.UUID) ([]Participant, error)
	ListActiveRoomsByTenant(ctx context.Context, arg ListActiveRoomsByTenantParams) ([]Room, error)
	ListActiveRoomsWithParticipantCount(ctx context.Context, arg ListActiveRoomsWithParticipantCountParams) ([]ListActiveRoomsWithParticipantCountRow, error)
	// Minimal rowset for API key verification; only legacy keys without lookup hashes need scanning.
	ListActiveTenantAPIKeys(ctx context.Context, arg ListActiveTenantAPIKeysParams) ([]ListActiveTenantAPIKeysRow, error)
	ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByResourceType(ctx context.Context, arg ListAuditLogsByResourceTypeParams) ([]AuditLog, error)
	ListAuditLogsByRoom(ctx context.Context, arg ListAuditLogsByRoomParams) ([]AuditLog, error)
	ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]AuditLog, error)
	ListAuditLogsByTenantAndAction(ctx context.Context, arg ListAuditLogsByTenantAndActionParams) ([]AuditLog, error)
	ListAuditLogsByTenantInDateRange(ctx context.Context, arg ListAuditLogsByTenantInDateRangeParams) ([]AuditLog, error)
	ListEmptyActiveRooms(ctx context.Context, dollar_1 interface{}) ([]Room, error)
	// Internal Retention Queries
	// Delete recordings after retention window (internal tenants only)
	ListInternalRecordingsForDeletion(ctx context.Context, arg ListInternalRecordingsForDeletionParams) ([]Recording, error)
	// Internal Meetings Queries
	// Dashboard rows (room + recording + transcript summary)
	ListMeetingsByTenant(ctx context.Context, arg ListMeetingsByTenantParams) ([]ListMeetingsByTenantRow, error)
	ListMeetingsByWorkspace(ctx context.Context, arg ListMeetingsByWorkspaceParams) ([]ListMeetingsByWorkspaceRow, error)
	ListParticipantsByRoom(ctx context.Context, roomID uuid.UUID) ([]Participant, error)
	ListParticipantsWithRoomInfo(ctx context.Context, arg ListParticipantsWithRoomInfoParams) ([]ListParticipantsWithRoomInfoRow, error)
	ListPostMeetingTranscriptsByRoom(ctx context.Context, roomID uuid.UUID) ([]PostMeetingTranscript, error)
	ListRecordings(ctx context.Context, arg ListRecordingsParams) ([]Recording, error)
	ListRecordingsByRoom(ctx context.Context, roomID uuid.UUID) ([]Recording, error)
	ListRecordingsByStatus(ctx context.Context, arg ListRecordingsByStatusParams) ([]Recording, error)
	ListRecordingsByTenant(ctx context.Context, arg ListRecordingsByTenantParams) ([]ListRecordingsByTenantRow, error)
	ListRecordingsByWorkspace(ctx context.Context, arg ListRecordingsByWorkspaceParams) ([]ListRecordingsByWorkspaceRow, error)
	ListRecordingsReadyForArchive(ctx context.Context, limit int32) ([]Recording, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	ListRoomsByTenant(ctx context.Context, arg ListRoomsByTenantParams) ([]Room, error)
	ListRoomsWithParticipantCountByStatuses(ctx context.Context, arg ListRoomsWithParticipantCountByStatusesParams) ([]ListRoomsWithParticipantCountByStatusesRow, error)
	ListRoomsWithParticipantCountByWorkspaceAndStatuses(ctx context.Context, arg ListRoomsWithParticipantCountByWorkspaceAndStatusesParams) ([]ListRoomsWithParticipantCountByWorkspaceAndStatusesRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListTranscriptsByRoom(ctx context.Context, arg ListTranscriptsByRoomParams) ([]Transcript, error)
	MarkPostMeetingTranscriptFailed(ctx context.Context, arg MarkPostMeetingTranscriptFailedParams) error
	MarkPostMeetingTranscriptProcessing(ctx context.Context, id uuid.UUID) error
	MarkRecordingDeleted(ctx context.Context, id uuid.UUID) (Recording, error)
	MarkRecordingFailed(ctx context.Context, id uuid.UUID) (Recording, error)
	MarkTenantClaimUsed(ctx context.Context, id uuid.UUID) (TenantClaim, error)
	MarkWebhookDelivered(ctx context.Context, id uuid.UUID) error
	MarkWebhookSending(ctx context.Context, id uuid.UUID) error
	MarkWhisperTranscriptionJobCompleted(ctx context.Context, arg MarkWhisperTranscriptionJobCompletedParams) error
	MarkWhisperTranscriptionJobFailed(ctx context.Context, arg MarkWhisperTranscriptionJobFailedParams) error
	MarkWhisperTranscriptionJobTimedOut(ctx context.Context, arg MarkWhisperTranscriptionJobTimedOutParams) error
	ParticipantLeave(ctx context.Context, id uuid.UUID) (Participant, error)
	ParticipantLeaveByCloudflareID(ctx context.Context, cloudflareParticipantID string) (Participant, error)
	ReactivateRoom(ctx context.Context, arg ReactivateRoomParams) (Room, error)
	RevokeUserSession(ctx context.Context, id uuid.UUID) error
	RotateTenantAPIKey(ctx context.Context, arg RotateTenantAPIKeyParams) (Tenant, error)
	StopRecording(ctx context.Context, id uuid.UUID) (Recording, error)
	TouchUserSession(ctx context.Context, id uuid.UUID) error
	UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) (Participant, error)
	UpdatePostMeetingTranscriptAI(ctx context.Context, arg UpdatePostMeetingTranscriptAIParams) error
	UpdatePostMeetingTranscriptResult(ctx context.Context, arg UpdatePostMeetingTranscriptResultParams) error
	UpdatePostMeetingTranscriptStatus(ctx context.Context, arg UpdatePostMeetingTranscriptStatusParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTenantAPIKeyLookupHash(ctx context.Context, arg UpdateTenantAPIKeyLookupHashParams) error
	UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (Tenant, error)
	UpdateWebhookDeliveryAttempt(ctx context.Context, arg UpdateWebhookDeliveryAttemptParams) error
}

var _ Querier = (*Queries)(nil)
