// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateScheduledRoom = `-- name: ActivateScheduledRoom :one
UPDATE rooms
SET
    status = 'active',
    started_at = COALESCE(started_at, NOW()),
    ended_at = NULL
WHERE id = $1 AND status = 'scheduled'
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

func (q *Queries) ActivateScheduledRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, activateScheduledRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const countActiveRoomsByTenant = `-- name: CountActiveRoomsByTenant :one
SELECT COUNT(*) FROM rooms
WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveRoomsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRoomsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomsByTenantAndStatuses = `-- name: CountRoomsByTenantAndStatuses :one
SELECT COUNT(*) FROM rooms
WHERE tenant_id = $1 AND status = ANY($2::text[])
`

type CountRoomsByTenantAndStatusesParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Statuses []string  `db:"statuses" json:"statuses"`
}

func (q *Queries) CountRoomsByTenantAndStatuses(ctx context.Context, arg CountRoomsByTenantAndStatusesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomsByTenantAndStatuses, arg.TenantID, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomsByWorkspaceAndStatuses = `-- name: CountRoomsByWorkspaceAndStatuses :one
SELECT COUNT(*) FROM rooms
WHERE workspace_id = $1 AND status = ANY($2::text[])
`

type CountRoomsByWorkspaceAndStatusesParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Statuses    []string    `db:"statuses" json:"statuses"`
}

func (q *Queries) CountRoomsByWorkspaceAndStatuses(ctx context.Context, arg CountRoomsByWorkspaceAndStatusesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomsByWorkspaceAndStatuses, arg.WorkspaceID, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (
    tenant_id,
    workspace_id,
    created_by_user_id,
    cloudflare_meeting_id,
    name,
    config,
    started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

type CreateRoomParams struct {
	TenantID            uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	WorkspaceID         pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID     pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
	CloudflareMeetingID string      `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                *string     `db:"name" json:"name"`
	Config              []byte      `db:"config" json:"config"`
}

// Room Queries
// CRUD operations and room management
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.TenantID,
		arg.WorkspaceID,
		arg.CreatedByUserID,
		arg.CloudflareMeetingID,
		arg.Name,
		arg.Config,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const createRoomWithID = `-- name: CreateRoomWithID :one
INSERT INTO rooms (
    id,
    tenant_id,
    workspace_id,
    created_by_user_id,
    cloudflare_meeting_id,
    name,
    config,
    started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

type CreateRoomWithIDParams struct {
	ID                  uuid.UUID   `db:"id" json:"id"`
	TenantID            uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	WorkspaceID         pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID     pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
	CloudflareMeetingID string      `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                *string     `db:"name" json:"name"`
	Config              []byte      `db:"config" json:"config"`
}

func (q *Queries) CreateRoomWithID(ctx context.Context, arg CreateRoomWithIDParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoomWithID,
		arg.ID,
		arg.TenantID,
		arg.WorkspaceID,
		arg.CreatedByUserID,
		arg.CloudflareMeetingID,
		arg.Name,
		arg.Config,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const createScheduledRoom = `-- name: CreateScheduledRoom :one
INSERT INTO rooms (
    tenant_id,
    workspace_id,
    created_by_user_id,
    cloudflare_meeting_id,
    name,
    config,
    status,
    scheduled_start_at,
    scheduled_end_at,
    allow_early_join_minutes
) VALUES (
    $1, $2, $3, $4, $5, $6, 'scheduled', $7, $8, $9
)
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

type CreateScheduledRoomParams struct {
	TenantID              uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	WorkspaceID           pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID       pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CloudflareMeetingID   string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                  *string            `db:"name" json:"name"`
	Config                []byte             `db:"config" json:"config"`
	ScheduledStartAt      pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt        pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
}

func (q *Queries) CreateScheduledRoom(ctx context.Context, arg CreateScheduledRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createScheduledRoom,
		arg.TenantID,
		arg.WorkspaceID,
		arg.CreatedByUserID,
		arg.CloudflareMeetingID,
		arg.Name,
		arg.Config,
		arg.ScheduledStartAt,
		arg.ScheduledEndAt,
		arg.AllowEarlyJoinMinutes,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const endRoom = `-- name: EndRoom :one
UPDATE rooms
SET
    status = 'ended',
    ended_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

func (q *Queries) EndRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, endRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const getRoomByCloudflareID = `-- name: GetRoomByCloudflareID :one
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
WHERE cloudflare_meeting_id = $1 LIMIT 1
`

func (q *Queries) GetRoomByCloudflareID(ctx context.Context, cloudflareMeetingID string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCloudflareID, cloudflareMeetingID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const getRoomByNameAndTenant = `-- name: GetRoomByNameAndTenant :one
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
WHERE name = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetRoomByNameAndTenantParams struct {
	Name     *string   `db:"name" json:"name"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetRoomByNameAndTenant(ctx context.Context, arg GetRoomByNameAndTenantParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByNameAndTenant, arg.Name, arg.TenantID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const getRoomWithParticipantCount = `-- name: GetRoomWithParticipantCount :one
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata, r.scheduled_start_at, r.scheduled_end_at, r.allow_early_join_minutes, r.screen_annotation_state, r.workspace_id, r.created_by_user_id,
    COUNT(p.id) FILTER (WHERE p.left_at IS NULL) as active_participant_count
FROM rooms r
LEFT JOIN participants p ON p.room_id = r.id
WHERE r.id = $1
GROUP BY r.id
`

type GetRoomWithParticipantCountRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	ScheduledStartAt       pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt         pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes  int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
	ScreenAnnotationState  []byte             `db:"screen_annotation_state" json:"screen_annotation_state"`
	WorkspaceID            pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) GetRoomWithParticipantCount(ctx context.Context, id uuid.UUID) (GetRoomWithParticipantCountRow, error) {
	row := q.db.QueryRow(ctx, getRoomWithParticipantCount, id)
	var i GetRoomWithParticipantCountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
		&i.ActiveParticipantCount,
	)
	return i, err
}

const listActiveRoomsByTenant = `-- name: ListActiveRoomsByTenant :many
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
WHERE tenant_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveRoomsByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListActiveRoomsByTenant(ctx context.Context, arg ListActiveRoomsByTenantParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listActiveRoomsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRoomsWithParticipantCount = `-- name: ListActiveRoomsWithParticipantCount :many
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata, r.scheduled_start_at, r.scheduled_end_at, r.allow_early_join_minutes, r.screen_annotation_state, r.workspace_id, r.created_by_user_id,
    COUNT(p.id) FILTER (WHERE p.left_at IS NULL) as active_participant_count
FROM rooms r
LEFT JOIN participants p ON p.room_id = r.id
WHERE r.tenant_id = $1 AND r.status = 'active'
GROUP BY r.id
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveRoomsWithParticipantCountParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

type ListActiveRoomsWithParticipantCountRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	ScheduledStartAt       pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt         pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes  int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
	ScreenAnnotationState  []byte             `db:"screen_annotation_state" json:"screen_annotation_state"`
	WorkspaceID            pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) ListActiveRoomsWithParticipantCount(ctx context.Context, arg ListActiveRoomsWithParticipantCountParams) ([]ListActiveRoomsWithParticipantCountRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoomsWithParticipantCount, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRoomsWithParticipantCountRow{}
	for rows.Next() {
		var i ListActiveRoomsWithParticipantCountRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
			&i.ActiveParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmptyActiveRooms = `-- name: ListEmptyActiveRooms :many
SELECT r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata, r.scheduled_start_at, r.scheduled_end_at, r.allow_early_join_minutes, r.screen_annotation_state, r.workspace_id, r.created_by_user_id FROM rooms r
LEFT JOIN participants p ON p.room_id = r.id AND p.left_at IS NULL
WHERE r.status = 'active'
  AND r.created_at < NOW() - INTERVAL '1 minute' * $1
GROUP BY r.id
HAVING COUNT(p.id) = 0
`

func (q *Queries) ListEmptyActiveRooms(ctx context.Context, dollar_1 interface{}) ([]Room, error) {
	rows, err := q.db.Query(ctx, listEmptyActiveRooms, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByTenant = `-- name: ListRoomsByTenant :many
SELECT id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id FROM rooms
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRoomsByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListRoomsByTenant(ctx context.Context, arg ListRoomsByTenantParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsWithParticipantCountByStatuses = `-- name: ListRoomsWithParticipantCountByStatuses :many
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata, r.scheduled_start_at, r.scheduled_end_at, r.allow_early_join_minutes, r.screen_annotation_state, r.workspace_id, r.created_by_user_id,
    COUNT(p.id) FILTER (WHERE p.left_at IS NULL) as active_participant_count
FROM rooms r
LEFT JOIN participants p ON p.room_id = r.id
WHERE r.tenant_id = $1
  AND r.status = ANY($2::text[])
GROUP BY r.id
ORDER BY
    CASE
        WHEN r.status = 'scheduled' THEN COALESCE(r.scheduled_start_at, r.created_at)
        ELSE r.created_at
    END DESC
LIMIT $4 OFFSET $3
`

type ListRoomsWithParticipantCountByStatusesParams struct {
	TenantID    uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Statuses    []string  `db:"statuses" json:"statuses"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

type ListRoomsWithParticipantCountByStatusesRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	ScheduledStartAt       pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt         pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes  int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
	ScreenAnnotationState  []byte             `db:"screen_annotation_state" json:"screen_annotation_state"`
	WorkspaceID            pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) ListRoomsWithParticipantCountByStatuses(ctx context.Context, arg ListRoomsWithParticipantCountByStatusesParams) ([]ListRoomsWithParticipantCountByStatusesRow, error) {
	rows, err := q.db.Query(ctx, listRoomsWithParticipantCountByStatuses,
		arg.TenantID,
		arg.Statuses,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsWithParticipantCountByStatusesRow{}
	for rows.Next() {
		var i ListRoomsWithParticipantCountByStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
			&i.ActiveParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsWithParticipantCountByWorkspaceAndStatuses = `-- name: ListRoomsWithParticipantCountByWorkspaceAndStatuses :many
SELECT
    r.id, r.tenant_id, r.cloudflare_meeting_id, r.name, r.config, r.status, r.started_at, r.ended_at, r.created_at, r.updated_at, r.whiteboard_state, r.metadata, r.scheduled_start_at, r.scheduled_end_at, r.allow_early_join_minutes, r.screen_annotation_state, r.workspace_id, r.created_by_user_id,
    COUNT(p.id) FILTER (WHERE p.left_at IS NULL) as active_participant_count
FROM rooms r
LEFT JOIN participants p ON p.room_id = r.id
WHERE r.workspace_id = $1
  AND r.status = ANY($2::text[])
GROUP BY r.id
ORDER BY
    CASE
        WHEN r.status = 'scheduled' THEN COALESCE(r.scheduled_start_at, r.created_at)
        ELSE r.created_at
    END DESC
LIMIT $4 OFFSET $3
`

type ListRoomsWithParticipantCountByWorkspaceAndStatusesParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Statuses    []string    `db:"statuses" json:"statuses"`
	OffsetCount int32       `db:"offset_count" json:"offset_count"`
	LimitCount  int32       `db:"limit_count" json:"limit_count"`
}

type ListRoomsWithParticipantCountByWorkspaceAndStatusesRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TenantID               uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CloudflareMeetingID    string             `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
	Name                   *string            `db:"name" json:"name"`
	Config                 []byte             `db:"config" json:"config"`
	Status                 string             `db:"status" json:"status"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt              time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time          `db:"updated_at" json:"updated_at"`
	WhiteboardState        []byte             `db:"whiteboard_state" json:"whiteboard_state"`
	Metadata               []byte             `db:"metadata" json:"metadata"`
	ScheduledStartAt       pgtype.Timestamptz `db:"scheduled_start_at" json:"scheduled_start_at"`
	ScheduledEndAt         pgtype.Timestamptz `db:"scheduled_end_at" json:"scheduled_end_at"`
	AllowEarlyJoinMinutes  int32              `db:"allow_early_join_minutes" json:"allow_early_join_minutes"`
	ScreenAnnotationState  []byte             `db:"screen_annotation_state" json:"screen_annotation_state"`
	WorkspaceID            pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) ListRoomsWithParticipantCountByWorkspaceAndStatuses(ctx context.Context, arg ListRoomsWithParticipantCountByWorkspaceAndStatusesParams) ([]ListRoomsWithParticipantCountByWorkspaceAndStatusesRow, error) {
	rows, err := q.db.Query(ctx, listRoomsWithParticipantCountByWorkspaceAndStatuses,
		arg.WorkspaceID,
		arg.Statuses,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsWithParticipantCountByWorkspaceAndStatusesRow{}
	for rows.Next() {
		var i ListRoomsWithParticipantCountByWorkspaceAndStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudflareMeetingID,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteboardState,
			&i.Metadata,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.AllowEarlyJoinMinutes,
			&i.ScreenAnnotationState,
			&i.WorkspaceID,
			&i.CreatedByUserID,
			&i.ActiveParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateRoom = `-- name: ReactivateRoom :one
UPDATE rooms
SET
    status = 'active',
    cloudflare_meeting_id = $2,
    started_at = NOW(),
    ended_at = NULL
WHERE id = $1
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

type ReactivateRoomParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	CloudflareMeetingID string    `db:"cloudflare_meeting_id" json:"cloudflare_meeting_id"`
}

func (q *Queries) ReactivateRoom(ctx context.Context, arg ReactivateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, reactivateRoom, arg.ID, arg.CloudflareMeetingID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
    name = COALESCE($2, name),
    config = COALESCE($3, config)
WHERE id = $1
RETURNING id, tenant_id, cloudflare_meeting_id, name, config, status, started_at, ended_at, created_at, updated_at, whiteboard_state, metadata, scheduled_start_at, scheduled_end_at, allow_early_join_minutes, screen_annotation_state, workspace_id, created_by_user_id
`

type UpdateRoomParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   *string   `db:"name" json:"name"`
	Config []byte    `db:"config" json:"config"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.ID, arg.Name, arg.Config)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudflareMeetingID,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteboardState,
		&i.Metadata,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.AllowEarlyJoinMinutes,
		&i.ScreenAnnotationState,
		&i.WorkspaceID,
		&i.CreatedByUserID,
	)
	return i, err
}
