// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whisper_transcription_jobs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetWhisperTranscriptionJobStats = `-- name: AdminGetWhisperTranscriptionJobStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'queued')::bigint AS queued,
    COUNT(*) FILTER (WHERE status = 'completed')::bigint AS completed,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed,
    COUNT(*) FILTER (WHERE status = 'timed_out')::bigint AS timed_out,
    COUNT(*)::bigint AS total
FROM whisper_transcription_jobs
`

type AdminGetWhisperTranscriptionJobStatsRow struct {
	Queued    int64 `db:"queued" json:"queued"`
	Completed int64 `db:"completed" json:"completed"`
	Failed    int64 `db:"failed" json:"failed"`
	TimedOut  int64 `db:"timed_out" json:"timed_out"`
	Total     int64 `db:"total" json:"total"`
}

func (q *Queries) AdminGetWhisperTranscriptionJobStats(ctx context.Context) (AdminGetWhisperTranscriptionJobStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetWhisperTranscriptionJobStats)
	var i AdminGetWhisperTranscriptionJobStatsRow
	err := row.Scan(
		&i.Queued,
		&i.Completed,
		&i.Failed,
		&i.TimedOut,
		&i.Total,
	)
	return i, err
}

const adminListWhisperTranscriptionJobs = `-- name: AdminListWhisperTranscriptionJobs :many
SELECT
    wtj.id, wtj.transcript_id, wtj.recording_id, wtj.room_id, wtj.provider, wtj.whisper_job_id, wtj.queue_key, wtj.audio_storage_path, wtj.traceparent, wtj.language_hint, wtj.status, wtj.queue_depth_at_enqueue, wtj.processing_queue_depth_at_enqueue, wtj.queue_depth_at_timeout, wtj.processing_queue_depth_at_timeout, wtj.result_language, wtj.duration_seconds, wtj.word_count, wtj.error_message, wtj.error_class, wtj.error_stage, wtj.download_http_status, wtj.download_size_bytes, wtj.created_at, wtj.completed_at,
    r.name AS room_name,
    t.name AS tenant_name
FROM whisper_transcription_jobs wtj
JOIN rooms r ON r.id = wtj.room_id
JOIN tenants t ON t.id = r.tenant_id
ORDER BY wtj.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListWhisperTranscriptionJobsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListWhisperTranscriptionJobsRow struct {
	ID                            uuid.UUID          `db:"id" json:"id"`
	TranscriptID                  uuid.UUID          `db:"transcript_id" json:"transcript_id"`
	RecordingID                   uuid.UUID          `db:"recording_id" json:"recording_id"`
	RoomID                        uuid.UUID          `db:"room_id" json:"room_id"`
	Provider                      string             `db:"provider" json:"provider"`
	WhisperJobID                  uuid.UUID          `db:"whisper_job_id" json:"whisper_job_id"`
	QueueKey                      string             `db:"queue_key" json:"queue_key"`
	AudioStoragePath              string             `db:"audio_storage_path" json:"audio_storage_path"`
	Traceparent                   *string            `db:"traceparent" json:"traceparent"`
	LanguageHint                  *string            `db:"language_hint" json:"language_hint"`
	Status                        string             `db:"status" json:"status"`
	QueueDepthAtEnqueue           *int64             `db:"queue_depth_at_enqueue" json:"queue_depth_at_enqueue"`
	ProcessingQueueDepthAtEnqueue *int64             `db:"processing_queue_depth_at_enqueue" json:"processing_queue_depth_at_enqueue"`
	QueueDepthAtTimeout           *int64             `db:"queue_depth_at_timeout" json:"queue_depth_at_timeout"`
	ProcessingQueueDepthAtTimeout *int64             `db:"processing_queue_depth_at_timeout" json:"processing_queue_depth_at_timeout"`
	ResultLanguage                *string            `db:"result_language" json:"result_language"`
	DurationSeconds               *int32             `db:"duration_seconds" json:"duration_seconds"`
	WordCount                     *int32             `db:"word_count" json:"word_count"`
	ErrorMessage                  *string            `db:"error_message" json:"error_message"`
	ErrorClass                    *string            `db:"error_class" json:"error_class"`
	ErrorStage                    *string            `db:"error_stage" json:"error_stage"`
	DownloadHttpStatus            *int32             `db:"download_http_status" json:"download_http_status"`
	DownloadSizeBytes             *int64             `db:"download_size_bytes" json:"download_size_bytes"`
	CreatedAt                     time.Time          `db:"created_at" json:"created_at"`
	CompletedAt                   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	RoomName                      *string            `db:"room_name" json:"room_name"`
	TenantName                    string             `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) AdminListWhisperTranscriptionJobs(ctx context.Context, arg AdminListWhisperTranscriptionJobsParams) ([]AdminListWhisperTranscriptionJobsRow, error) {
	rows, err := q.db.Query(ctx, adminListWhisperTranscriptionJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWhisperTranscriptionJobsRow{}
	for rows.Next() {
		var i AdminListWhisperTranscriptionJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.RecordingID,
			&i.RoomID,
			&i.Provider,
			&i.WhisperJobID,
			&i.QueueKey,
			&i.AudioStoragePath,
			&i.Traceparent,
			&i.LanguageHint,
			&i.Status,
			&i.QueueDepthAtEnqueue,
			&i.ProcessingQueueDepthAtEnqueue,
			&i.QueueDepthAtTimeout,
			&i.ProcessingQueueDepthAtTimeout,
			&i.ResultLanguage,
			&i.DurationSeconds,
			&i.WordCount,
			&i.ErrorMessage,
			&i.ErrorClass,
			&i.ErrorStage,
			&i.DownloadHttpStatus,
			&i.DownloadSizeBytes,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.RoomName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListWhisperTranscriptionJobsByWhisperJobIDs = `-- name: AdminListWhisperTranscriptionJobsByWhisperJobIDs :many
SELECT
    wtj.id, wtj.transcript_id, wtj.recording_id, wtj.room_id, wtj.provider, wtj.whisper_job_id, wtj.queue_key, wtj.audio_storage_path, wtj.traceparent, wtj.language_hint, wtj.status, wtj.queue_depth_at_enqueue, wtj.processing_queue_depth_at_enqueue, wtj.queue_depth_at_timeout, wtj.processing_queue_depth_at_timeout, wtj.result_language, wtj.duration_seconds, wtj.word_count, wtj.error_message, wtj.error_class, wtj.error_stage, wtj.download_http_status, wtj.download_size_bytes, wtj.created_at, wtj.completed_at,
    r.name AS room_name,
    t.name AS tenant_name
FROM whisper_transcription_jobs wtj
JOIN rooms r ON r.id = wtj.room_id
JOIN tenants t ON t.id = r.tenant_id
WHERE wtj.whisper_job_id = ANY($1::uuid[])
ORDER BY wtj.created_at DESC
`

type AdminListWhisperTranscriptionJobsByWhisperJobIDsRow struct {
	ID                            uuid.UUID          `db:"id" json:"id"`
	TranscriptID                  uuid.UUID          `db:"transcript_id" json:"transcript_id"`
	RecordingID                   uuid.UUID          `db:"recording_id" json:"recording_id"`
	RoomID                        uuid.UUID          `db:"room_id" json:"room_id"`
	Provider                      string             `db:"provider" json:"provider"`
	WhisperJobID                  uuid.UUID          `db:"whisper_job_id" json:"whisper_job_id"`
	QueueKey                      string             `db:"queue_key" json:"queue_key"`
	AudioStoragePath              string             `db:"audio_storage_path" json:"audio_storage_path"`
	Traceparent                   *string            `db:"traceparent" json:"traceparent"`
	LanguageHint                  *string            `db:"language_hint" json:"language_hint"`
	Status                        string             `db:"status" json:"status"`
	QueueDepthAtEnqueue           *int64             `db:"queue_depth_at_enqueue" json:"queue_depth_at_enqueue"`
	ProcessingQueueDepthAtEnqueue *int64             `db:"processing_queue_depth_at_enqueue" json:"processing_queue_depth_at_enqueue"`
	QueueDepthAtTimeout           *int64             `db:"queue_depth_at_timeout" json:"queue_depth_at_timeout"`
	ProcessingQueueDepthAtTimeout *int64             `db:"processing_queue_depth_at_timeout" json:"processing_queue_depth_at_timeout"`
	ResultLanguage                *string            `db:"result_language" json:"result_language"`
	DurationSeconds               *int32             `db:"duration_seconds" json:"duration_seconds"`
	WordCount                     *int32             `db:"word_count" json:"word_count"`
	ErrorMessage                  *string            `db:"error_message" json:"error_message"`
	ErrorClass                    *string            `db:"error_class" json:"error_class"`
	ErrorStage                    *string            `db:"error_stage" json:"error_stage"`
	DownloadHttpStatus            *int32             `db:"download_http_status" json:"download_http_status"`
	DownloadSizeBytes             *int64             `db:"download_size_bytes" json:"download_size_bytes"`
	CreatedAt                     time.Time          `db:"created_at" json:"created_at"`
	CompletedAt                   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	RoomName                      *string            `db:"room_name" json:"room_name"`
	TenantName                    string             `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) AdminListWhisperTranscriptionJobsByWhisperJobIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]AdminListWhisperTranscriptionJobsByWhisperJobIDsRow, error) {
	rows, err := q.db.Query(ctx, adminListWhisperTranscriptionJobsByWhisperJobIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWhisperTranscriptionJobsByWhisperJobIDsRow{}
	for rows.Next() {
		var i AdminListWhisperTranscriptionJobsByWhisperJobIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.RecordingID,
			&i.RoomID,
			&i.Provider,
			&i.WhisperJobID,
			&i.QueueKey,
			&i.AudioStoragePath,
			&i.Traceparent,
			&i.LanguageHint,
			&i.Status,
			&i.QueueDepthAtEnqueue,
			&i.ProcessingQueueDepthAtEnqueue,
			&i.QueueDepthAtTimeout,
			&i.ProcessingQueueDepthAtTimeout,
			&i.ResultLanguage,
			&i.DurationSeconds,
			&i.WordCount,
			&i.ErrorMessage,
			&i.ErrorClass,
			&i.ErrorStage,
			&i.DownloadHttpStatus,
			&i.DownloadSizeBytes,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.RoomName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWhisperTranscriptionJob = `-- name: CreateWhisperTranscriptionJob :one

INSERT INTO whisper_transcription_jobs (
    transcript_id,
    recording_id,
    room_id,
    provider,
    whisper_job_id,
    queue_key,
    audio_storage_path,
    traceparent,
    language_hint,
    status,
    queue_depth_at_enqueue,
    processing_queue_depth_at_enqueue
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'queued', $10, $11
)
RETURNING id, transcript_id, recording_id, room_id, provider, whisper_job_id, queue_key, audio_storage_path, traceparent, language_hint, status, queue_depth_at_enqueue, processing_queue_depth_at_enqueue, queue_depth_at_timeout, processing_queue_depth_at_timeout, result_language, duration_seconds, word_count, error_message, error_class, error_stage, download_http_status, download_size_bytes, created_at, completed_at
`

type CreateWhisperTranscriptionJobParams struct {
	TranscriptID                  uuid.UUID `db:"transcript_id" json:"transcript_id"`
	RecordingID                   uuid.UUID `db:"recording_id" json:"recording_id"`
	RoomID                        uuid.UUID `db:"room_id" json:"room_id"`
	Provider                      string    `db:"provider" json:"provider"`
	WhisperJobID                  uuid.UUID `db:"whisper_job_id" json:"whisper_job_id"`
	QueueKey                      string    `db:"queue_key" json:"queue_key"`
	AudioStoragePath              string    `db:"audio_storage_path" json:"audio_storage_path"`
	Traceparent                   *string   `db:"traceparent" json:"traceparent"`
	LanguageHint                  *string   `db:"language_hint" json:"language_hint"`
	QueueDepthAtEnqueue           *int64    `db:"queue_depth_at_enqueue" json:"queue_depth_at_enqueue"`
	ProcessingQueueDepthAtEnqueue *int64    `db:"processing_queue_depth_at_enqueue" json:"processing_queue_depth_at_enqueue"`
}

// Whisper transcription job history
func (q *Queries) CreateWhisperTranscriptionJob(ctx context.Context, arg CreateWhisperTranscriptionJobParams) (WhisperTranscriptionJob, error) {
	row := q.db.QueryRow(ctx, createWhisperTranscriptionJob,
		arg.TranscriptID,
		arg.RecordingID,
		arg.RoomID,
		arg.Provider,
		arg.WhisperJobID,
		arg.QueueKey,
		arg.AudioStoragePath,
		arg.Traceparent,
		arg.LanguageHint,
		arg.QueueDepthAtEnqueue,
		arg.ProcessingQueueDepthAtEnqueue,
	)
	var i WhisperTranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.RecordingID,
		&i.RoomID,
		&i.Provider,
		&i.WhisperJobID,
		&i.QueueKey,
		&i.AudioStoragePath,
		&i.Traceparent,
		&i.LanguageHint,
		&i.Status,
		&i.QueueDepthAtEnqueue,
		&i.ProcessingQueueDepthAtEnqueue,
		&i.QueueDepthAtTimeout,
		&i.ProcessingQueueDepthAtTimeout,
		&i.ResultLanguage,
		&i.DurationSeconds,
		&i.WordCount,
		&i.ErrorMessage,
		&i.ErrorClass,
		&i.ErrorStage,
		&i.DownloadHttpStatus,
		&i.DownloadSizeBytes,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markWhisperTranscriptionJobCompleted = `-- name: MarkWhisperTranscriptionJobCompleted :exec
UPDATE whisper_transcription_jobs
SET
    status = 'completed',
    result_language = $2,
    duration_seconds = $3,
    word_count = $4,
    completed_at = NOW()
WHERE whisper_job_id = $1
`

type MarkWhisperTranscriptionJobCompletedParams struct {
	WhisperJobID    uuid.UUID `db:"whisper_job_id" json:"whisper_job_id"`
	ResultLanguage  *string   `db:"result_language" json:"result_language"`
	DurationSeconds *int32    `db:"duration_seconds" json:"duration_seconds"`
	WordCount       *int32    `db:"word_count" json:"word_count"`
}

func (q *Queries) MarkWhisperTranscriptionJobCompleted(ctx context.Context, arg MarkWhisperTranscriptionJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markWhisperTranscriptionJobCompleted,
		arg.WhisperJobID,
		arg.ResultLanguage,
		arg.DurationSeconds,
		arg.WordCount,
	)
	return err
}

const markWhisperTranscriptionJobFailed = `-- name: MarkWhisperTranscriptionJobFailed :exec
UPDATE whisper_transcription_jobs
SET
    status = 'failed',
    error_message = $2,
    error_class = $3,
    error_stage = $4,
    download_http_status = $5,
    download_size_bytes = $6,
    completed_at = NOW()
WHERE whisper_job_id = $1
`

type MarkWhisperTranscriptionJobFailedParams struct {
	WhisperJobID       uuid.UUID `db:"whisper_job_id" json:"whisper_job_id"`
	ErrorMessage       *string   `db:"error_message" json:"error_message"`
	ErrorClass         *string   `db:"error_class" json:"error_class"`
	ErrorStage         *string   `db:"error_stage" json:"error_stage"`
	DownloadHttpStatus *int32    `db:"download_http_status" json:"download_http_status"`
	DownloadSizeBytes  *int64    `db:"download_size_bytes" json:"download_size_bytes"`
}

func (q *Queries) MarkWhisperTranscriptionJobFailed(ctx context.Context, arg MarkWhisperTranscriptionJobFailedParams) error {
	_, err := q.db.Exec(ctx, markWhisperTranscriptionJobFailed,
		arg.WhisperJobID,
		arg.ErrorMessage,
		arg.ErrorClass,
		arg.ErrorStage,
		arg.DownloadHttpStatus,
		arg.DownloadSizeBytes,
	)
	return err
}

const markWhisperTranscriptionJobTimedOut = `-- name: MarkWhisperTranscriptionJobTimedOut :exec
UPDATE whisper_transcription_jobs
SET
    status = 'timed_out',
    error_message = $2,
    queue_depth_at_timeout = $3,
    processing_queue_depth_at_timeout = $4,
    completed_at = NOW()
WHERE whisper_job_id = $1
`

type MarkWhisperTranscriptionJobTimedOutParams struct {
	WhisperJobID                  uuid.UUID `db:"whisper_job_id" json:"whisper_job_id"`
	ErrorMessage                  *string   `db:"error_message" json:"error_message"`
	QueueDepthAtTimeout           *int64    `db:"queue_depth_at_timeout" json:"queue_depth_at_timeout"`
	ProcessingQueueDepthAtTimeout *int64    `db:"processing_queue_depth_at_timeout" json:"processing_queue_depth_at_timeout"`
}

func (q *Queries) MarkWhisperTranscriptionJobTimedOut(ctx context.Context, arg MarkWhisperTranscriptionJobTimedOutParams) error {
	_, err := q.db.Exec(ctx, markWhisperTranscriptionJobTimedOut,
		arg.WhisperJobID,
		arg.ErrorMessage,
		arg.QueueDepthAtTimeout,
		arg.ProcessingQueueDepthAtTimeout,
	)
	return err
}
