export { SpaceClientError } from "./errors";
export { createSpaceClient } from "./space-client";
export type { AccessGrant } from "../session/access-grant";
export type {
  AccessContext,
  AccessReason,
  ActiveReaction,
  AdmissionRequest,
  Capability,
  ChatAttachment,
  ChatController,
  ChatFilesController,
  ChatMessage,
  ChatReadReceipt,
  ChatSendInput,
  ChatSlice,
  ChatUploadFile,
  ClientEventHandler,
  ClientEventMap,
  ClientEventName,
  ClientFailure,
  ConnectionSlice,
  ConnectionStatus,
  EpisodeSummary,
  ErrorCode,
  GetAccess,
  IncomingMediaRequest,
  JoinOptions,
  LocalMedia,
  Logger,
  MediaController,
  MediaDevice,
  MediaRequestKind,
  MediaSlice,
  Participant,
  ParticipantsController,
  ParticipantsSlice,
  Reaction,
  ReactionsController,
  ReactionsSlice,
  RemoteMedia,
  SelfSlice,
  SpaceClient,
  SpaceClientOptions,
  SpaceSnapshot,
  WhiteboardController,
  WhiteboardSlice,
} from "./types";
