// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authentication.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
with created_user as (
    insert into users (
        id,
        name,
        email
    ) values (
        $1,
        $2,
        $3
    )
    returning
        id,
        name,
        email,
        updated_at,
        created_at
),
created_identity as (
    insert into auth_identities (
        id,
        user_id,
        provider,
        provider_subject
    ) values (
        $4,
        $1,
        'google',
        $5
    )
)
select
    id,
    name,
    email,
    updated_at,
    created_at
from created_user
`

type CreateGoogleUserParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	IdentityID      pgtype.UUID `json:"identity_id"`
	ProviderSubject string      `json:"provider_subject"`
}

type CreateGoogleUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.IdentityID,
		arg.ProviderSubject,
	)
	var i CreateGoogleUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginSession = `-- name: CreateLoginSession :one
insert into login_sessions (
    id,
    user_id,
    token_hash,
    user_agent,
    expires_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5
)
returning
    id,
    user_id,
    token_hash,
    user_agent,
    device_name,
    ip_address,
    expires_at,
    revoked_at,
    updated_at,
    created_at
`

type CreateLoginSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) (LoginSession, error) {
	row := q.db.QueryRow(ctx, createLoginSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.DeviceName,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordUser = `-- name: CreatePasswordUser :one
with created_user as (
    insert into users (
        id,
        name,
        email
    ) values (
        $1,
        $2,
        $3
    )
    returning
        id,
        name,
        email,
        updated_at,
        created_at
),
created_identity as (
    insert into auth_identities (
        id,
        user_id,
        provider,
        provider_subject,
        password_hash
    ) values (
        $4,
        $1,
        'password',
        $3,
        $5
    )
)
select
    id,
    name,
    email,
    updated_at,
    created_at
from created_user
`

type CreatePasswordUserParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	IdentityID   pgtype.UUID `json:"identity_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreatePasswordUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (CreatePasswordUserRow, error) {
	row := q.db.QueryRow(ctx, createPasswordUser,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.IdentityID,
		arg.PasswordHash,
	)
	var i CreatePasswordUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginSessionByTokenHash = `-- name: GetLoginSessionByTokenHash :one
select
    login_sessions.id as session_id,
    login_sessions.user_id,
    login_sessions.token_hash,
    login_sessions.user_agent,
    login_sessions.device_name,
    login_sessions.ip_address,
    login_sessions.expires_at,
    login_sessions.revoked_at,
    login_sessions.updated_at as session_updated_at,
    login_sessions.created_at as session_created_at,
    users.id,
    users.name,
    users.email,
    users.updated_at,
    users.created_at
from login_sessions
join users on users.id = login_sessions.user_id
where
    login_sessions.token_hash = $1
    and login_sessions.expires_at > now()
    and login_sessions.revoked_at is null
`

type GetLoginSessionByTokenHashRow struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	TokenHash        string             `json:"token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	DeviceName       pgtype.Text        `json:"device_name"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	SessionUpdatedAt pgtype.Timestamptz `json:"session_updated_at"`
	SessionCreatedAt pgtype.Timestamptz `json:"session_created_at"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLoginSessionByTokenHash(ctx context.Context, tokenHash string) (GetLoginSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getLoginSessionByTokenHash, tokenHash)
	var i GetLoginSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.DeviceName,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.SessionUpdatedAt,
		&i.SessionCreatedAt,
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordIdentityByEmail = `-- name: GetPasswordIdentityByEmail :one
select
    users.id,
    users.name,
    users.email,
    users.updated_at,
    users.created_at,
    auth_identities.password_hash
from auth_identities
join users on users.id = auth_identities.user_id
where
    auth_identities.provider = 'password'
    and auth_identities.provider_subject = $1
    and auth_identities.password_hash is not null
`

type GetPasswordIdentityByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}

func (q *Queries) GetPasswordIdentityByEmail(ctx context.Context, email string) (GetPasswordIdentityByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordIdentityByEmail, email)
	var i GetPasswordIdentityByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByAuthIdentity = `-- name: GetUserByAuthIdentity :one
select
    users.id,
    users.name,
    users.email,
    users.updated_at,
    users.created_at
from auth_identities
join users on users.id = auth_identities.user_id
where
    auth_identities.provider = $1
    and auth_identities.provider_subject = $2
`

type GetUserByAuthIdentityParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetUserByAuthIdentity(ctx context.Context, arg GetUserByAuthIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select
    id,
    name,
    email,
    updated_at,
    created_at
from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeLoginSession = `-- name: RevokeLoginSession :one
update login_sessions
set
    revoked_at = $1,
    updated_at = now()
where
    id = $2
    and revoked_at is null
returning
    id,
    user_id,
    token_hash,
    user_agent,
    device_name,
    ip_address,
    expires_at,
    revoked_at,
    updated_at,
    created_at
`

type RevokeLoginSessionParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeLoginSession(ctx context.Context, arg RevokeLoginSessionParams) (LoginSession, error) {
	row := q.db.QueryRow(ctx, revokeLoginSession, arg.RevokedAt, arg.ID)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.DeviceName,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
