// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error)
	CreateIntegrationConnection(ctx context.Context, arg CreateIntegrationConnectionParams) (IntegrationConnection, error)
	CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) (LoginSession, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (CreatePasswordUserRow, error)
	CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomSession(ctx context.Context, arg CreateRoomSessionParams) (RoomSession, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error)
	CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (Transcription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetIntegrationConnection(ctx context.Context, arg GetIntegrationConnectionParams) (IntegrationConnection, error)
	GetIntegrationConnectionByExternalRef(ctx context.Context, arg GetIntegrationConnectionByExternalRefParams) (IntegrationConnection, error)
	GetLoginSessionByTokenHash(ctx context.Context, tokenHash string) (GetLoginSessionByTokenHashRow, error)
	GetPasswordIdentityByEmail(ctx context.Context, email string) (GetPasswordIdentityByEmailRow, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (GetTenantRow, error)
	GetTenantAuditLog(ctx context.Context, arg GetTenantAuditLogParams) (AuditLog, error)
	GetTenantMembershipForUser(ctx context.Context, arg GetTenantMembershipForUserParams) (Membership, error)
	GetTenantRecording(ctx context.Context, arg GetTenantRecordingParams) (Recording, error)
	GetTenantRoom(ctx context.Context, arg GetTenantRoomParams) (Room, error)
	GetTenantRoomSession(ctx context.Context, arg GetTenantRoomSessionParams) (RoomSession, error)
	GetTenantTranscription(ctx context.Context, arg GetTenantTranscriptionParams) (Transcription, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByAuthIdentity(ctx context.Context, arg GetUserByAuthIdentityParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListIntegrationConnections(ctx context.Context, arg ListIntegrationConnectionsParams) ([]IntegrationConnection, error)
	ListTenantAuditLogs(ctx context.Context, arg ListTenantAuditLogsParams) ([]AuditLog, error)
	ListTenantMemberships(ctx context.Context, arg ListTenantMembershipsParams) ([]Membership, error)
	ListTenantRecordings(ctx context.Context, arg ListTenantRecordingsParams) ([]Recording, error)
	ListTenantRoomSessions(ctx context.Context, arg ListTenantRoomSessionsParams) ([]RoomSession, error)
	ListTenantRooms(ctx context.Context, arg ListTenantRoomsParams) ([]Room, error)
	ListTenantTranscriptions(ctx context.Context, arg ListTenantTranscriptionsParams) ([]Transcription, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkIntegrationConnectionUsed(ctx context.Context, arg MarkIntegrationConnectionUsedParams) (IntegrationConnection, error)
	RevokeLoginSession(ctx context.Context, arg RevokeLoginSessionParams) (LoginSession, error)
	UpdateIntegrationConnection(ctx context.Context, arg UpdateIntegrationConnectionParams) (IntegrationConnection, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (UpdateTenantRow, error)
	UpdateTenantMembership(ctx context.Context, arg UpdateTenantMembershipParams) (Membership, error)
	UpdateTenantRecording(ctx context.Context, arg UpdateTenantRecordingParams) (Recording, error)
	UpdateTenantRoom(ctx context.Context, arg UpdateTenantRoomParams) (Room, error)
	UpdateTenantRoomSession(ctx context.Context, arg UpdateTenantRoomSessionParams) (RoomSession, error)
	UpdateTenantTranscription(ctx context.Context, arg UpdateTenantTranscriptionParams) (Transcription, error)
}

var _ Querier = (*Queries)(nil)
