// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recording_capture_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRecordingCapturePlan = `-- name: GetLatestRecordingCapturePlan :one
select plan_handle, revision, job_id, attempt_count, fencing_generation,
    capture_epoch, envelope_digest, tenant_id, space_id, episode_id,
    recording_id, episode_control_revision, provider_incarnation,
    provider_sequence, plan_schema_version, plan_bytes, plan_fingerprint,
    effective_deadline_at, created_at
from recording_capture_plans
where plan_handle = $1
order by revision desc
limit 1
`

func (q *Queries) GetLatestRecordingCapturePlan(ctx context.Context, planHandle pgtype.UUID) (RecordingCapturePlan, error) {
	row := q.db.QueryRow(ctx, getLatestRecordingCapturePlan, planHandle)
	var i RecordingCapturePlan
	err := row.Scan(
		&i.PlanHandle,
		&i.Revision,
		&i.JobID,
		&i.AttemptCount,
		&i.FencingGeneration,
		&i.CaptureEpoch,
		&i.EnvelopeDigest,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.EpisodeControlRevision,
		&i.ProviderIncarnation,
		&i.ProviderSequence,
		&i.PlanSchemaVersion,
		&i.PlanBytes,
		&i.PlanFingerprint,
		&i.EffectiveDeadlineAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingCapturePlanSource = `-- name: GetRecordingCapturePlanSource :one
select
    authority.envelope_bytes,
    authority.envelope_digest,
    authority.issued_at,
    jobs.id as job_id,
    jobs.tenant_id,
    reservations.space_id,
    jobs.episode_id,
    jobs.recording_id,
    authority.attempt_count,
    authority.fencing_generation,
    authority.capture_epoch,
    reservations.participant_count,
    reservations.input_bitrate_bps,
    reservations.ends_at,
    pipelines.state as pipeline_state,
    pipelines.stop_requested_at,
    control.control_revision as episode_control_revision,
    control.folded_state as episode_folded_state,
    coalesce(participant_snapshot.participants, '[]'::jsonb) as episode_participants,
    coalesce(observation.incarnation, 0)::bigint as provider_incarnation,
    coalesce(observation.sequence, 0)::bigint as provider_sequence,
    coalesce(observation.publications, '[]'::jsonb) as provider_publications
from recording_job_attempt_authorities authority
join recording_jobs jobs on jobs.id = authority.job_id
join recording_pipelines pipelines on pipelines.recording_id = jobs.recording_id
join recording_reservations reservations on reservations.id = pipelines.reservation_id
join sync_episode_control control
  on control.tenant_id = jobs.tenant_id
 and control.space_id = reservations.space_id
 and control.episode_id = jobs.episode_id
left join lateral (
    select incarnation, sequence, publications
    from provider_operation_observations
    where tenant_id = jobs.tenant_id
      and episode_id = jobs.episode_id
    order by incarnation desc, sequence desc
    limit 1
) observation on true
left join lateral (
    select jsonb_agg(
        jsonb_build_object(
            'participant_id', id,
            'generation', generation,
            'status', status
        )
        order by id
    ) as participants
    from participants
    where tenant_id = jobs.tenant_id
      and space_id = reservations.space_id
      and episode_id = jobs.episode_id
      and status in ('active', 'leaving')
) participant_snapshot on true
where authority.job_id = $1
  and authority.attempt_count = $2
  and authority.fencing_generation = $3
  and authority.capture_epoch = $4
  and authority.envelope_digest = $5
  and authority.lease_token = $6
  and authority.lease_owner = $7
  and jobs.kind = 'capture'
  and jobs.state = 'leased'
  and jobs.lease_token = $6
  and jobs.lease_owner = $7
  and jobs.lease_expires_at > clock_timestamp()
for update of jobs
`

type GetRecordingCapturePlanSourceParams struct {
	JobID             pgtype.UUID `json:"job_id"`
	AttemptCount      int32       `json:"attempt_count"`
	FencingGeneration int64       `json:"fencing_generation"`
	CaptureEpoch      int64       `json:"capture_epoch"`
	EnvelopeDigest    []byte      `json:"envelope_digest"`
	LeaseToken        string      `json:"lease_token"`
	LeaseOwner        string      `json:"lease_owner"`
}

type GetRecordingCapturePlanSourceRow struct {
	EnvelopeBytes          []byte             `json:"envelope_bytes"`
	EnvelopeDigest         []byte             `json:"envelope_digest"`
	IssuedAt               pgtype.Timestamptz `json:"issued_at"`
	JobID                  pgtype.UUID        `json:"job_id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	SpaceID                pgtype.UUID        `json:"space_id"`
	EpisodeID              pgtype.UUID        `json:"episode_id"`
	RecordingID            pgtype.UUID        `json:"recording_id"`
	AttemptCount           int32              `json:"attempt_count"`
	FencingGeneration      int64              `json:"fencing_generation"`
	CaptureEpoch           int64              `json:"capture_epoch"`
	ParticipantCount       int32              `json:"participant_count"`
	InputBitrateBps        int64              `json:"input_bitrate_bps"`
	EndsAt                 pgtype.Timestamptz `json:"ends_at"`
	PipelineState          string             `json:"pipeline_state"`
	StopRequestedAt        pgtype.Timestamptz `json:"stop_requested_at"`
	EpisodeControlRevision int64              `json:"episode_control_revision"`
	EpisodeFoldedState     []byte             `json:"episode_folded_state"`
	EpisodeParticipants    []byte             `json:"episode_participants"`
	ProviderIncarnation    int64              `json:"provider_incarnation"`
	ProviderSequence       int64              `json:"provider_sequence"`
	ProviderPublications   []byte             `json:"provider_publications"`
}

func (q *Queries) GetRecordingCapturePlanSource(ctx context.Context, arg GetRecordingCapturePlanSourceParams) (GetRecordingCapturePlanSourceRow, error) {
	row := q.db.QueryRow(ctx, getRecordingCapturePlanSource,
		arg.JobID,
		arg.AttemptCount,
		arg.FencingGeneration,
		arg.CaptureEpoch,
		arg.EnvelopeDigest,
		arg.LeaseToken,
		arg.LeaseOwner,
	)
	var i GetRecordingCapturePlanSourceRow
	err := row.Scan(
		&i.EnvelopeBytes,
		&i.EnvelopeDigest,
		&i.IssuedAt,
		&i.JobID,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.AttemptCount,
		&i.FencingGeneration,
		&i.CaptureEpoch,
		&i.ParticipantCount,
		&i.InputBitrateBps,
		&i.EndsAt,
		&i.PipelineState,
		&i.StopRequestedAt,
		&i.EpisodeControlRevision,
		&i.EpisodeFoldedState,
		&i.EpisodeParticipants,
		&i.ProviderIncarnation,
		&i.ProviderSequence,
		&i.ProviderPublications,
	)
	return i, err
}

const insertRecordingCapturePlan = `-- name: InsertRecordingCapturePlan :one
insert into recording_capture_plans (
    plan_handle, revision, job_id, attempt_count, fencing_generation,
    capture_epoch, envelope_digest, tenant_id, space_id, episode_id,
    recording_id, episode_control_revision, provider_incarnation,
    provider_sequence, plan_schema_version, plan_bytes, plan_fingerprint,
    effective_deadline_at
)
values (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15,
    $16, $17,
    $18
)
returning plan_handle, revision, job_id, attempt_count, fencing_generation,
    capture_epoch, envelope_digest, tenant_id, space_id, episode_id,
    recording_id, episode_control_revision, provider_incarnation,
    provider_sequence, plan_schema_version, plan_bytes, plan_fingerprint,
    effective_deadline_at, created_at
`

type InsertRecordingCapturePlanParams struct {
	PlanHandle             pgtype.UUID        `json:"plan_handle"`
	Revision               int64              `json:"revision"`
	JobID                  pgtype.UUID        `json:"job_id"`
	AttemptCount           int32              `json:"attempt_count"`
	FencingGeneration      int64              `json:"fencing_generation"`
	CaptureEpoch           int64              `json:"capture_epoch"`
	EnvelopeDigest         []byte             `json:"envelope_digest"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	SpaceID                pgtype.UUID        `json:"space_id"`
	EpisodeID              pgtype.UUID        `json:"episode_id"`
	RecordingID            pgtype.UUID        `json:"recording_id"`
	EpisodeControlRevision int64              `json:"episode_control_revision"`
	ProviderIncarnation    int64              `json:"provider_incarnation"`
	ProviderSequence       int64              `json:"provider_sequence"`
	PlanSchemaVersion      string             `json:"plan_schema_version"`
	PlanBytes              []byte             `json:"plan_bytes"`
	PlanFingerprint        []byte             `json:"plan_fingerprint"`
	EffectiveDeadlineAt    pgtype.Timestamptz `json:"effective_deadline_at"`
}

func (q *Queries) InsertRecordingCapturePlan(ctx context.Context, arg InsertRecordingCapturePlanParams) (RecordingCapturePlan, error) {
	row := q.db.QueryRow(ctx, insertRecordingCapturePlan,
		arg.PlanHandle,
		arg.Revision,
		arg.JobID,
		arg.AttemptCount,
		arg.FencingGeneration,
		arg.CaptureEpoch,
		arg.EnvelopeDigest,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
		arg.EpisodeControlRevision,
		arg.ProviderIncarnation,
		arg.ProviderSequence,
		arg.PlanSchemaVersion,
		arg.PlanBytes,
		arg.PlanFingerprint,
		arg.EffectiveDeadlineAt,
	)
	var i RecordingCapturePlan
	err := row.Scan(
		&i.PlanHandle,
		&i.Revision,
		&i.JobID,
		&i.AttemptCount,
		&i.FencingGeneration,
		&i.CaptureEpoch,
		&i.EnvelopeDigest,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.EpisodeControlRevision,
		&i.ProviderIncarnation,
		&i.ProviderSequence,
		&i.PlanSchemaVersion,
		&i.PlanBytes,
		&i.PlanFingerprint,
		&i.EffectiveDeadlineAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockRecordingCapturePlanHandle = `-- name: LockRecordingCapturePlanHandle :exec
select pg_advisory_xact_lock(hashtextextended($1::text, 2))
`

func (q *Queries) LockRecordingCapturePlanHandle(ctx context.Context, planHandle string) error {
	_, err := q.db.Exec(ctx, lockRecordingCapturePlanHandle, planHandle)
	return err
}
