// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recording_capture_lifecycle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecordingCaptureLifecycleOperation = `-- name: InsertRecordingCaptureLifecycleOperation :one
insert into sync_external_operations (
    tenant_id,
    space_id,
    episode_id,
    external_operation_id,
    request_key,
    request_fingerprint,
    operation_name,
    recording_id,
    journey_id,
    parent_journey_event_id,
    producing_trace_id,
    producing_span_id,
    producing_traceparent,
    producing_tracestate,
    payload,
    fence_active
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    false
)
on conflict (tenant_id, episode_id, operation_name, request_key) do nothing
returning tenant_id, space_id, episode_id, external_operation_id, parent_external_operation_id, request_key, request_fingerprint, operation_name, actor_participant_id, actor_generation, target_participant_id, target_participant_generation, source, recording_id, deadline_generation, journey_id, parent_journey_event_id, producing_trace_id, producing_span_id, payload, status, fence_active, attempt_count, next_attempt_at, last_error_code, applied_event_id, applied_revision, created_at, completed_at, producing_traceparent, producing_tracestate
`

type InsertRecordingCaptureLifecycleOperationParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	SpaceID              pgtype.UUID `json:"space_id"`
	EpisodeID            pgtype.UUID `json:"episode_id"`
	ExternalOperationID  pgtype.UUID `json:"external_operation_id"`
	RequestKey           string      `json:"request_key"`
	RequestFingerprint   []byte      `json:"request_fingerprint"`
	OperationName        string      `json:"operation_name"`
	RecordingID          pgtype.UUID `json:"recording_id"`
	JourneyID            pgtype.UUID `json:"journey_id"`
	ParentJourneyEventID pgtype.UUID `json:"parent_journey_event_id"`
	ProducingTraceID     pgtype.Text `json:"producing_trace_id"`
	ProducingSpanID      pgtype.Text `json:"producing_span_id"`
	ProducingTraceparent pgtype.Text `json:"producing_traceparent"`
	ProducingTracestate  pgtype.Text `json:"producing_tracestate"`
	Payload              []byte      `json:"payload"`
}

func (q *Queries) InsertRecordingCaptureLifecycleOperation(ctx context.Context, arg InsertRecordingCaptureLifecycleOperationParams) (SyncExternalOperation, error) {
	row := q.db.QueryRow(ctx, insertRecordingCaptureLifecycleOperation,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.ExternalOperationID,
		arg.RequestKey,
		arg.RequestFingerprint,
		arg.OperationName,
		arg.RecordingID,
		arg.JourneyID,
		arg.ParentJourneyEventID,
		arg.ProducingTraceID,
		arg.ProducingSpanID,
		arg.ProducingTraceparent,
		arg.ProducingTracestate,
		arg.Payload,
	)
	var i SyncExternalOperation
	err := row.Scan(
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.ExternalOperationID,
		&i.ParentExternalOperationID,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.OperationName,
		&i.ActorParticipantID,
		&i.ActorGeneration,
		&i.TargetParticipantID,
		&i.TargetParticipantGeneration,
		&i.Source,
		&i.RecordingID,
		&i.DeadlineGeneration,
		&i.JourneyID,
		&i.ParentJourneyEventID,
		&i.ProducingTraceID,
		&i.ProducingSpanID,
		&i.Payload,
		&i.Status,
		&i.FenceActive,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.AppliedEventID,
		&i.AppliedRevision,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ProducingTraceparent,
		&i.ProducingTracestate,
	)
	return i, err
}

const lockRecordingCaptureLifecycleAuthority = `-- name: LockRecordingCaptureLifecycleAuthority :one
select
    authority.envelope_digest,
    authority.job_id,
    authority.attempt_count,
    authority.fencing_generation,
    authority.capture_epoch,
    jobs.tenant_id,
    reservations.space_id,
    jobs.episode_id,
    jobs.recording_id,
    jobs.lease_owner,
    jobs.lease_token,
    jobs.lease_expires_at,
    sync_recordings.status as recording_status,
    sync_recordings.start_external_operation_id,
    sync_recordings.stop_external_operation_id
from recording_job_attempt_authorities authority
join recording_jobs jobs on jobs.id = authority.job_id
join recording_pipelines pipelines on pipelines.recording_id = jobs.recording_id
join recording_reservations reservations on reservations.id = pipelines.reservation_id
join sync_recordings
  on sync_recordings.tenant_id = jobs.tenant_id
 and sync_recordings.space_id = reservations.space_id
 and sync_recordings.episode_id = jobs.episode_id
 and sync_recordings.recording_id = jobs.recording_id
where authority.job_id = $1
  and authority.attempt_count = $2
  and authority.fencing_generation = $3
  and authority.capture_epoch = $4
  and authority.envelope_digest = $5
  and authority.lease_token = $6
  and authority.lease_owner = $7
  and jobs.kind = 'capture'
  and jobs.state = 'leased'
  and jobs.tenant_id = $8
  and jobs.episode_id = $9
  and jobs.recording_id = $10
  and reservations.space_id = $11
  and jobs.attempt_count = $2
  and jobs.fencing_generation = $3
  and jobs.lease_token = $6
  and jobs.lease_owner = $7
  and jobs.lease_expires_at = $12
  and jobs.lease_expires_at > clock_timestamp()
  and authority.lease_expires_at = $12
for update of jobs, sync_recordings
`

type LockRecordingCaptureLifecycleAuthorityParams struct {
	JobID             pgtype.UUID        `json:"job_id"`
	AttemptCount      int32              `json:"attempt_count"`
	FencingGeneration int64              `json:"fencing_generation"`
	CaptureEpoch      int64              `json:"capture_epoch"`
	EnvelopeDigest    []byte             `json:"envelope_digest"`
	LeaseToken        string             `json:"lease_token"`
	LeaseOwner        string             `json:"lease_owner"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	EpisodeID         pgtype.UUID        `json:"episode_id"`
	RecordingID       pgtype.UUID        `json:"recording_id"`
	SpaceID           pgtype.UUID        `json:"space_id"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
}

type LockRecordingCaptureLifecycleAuthorityRow struct {
	EnvelopeDigest           []byte             `json:"envelope_digest"`
	JobID                    pgtype.UUID        `json:"job_id"`
	AttemptCount             int32              `json:"attempt_count"`
	FencingGeneration        int64              `json:"fencing_generation"`
	CaptureEpoch             int64              `json:"capture_epoch"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	EpisodeID                pgtype.UUID        `json:"episode_id"`
	RecordingID              pgtype.UUID        `json:"recording_id"`
	LeaseOwner               pgtype.Text        `json:"lease_owner"`
	LeaseToken               pgtype.Text        `json:"lease_token"`
	LeaseExpiresAt           pgtype.Timestamptz `json:"lease_expires_at"`
	RecordingStatus          string             `json:"recording_status"`
	StartExternalOperationID pgtype.UUID        `json:"start_external_operation_id"`
	StopExternalOperationID  pgtype.UUID        `json:"stop_external_operation_id"`
}

func (q *Queries) LockRecordingCaptureLifecycleAuthority(ctx context.Context, arg LockRecordingCaptureLifecycleAuthorityParams) (LockRecordingCaptureLifecycleAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockRecordingCaptureLifecycleAuthority,
		arg.JobID,
		arg.AttemptCount,
		arg.FencingGeneration,
		arg.CaptureEpoch,
		arg.EnvelopeDigest,
		arg.LeaseToken,
		arg.LeaseOwner,
		arg.TenantID,
		arg.EpisodeID,
		arg.RecordingID,
		arg.SpaceID,
		arg.LeaseExpiresAt,
	)
	var i LockRecordingCaptureLifecycleAuthorityRow
	err := row.Scan(
		&i.EnvelopeDigest,
		&i.JobID,
		&i.AttemptCount,
		&i.FencingGeneration,
		&i.CaptureEpoch,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RecordingStatus,
		&i.StartExternalOperationID,
		&i.StopExternalOperationID,
	)
	return i, err
}

const lockRecordingCaptureLifecycleOperation = `-- name: LockRecordingCaptureLifecycleOperation :one
select tenant_id, space_id, episode_id, external_operation_id, parent_external_operation_id, request_key, request_fingerprint, operation_name, actor_participant_id, actor_generation, target_participant_id, target_participant_generation, source, recording_id, deadline_generation, journey_id, parent_journey_event_id, producing_trace_id, producing_span_id, payload, status, fence_active, attempt_count, next_attempt_at, last_error_code, applied_event_id, applied_revision, created_at, completed_at, producing_traceparent, producing_tracestate
from sync_external_operations
where tenant_id = $1
  and space_id = $2
  and episode_id = $3
  and operation_name = $4
  and request_key = $5
for update
`

type LockRecordingCaptureLifecycleOperationParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SpaceID       pgtype.UUID `json:"space_id"`
	EpisodeID     pgtype.UUID `json:"episode_id"`
	OperationName string      `json:"operation_name"`
	RequestKey    string      `json:"request_key"`
}

func (q *Queries) LockRecordingCaptureLifecycleOperation(ctx context.Context, arg LockRecordingCaptureLifecycleOperationParams) (SyncExternalOperation, error) {
	row := q.db.QueryRow(ctx, lockRecordingCaptureLifecycleOperation,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.OperationName,
		arg.RequestKey,
	)
	var i SyncExternalOperation
	err := row.Scan(
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.ExternalOperationID,
		&i.ParentExternalOperationID,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.OperationName,
		&i.ActorParticipantID,
		&i.ActorGeneration,
		&i.TargetParticipantID,
		&i.TargetParticipantGeneration,
		&i.Source,
		&i.RecordingID,
		&i.DeadlineGeneration,
		&i.JourneyID,
		&i.ParentJourneyEventID,
		&i.ProducingTraceID,
		&i.ProducingSpanID,
		&i.Payload,
		&i.Status,
		&i.FenceActive,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.AppliedEventID,
		&i.AppliedRevision,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ProducingTraceparent,
		&i.ProducingTracestate,
	)
	return i, err
}
