// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recording_presentation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecordingPresentationBaseline = `-- name: GetRecordingPresentationBaseline :one
select presentation_handle, tenant_id, space_id, episode_id, recording_id, schema_version, profile_version, profile, space_name, episode_control_revision, episode_folded_state, participant_facts, chat_head_sequence, chat_retained_floor_sequence, whiteboard_scene_id, whiteboard_revision, whiteboard_snapshot, baseline_at, created_at from recording_presentation_baselines
where tenant_id = $1
  and space_id = $2
  and episode_id = $3
  and recording_id = $4
`

type GetRecordingPresentationBaselineParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	SpaceID     pgtype.UUID `json:"space_id"`
	EpisodeID   pgtype.UUID `json:"episode_id"`
	RecordingID pgtype.UUID `json:"recording_id"`
}

func (q *Queries) GetRecordingPresentationBaseline(ctx context.Context, arg GetRecordingPresentationBaselineParams) (RecordingPresentationBaseline, error) {
	row := q.db.QueryRow(ctx, getRecordingPresentationBaseline,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
	)
	var i RecordingPresentationBaseline
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.Profile,
		&i.SpaceName,
		&i.EpisodeControlRevision,
		&i.EpisodeFoldedState,
		&i.ParticipantFacts,
		&i.ChatHeadSequence,
		&i.ChatRetainedFloorSequence,
		&i.WhiteboardSceneID,
		&i.WhiteboardRevision,
		&i.WhiteboardSnapshot,
		&i.BaselineAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingPresentationCompletionSource = `-- name: GetRecordingPresentationCompletionSource :one
with authority as (
    select jobs.tenant_id, reservations.space_id, jobs.episode_id,
        jobs.recording_id, pipelines.capture_epoch
    from recording_job_attempt_authorities attempts
    join recording_jobs jobs on jobs.id = attempts.job_id
    join recording_pipelines pipelines on pipelines.recording_id = jobs.recording_id
    join recording_reservations reservations on reservations.id = pipelines.reservation_id
    where attempts.job_id = $1
      and attempts.attempt_count = $2
      and attempts.fencing_generation = $3
      and attempts.capture_epoch = $4
      and attempts.envelope_digest = $5
      and attempts.lease_token = $6
      and attempts.lease_owner = $7
      and jobs.kind = 'capture'
      and jobs.state = 'leased'
      and jobs.attempt_count = attempts.attempt_count
      and jobs.fencing_generation = attempts.fencing_generation
      and jobs.lease_token = $6
      and jobs.lease_owner = $7
      and jobs.lease_expires_at > clock_timestamp()
      and pipelines.capture_epoch = attempts.capture_epoch
), source as (
    select sources.presentation_handle, sources.tenant_id, sources.space_id,
        sources.episode_id, sources.recording_id,
        authority.capture_epoch as capture_epoch, sources.capture_ready_at,
        sources.episode_control_start_revision, sources.episode_control_events,
        sources.episode_control_end_revision, sources.participant_facts,
        sources.chat_start_sequence, sources.chat_retained_floor_sequence,
        sources.initial_chat_messages, sources.whiteboard_start_revision,
        sources.whiteboard_events, sources.whiteboard_end_revision,
        sources.capture_plan_start_revision, sources.created_at,
        baselines.schema_version, baselines.profile_version,
        baselines.profile, baselines.space_name, baselines.episode_folded_state,
        baselines.whiteboard_snapshot, baselines.baseline_at
    from authority
    join recording_presentation_sources sources
      on sources.tenant_id = authority.tenant_id
     and sources.space_id = authority.space_id
     and sources.episode_id = authority.episode_id
     and sources.recording_id = authority.recording_id
     and sources.capture_epoch <= authority.capture_epoch
    join recording_presentation_baselines baselines using (presentation_handle)
), duration as (
    select coalesce(max(bundles.media_end_millis), 0)::bigint as duration_millis
    from authority
    left join recording_bundles bundles
      on bundles.tenant_id = authority.tenant_id
     and bundles.recording_id = authority.recording_id
     and bundles.capture_job_id = $1
), boundary as (
    select source.presentation_handle, source.tenant_id, source.space_id, source.episode_id, source.recording_id, source.capture_epoch, source.capture_ready_at, source.episode_control_start_revision, source.episode_control_events, source.episode_control_end_revision, source.participant_facts, source.chat_start_sequence, source.chat_retained_floor_sequence, source.initial_chat_messages, source.whiteboard_start_revision, source.whiteboard_events, source.whiteboard_end_revision, source.capture_plan_start_revision, source.created_at, source.schema_version, source.profile_version, source.profile, source.space_name, source.episode_folded_state, source.whiteboard_snapshot, source.baseline_at, duration.duration_millis,
        cast(source.capture_ready_at + duration.duration_millis * interval '1 millisecond' as timestamptz) as ended_at
    from source cross join duration
)
select boundary.presentation_handle, boundary.tenant_id, boundary.space_id, boundary.episode_id, boundary.recording_id, boundary.capture_epoch, boundary.capture_ready_at, boundary.episode_control_start_revision, boundary.episode_control_events, boundary.episode_control_end_revision, boundary.participant_facts, boundary.chat_start_sequence, boundary.chat_retained_floor_sequence, boundary.initial_chat_messages, boundary.whiteboard_start_revision, boundary.whiteboard_events, boundary.whiteboard_end_revision, boundary.capture_plan_start_revision, boundary.created_at, boundary.schema_version, boundary.profile_version, boundary.profile, boundary.space_name, boundary.episode_folded_state, boundary.whiteboard_snapshot, boundary.baseline_at, boundary.duration_millis, boundary.ended_at,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'revision', plans.revision,
            'capture_epoch', plans.capture_epoch,
            'source_revision', plans.source_revision,
            'plan_bytes', encode(plans.plan_bytes, 'base64'),
            'plan_fingerprint', encode(plans.plan_fingerprint, 'hex'),
            'created_at', plans.created_at
        ) order by plans.revision)
        from (
            select row_number() over (
                    order by plans.capture_epoch, plans.revision, plans.plan_handle
                )::bigint as revision,
                plans.capture_epoch, plans.revision as source_revision,
                plans.plan_bytes, plans.plan_fingerprint, plans.created_at
            from recording_capture_plans plans
            where plans.tenant_id = boundary.tenant_id
              and plans.space_id = boundary.space_id
              and plans.episode_id = boundary.episode_id
              and plans.recording_id = boundary.recording_id
              and plans.capture_epoch >= (
                  select origins.capture_epoch
                  from recording_presentation_sources origins
                  where origins.presentation_handle = boundary.presentation_handle
              )
              and plans.capture_epoch <= boundary.capture_epoch
              and plans.created_at <= boundary.ended_at
            order by plans.capture_epoch, plans.revision, plans.plan_handle
            limit 100001
        ) plans
    ), '[]'::jsonb)::text as capture_plans_json,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'revision', events.revision,
            'event_name', events.event_name,
            'payload', events.payload,
            'created_at', events.created_at
        ) order by events.revision)
        from (
            select events.revision, events.event_name, events.payload, events.created_at
            from sync_control_events events
            where events.tenant_id = boundary.tenant_id
              and events.space_id = boundary.space_id
              and events.episode_id = boundary.episode_id
              and events.revision > boundary.episode_control_end_revision
              and events.created_at <= boundary.ended_at
            order by events.revision
            limit 100001
        ) events
    ), '[]'::jsonb)::text as episode_control_tail_events_json,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'message_id', messages.message_id,
            'sequence', messages.sequence,
            'participant_id', messages.participant_id,
            'participant_generation', messages.participant_generation,
            'display_name', messages.display_name,
            'message_text', messages.message_text,
            'created_at', messages.created_at,
            'attachments', coalesce((
                select jsonb_agg(jsonb_build_object(
                    'attachment_id', attachments.attachment_id,
                    'object_key', attachments.object_key,
                    'object_etag', attachments.immutable_object_identity,
                    'original_filename', attachments.original_filename,
                    'mime_type', attachments.mime_type,
                    'byte_length', attachments.byte_length,
                    'sha256', encode(attachments.sha256, 'hex')
                ) order by attachments.message_ordinal)
                from sync_chat_attachments attachments
                where attachments.tenant_id = messages.tenant_id
                  and attachments.space_id = messages.space_id
                  and attachments.message_sequence = messages.sequence
                  and attachments.status = 'attached'
            ), '[]'::jsonb)
        ) order by messages.sequence)
        from (
            select messages.tenant_id, messages.space_id, messages.episode_id, messages.sequence, messages.message_id, messages.participant_id, messages.participant_generation, messages.client_message_id, messages.request_fingerprint, messages.display_name, messages.message_text, messages.encoded_bytes, messages.created_at
            from sync_chat_messages messages
            where messages.tenant_id = boundary.tenant_id
              and messages.space_id = boundary.space_id
              and messages.episode_id = boundary.episode_id
              and messages.sequence > boundary.chat_start_sequence
              and messages.created_at <= boundary.ended_at
            order by messages.sequence
            limit 100001
        ) messages
    ), '[]'::jsonb)::text as chat_tail_messages_json,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'operation_name', receipts.operation_name,
            'operation_id', receipts.operation_id,
            'scene_id', receipts.scene_id,
            'revision', receipts.revision,
            'elements', receipts.event_elements,
            'presenting', receipts.event_presenting,
            'completed_at', receipts.completed_at
        ) order by receipts.completed_at, receipts.operation_id)
        from (
            select receipts.tenant_id, receipts.space_id, receipts.episode_id, receipts.participant_id, receipts.submitted_generation, receipts.operation_id, receipts.request_fingerprint, receipts.operation_name, receipts.outcome, receipts.scene_id, receipts.revision, receipts.event_elements, receipts.event_presenting, receipts.event_encoded_bytes, receipts.completed_at
            from sync_whiteboard_operation_receipts receipts
            where receipts.tenant_id = boundary.tenant_id
              and receipts.space_id = boundary.space_id
              and receipts.episode_id = boundary.episode_id
              and receipts.completed_at > boundary.capture_ready_at
              and receipts.completed_at <= boundary.ended_at
            order by receipts.completed_at, receipts.operation_id
            limit 100001
        ) receipts
    ), '[]'::jsonb)::text as whiteboard_tail_events_json,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'file_id', files.file_id,
            'object_key', files.object_key,
            'object_etag', files.immutable_object_identity,
            'mime_type', files.mime_type,
            'byte_length', files.byte_length,
            'sha256', encode(files.sha256, 'hex')
        ) order by files.scene_id, files.file_id)
        from (
            select files.upload_id, files.tenant_id, files.space_id, files.episode_id, files.scene_id, files.participant_id, files.participant_generation, files.file_id, files.object_key, files.mime_type, files.byte_length, files.sha256, files.status, files.immutable_object_identity, files.expires_at, files.finalized_at, files.cleanup_claim_token, files.cleanup_claimed_until, files.cleanup_attempts, files.created_at, files.updated_at
            from sync_whiteboard_files files
            where files.tenant_id = boundary.tenant_id
              and files.space_id = boundary.space_id
              and files.episode_id = boundary.episode_id
              and files.status = 'ready'
              and files.finalized_at <= boundary.ended_at
            order by files.scene_id, files.file_id
            limit 257
        ) files
    ), '[]'::jsonb)::text as whiteboard_files_json,
    coalesce((
        select jsonb_agg(jsonb_build_object(
            'reaction_id', reactions.reaction_id,
            'participant_id', reactions.participant_id,
            'participant_generation', reactions.participant_generation,
            'display_name', reactions.display_name,
            'reaction', reactions.reaction,
            'occurred_at', reactions.occurred_at,
            'expires_at', reactions.expires_at
        ) order by reactions.occurred_at, reactions.reaction_id)
        from (
            select reactions.reaction_id, reactions.presentation_handle, reactions.tenant_id, reactions.space_id, reactions.episode_id, reactions.recording_id, reactions.participant_id, reactions.participant_generation, reactions.display_name, reactions.reaction, reactions.occurred_at, reactions.expires_at, reactions.created_at
            from recording_presentation_reactions reactions
            where reactions.tenant_id = boundary.tenant_id
              and reactions.recording_id = boundary.recording_id
              and reactions.presentation_handle = boundary.presentation_handle
              and reactions.occurred_at <= boundary.ended_at
            order by reactions.occurred_at, reactions.reaction_id
            limit 100001
        ) reactions
    ), '[]'::jsonb)::text as reactions_json
from boundary
`

type GetRecordingPresentationCompletionSourceParams struct {
	JobID             pgtype.UUID `json:"job_id"`
	AttemptCount      int32       `json:"attempt_count"`
	FencingGeneration int64       `json:"fencing_generation"`
	CaptureEpoch      int64       `json:"capture_epoch"`
	EnvelopeDigest    []byte      `json:"envelope_digest"`
	LeaseToken        string      `json:"lease_token"`
	LeaseOwner        string      `json:"lease_owner"`
}

type GetRecordingPresentationCompletionSourceRow struct {
	PresentationHandle           pgtype.UUID        `json:"presentation_handle"`
	TenantID                     pgtype.UUID        `json:"tenant_id"`
	SpaceID                      pgtype.UUID        `json:"space_id"`
	EpisodeID                    pgtype.UUID        `json:"episode_id"`
	RecordingID                  pgtype.UUID        `json:"recording_id"`
	CaptureEpoch                 int64              `json:"capture_epoch"`
	CaptureReadyAt               pgtype.Timestamptz `json:"capture_ready_at"`
	EpisodeControlStartRevision  int64              `json:"episode_control_start_revision"`
	EpisodeControlEvents         []byte             `json:"episode_control_events"`
	EpisodeControlEndRevision    int64              `json:"episode_control_end_revision"`
	ParticipantFacts             []byte             `json:"participant_facts"`
	ChatStartSequence            int64              `json:"chat_start_sequence"`
	ChatRetainedFloorSequence    pgtype.Int8        `json:"chat_retained_floor_sequence"`
	InitialChatMessages          []byte             `json:"initial_chat_messages"`
	WhiteboardStartRevision      int64              `json:"whiteboard_start_revision"`
	WhiteboardEvents             []byte             `json:"whiteboard_events"`
	WhiteboardEndRevision        int64              `json:"whiteboard_end_revision"`
	CapturePlanStartRevision     int64              `json:"capture_plan_start_revision"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	SchemaVersion                string             `json:"schema_version"`
	ProfileVersion               string             `json:"profile_version"`
	Profile                      []byte             `json:"profile"`
	SpaceName                    string             `json:"space_name"`
	EpisodeFoldedState           []byte             `json:"episode_folded_state"`
	WhiteboardSnapshot           []byte             `json:"whiteboard_snapshot"`
	BaselineAt                   pgtype.Timestamptz `json:"baseline_at"`
	DurationMillis               int64              `json:"duration_millis"`
	EndedAt                      pgtype.Timestamptz `json:"ended_at"`
	CapturePlansJson             string             `json:"capture_plans_json"`
	EpisodeControlTailEventsJson string             `json:"episode_control_tail_events_json"`
	ChatTailMessagesJson         string             `json:"chat_tail_messages_json"`
	WhiteboardTailEventsJson     string             `json:"whiteboard_tail_events_json"`
	WhiteboardFilesJson          string             `json:"whiteboard_files_json"`
	ReactionsJson                string             `json:"reactions_json"`
}

func (q *Queries) GetRecordingPresentationCompletionSource(ctx context.Context, arg GetRecordingPresentationCompletionSourceParams) (GetRecordingPresentationCompletionSourceRow, error) {
	row := q.db.QueryRow(ctx, getRecordingPresentationCompletionSource,
		arg.JobID,
		arg.AttemptCount,
		arg.FencingGeneration,
		arg.CaptureEpoch,
		arg.EnvelopeDigest,
		arg.LeaseToken,
		arg.LeaseOwner,
	)
	var i GetRecordingPresentationCompletionSourceRow
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.CaptureEpoch,
		&i.CaptureReadyAt,
		&i.EpisodeControlStartRevision,
		&i.EpisodeControlEvents,
		&i.EpisodeControlEndRevision,
		&i.ParticipantFacts,
		&i.ChatStartSequence,
		&i.ChatRetainedFloorSequence,
		&i.InitialChatMessages,
		&i.WhiteboardStartRevision,
		&i.WhiteboardEvents,
		&i.WhiteboardEndRevision,
		&i.CapturePlanStartRevision,
		&i.CreatedAt,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.Profile,
		&i.SpaceName,
		&i.EpisodeFoldedState,
		&i.WhiteboardSnapshot,
		&i.BaselineAt,
		&i.DurationMillis,
		&i.EndedAt,
		&i.CapturePlansJson,
		&i.EpisodeControlTailEventsJson,
		&i.ChatTailMessagesJson,
		&i.WhiteboardTailEventsJson,
		&i.WhiteboardFilesJson,
		&i.ReactionsJson,
	)
	return i, err
}

const getRecordingPresentationForRender = `-- name: GetRecordingPresentationForRender :one
select presentations.presentation_handle, presentations.schema_version,
    presentations.profile_version, presentations.duration_millis,
    presentations.presentation_sha256, sources.capture_ready_at,
    presentations.presentation_object_key, presentations.presentation_object_version,
    presentations.presentation_object_etag, presentations.presentation_content_type,
    presentations.presentation_byte_size,
    presentations.asset_manifest_object_key, presentations.asset_manifest_object_version,
    presentations.asset_manifest_object_etag, presentations.asset_manifest_content_type,
    presentations.asset_manifest_byte_size, presentations.asset_manifest_sha256
from recording_presentations presentations
join recording_presentation_sources sources using (presentation_handle)
where presentations.tenant_id = $1
  and presentations.space_id = $2
  and presentations.episode_id = $3
  and presentations.recording_id = $4
  and presentations.presentation_handle = $5
  and presentations.capture_epoch = $6
`

type GetRecordingPresentationForRenderParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	SpaceID            pgtype.UUID `json:"space_id"`
	EpisodeID          pgtype.UUID `json:"episode_id"`
	RecordingID        pgtype.UUID `json:"recording_id"`
	PresentationHandle pgtype.UUID `json:"presentation_handle"`
	CaptureEpoch       int64       `json:"capture_epoch"`
}

type GetRecordingPresentationForRenderRow struct {
	PresentationHandle         pgtype.UUID        `json:"presentation_handle"`
	SchemaVersion              string             `json:"schema_version"`
	ProfileVersion             string             `json:"profile_version"`
	DurationMillis             int64              `json:"duration_millis"`
	PresentationSha256         []byte             `json:"presentation_sha256"`
	CaptureReadyAt             pgtype.Timestamptz `json:"capture_ready_at"`
	PresentationObjectKey      string             `json:"presentation_object_key"`
	PresentationObjectVersion  string             `json:"presentation_object_version"`
	PresentationObjectEtag     string             `json:"presentation_object_etag"`
	PresentationContentType    string             `json:"presentation_content_type"`
	PresentationByteSize       int64              `json:"presentation_byte_size"`
	AssetManifestObjectKey     string             `json:"asset_manifest_object_key"`
	AssetManifestObjectVersion string             `json:"asset_manifest_object_version"`
	AssetManifestObjectEtag    string             `json:"asset_manifest_object_etag"`
	AssetManifestContentType   string             `json:"asset_manifest_content_type"`
	AssetManifestByteSize      int64              `json:"asset_manifest_byte_size"`
	AssetManifestSha256        []byte             `json:"asset_manifest_sha256"`
}

func (q *Queries) GetRecordingPresentationForRender(ctx context.Context, arg GetRecordingPresentationForRenderParams) (GetRecordingPresentationForRenderRow, error) {
	row := q.db.QueryRow(ctx, getRecordingPresentationForRender,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
		arg.PresentationHandle,
		arg.CaptureEpoch,
	)
	var i GetRecordingPresentationForRenderRow
	err := row.Scan(
		&i.PresentationHandle,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.DurationMillis,
		&i.PresentationSha256,
		&i.CaptureReadyAt,
		&i.PresentationObjectKey,
		&i.PresentationObjectVersion,
		&i.PresentationObjectEtag,
		&i.PresentationContentType,
		&i.PresentationByteSize,
		&i.AssetManifestObjectKey,
		&i.AssetManifestObjectVersion,
		&i.AssetManifestObjectEtag,
		&i.AssetManifestContentType,
		&i.AssetManifestByteSize,
		&i.AssetManifestSha256,
	)
	return i, err
}

const getRecordingPresentationSource = `-- name: GetRecordingPresentationSource :one
select sources.presentation_handle, sources.tenant_id, sources.space_id, sources.episode_id, sources.recording_id, sources.capture_epoch, sources.capture_ready_at, sources.episode_control_start_revision, sources.episode_control_events, sources.episode_control_end_revision, sources.participant_facts, sources.chat_start_sequence, sources.chat_retained_floor_sequence, sources.initial_chat_messages, sources.whiteboard_start_revision, sources.whiteboard_events, sources.whiteboard_end_revision, sources.capture_plan_start_revision, sources.created_at, baselines.schema_version, baselines.profile_version,
    baselines.profile, baselines.space_name, baselines.episode_folded_state,
    baselines.participant_facts as baseline_participant_facts,
    baselines.whiteboard_snapshot, baselines.baseline_at
from recording_presentation_sources sources
join recording_presentation_baselines baselines using (presentation_handle)
where sources.tenant_id = $1
  and sources.space_id = $2
  and sources.episode_id = $3
  and sources.recording_id = $4
  and sources.capture_epoch = $5
`

type GetRecordingPresentationSourceParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SpaceID      pgtype.UUID `json:"space_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	RecordingID  pgtype.UUID `json:"recording_id"`
	CaptureEpoch int64       `json:"capture_epoch"`
}

type GetRecordingPresentationSourceRow struct {
	PresentationHandle          pgtype.UUID        `json:"presentation_handle"`
	TenantID                    pgtype.UUID        `json:"tenant_id"`
	SpaceID                     pgtype.UUID        `json:"space_id"`
	EpisodeID                   pgtype.UUID        `json:"episode_id"`
	RecordingID                 pgtype.UUID        `json:"recording_id"`
	CaptureEpoch                int64              `json:"capture_epoch"`
	CaptureReadyAt              pgtype.Timestamptz `json:"capture_ready_at"`
	EpisodeControlStartRevision int64              `json:"episode_control_start_revision"`
	EpisodeControlEvents        []byte             `json:"episode_control_events"`
	EpisodeControlEndRevision   int64              `json:"episode_control_end_revision"`
	ParticipantFacts            []byte             `json:"participant_facts"`
	ChatStartSequence           int64              `json:"chat_start_sequence"`
	ChatRetainedFloorSequence   pgtype.Int8        `json:"chat_retained_floor_sequence"`
	InitialChatMessages         []byte             `json:"initial_chat_messages"`
	WhiteboardStartRevision     int64              `json:"whiteboard_start_revision"`
	WhiteboardEvents            []byte             `json:"whiteboard_events"`
	WhiteboardEndRevision       int64              `json:"whiteboard_end_revision"`
	CapturePlanStartRevision    int64              `json:"capture_plan_start_revision"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	SchemaVersion               string             `json:"schema_version"`
	ProfileVersion              string             `json:"profile_version"`
	Profile                     []byte             `json:"profile"`
	SpaceName                   string             `json:"space_name"`
	EpisodeFoldedState          []byte             `json:"episode_folded_state"`
	BaselineParticipantFacts    []byte             `json:"baseline_participant_facts"`
	WhiteboardSnapshot          []byte             `json:"whiteboard_snapshot"`
	BaselineAt                  pgtype.Timestamptz `json:"baseline_at"`
}

func (q *Queries) GetRecordingPresentationSource(ctx context.Context, arg GetRecordingPresentationSourceParams) (GetRecordingPresentationSourceRow, error) {
	row := q.db.QueryRow(ctx, getRecordingPresentationSource,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
		arg.CaptureEpoch,
	)
	var i GetRecordingPresentationSourceRow
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.CaptureEpoch,
		&i.CaptureReadyAt,
		&i.EpisodeControlStartRevision,
		&i.EpisodeControlEvents,
		&i.EpisodeControlEndRevision,
		&i.ParticipantFacts,
		&i.ChatStartSequence,
		&i.ChatRetainedFloorSequence,
		&i.InitialChatMessages,
		&i.WhiteboardStartRevision,
		&i.WhiteboardEvents,
		&i.WhiteboardEndRevision,
		&i.CapturePlanStartRevision,
		&i.CreatedAt,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.Profile,
		&i.SpaceName,
		&i.EpisodeFoldedState,
		&i.BaselineParticipantFacts,
		&i.WhiteboardSnapshot,
		&i.BaselineAt,
	)
	return i, err
}

const insertActiveRecordingPresentationReaction = `-- name: InsertActiveRecordingPresentationReaction :one
insert into recording_presentation_reactions (
    reaction_id, presentation_handle, tenant_id, space_id, episode_id,
    recording_id, participant_id, participant_generation, display_name,
    reaction, occurred_at, expires_at
)
select $1, sources.presentation_handle, sources.tenant_id,
    sources.space_id, sources.episode_id, sources.recording_id,
    $2, $3,
    $4, $5, $6,
    $7
from recording_presentation_sources sources
join sync_recordings recordings
  on recordings.tenant_id = sources.tenant_id
 and recordings.space_id = sources.space_id
 and recordings.episode_id = sources.episode_id
 and recordings.recording_id = sources.recording_id
where sources.tenant_id = $8
  and sources.space_id = $9
  and sources.episode_id = $10
  and recordings.status in ('recording', 'stopping')
  and $6::timestamptz >= sources.capture_ready_at
on conflict (reaction_id) do nothing
returning reaction_id, presentation_handle, tenant_id, space_id, episode_id, recording_id, participant_id, participant_generation, display_name, reaction, occurred_at, expires_at, created_at
`

type InsertActiveRecordingPresentationReactionParams struct {
	ReactionID            pgtype.UUID        `json:"reaction_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantGeneration int64              `json:"participant_generation"`
	DisplayName           string             `json:"display_name"`
	Reaction              string             `json:"reaction"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	EpisodeID             pgtype.UUID        `json:"episode_id"`
}

func (q *Queries) InsertActiveRecordingPresentationReaction(ctx context.Context, arg InsertActiveRecordingPresentationReactionParams) (RecordingPresentationReaction, error) {
	row := q.db.QueryRow(ctx, insertActiveRecordingPresentationReaction,
		arg.ReactionID,
		arg.ParticipantID,
		arg.ParticipantGeneration,
		arg.DisplayName,
		arg.Reaction,
		arg.OccurredAt,
		arg.ExpiresAt,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
	)
	var i RecordingPresentationReaction
	err := row.Scan(
		&i.ReactionID,
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.ParticipantID,
		&i.ParticipantGeneration,
		&i.DisplayName,
		&i.Reaction,
		&i.OccurredAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecordingPresentation = `-- name: InsertRecordingPresentation :one
insert into recording_presentations (
    presentation_handle, tenant_id, space_id, episode_id, recording_id,
    capture_epoch, schema_version, profile_version, duration_millis,
    presentation_sha256, presentation_object_key, presentation_object_version,
    presentation_object_etag, presentation_content_type, presentation_byte_size,
    asset_manifest_object_key, asset_manifest_object_version,
    asset_manifest_object_etag, asset_manifest_content_type,
    asset_manifest_byte_size, asset_manifest_sha256, frozen_at
) values (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13,
    $14, $15,
    $16, $17,
    $18, $19,
    $20, $21,
    $22
)
on conflict (presentation_handle) do nothing
returning presentation_handle, tenant_id, space_id, episode_id, recording_id, capture_epoch, schema_version, profile_version, duration_millis, presentation_sha256, presentation_object_key, presentation_object_version, presentation_object_etag, presentation_content_type, presentation_byte_size, asset_manifest_object_key, asset_manifest_object_version, asset_manifest_object_etag, asset_manifest_content_type, asset_manifest_byte_size, asset_manifest_sha256, frozen_at, created_at
`

type InsertRecordingPresentationParams struct {
	PresentationHandle         pgtype.UUID        `json:"presentation_handle"`
	TenantID                   pgtype.UUID        `json:"tenant_id"`
	SpaceID                    pgtype.UUID        `json:"space_id"`
	EpisodeID                  pgtype.UUID        `json:"episode_id"`
	RecordingID                pgtype.UUID        `json:"recording_id"`
	CaptureEpoch               int64              `json:"capture_epoch"`
	SchemaVersion              string             `json:"schema_version"`
	ProfileVersion             string             `json:"profile_version"`
	DurationMillis             int64              `json:"duration_millis"`
	PresentationSha256         []byte             `json:"presentation_sha256"`
	PresentationObjectKey      string             `json:"presentation_object_key"`
	PresentationObjectVersion  string             `json:"presentation_object_version"`
	PresentationObjectEtag     string             `json:"presentation_object_etag"`
	PresentationContentType    string             `json:"presentation_content_type"`
	PresentationByteSize       int64              `json:"presentation_byte_size"`
	AssetManifestObjectKey     string             `json:"asset_manifest_object_key"`
	AssetManifestObjectVersion string             `json:"asset_manifest_object_version"`
	AssetManifestObjectEtag    string             `json:"asset_manifest_object_etag"`
	AssetManifestContentType   string             `json:"asset_manifest_content_type"`
	AssetManifestByteSize      int64              `json:"asset_manifest_byte_size"`
	AssetManifestSha256        []byte             `json:"asset_manifest_sha256"`
	FrozenAt                   pgtype.Timestamptz `json:"frozen_at"`
}

func (q *Queries) InsertRecordingPresentation(ctx context.Context, arg InsertRecordingPresentationParams) (RecordingPresentation, error) {
	row := q.db.QueryRow(ctx, insertRecordingPresentation,
		arg.PresentationHandle,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
		arg.CaptureEpoch,
		arg.SchemaVersion,
		arg.ProfileVersion,
		arg.DurationMillis,
		arg.PresentationSha256,
		arg.PresentationObjectKey,
		arg.PresentationObjectVersion,
		arg.PresentationObjectEtag,
		arg.PresentationContentType,
		arg.PresentationByteSize,
		arg.AssetManifestObjectKey,
		arg.AssetManifestObjectVersion,
		arg.AssetManifestObjectEtag,
		arg.AssetManifestContentType,
		arg.AssetManifestByteSize,
		arg.AssetManifestSha256,
		arg.FrozenAt,
	)
	var i RecordingPresentation
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.CaptureEpoch,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.DurationMillis,
		&i.PresentationSha256,
		&i.PresentationObjectKey,
		&i.PresentationObjectVersion,
		&i.PresentationObjectEtag,
		&i.PresentationContentType,
		&i.PresentationByteSize,
		&i.AssetManifestObjectKey,
		&i.AssetManifestObjectVersion,
		&i.AssetManifestObjectEtag,
		&i.AssetManifestContentType,
		&i.AssetManifestByteSize,
		&i.AssetManifestSha256,
		&i.FrozenAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecordingPresentationAsset = `-- name: InsertRecordingPresentationAsset :one
insert into recording_presentation_assets (
    presentation_handle, tenant_id, recording_id, ordinal, asset_id, asset_kind,
    object_key, object_version, object_etag, content_type, byte_size, sha256
) values (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
on conflict (presentation_handle, ordinal) do nothing
returning presentation_handle, tenant_id, recording_id, ordinal, asset_id, asset_kind, object_key, object_version, object_etag, content_type, byte_size, sha256, created_at
`

type InsertRecordingPresentationAssetParams struct {
	PresentationHandle pgtype.UUID `json:"presentation_handle"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	RecordingID        pgtype.UUID `json:"recording_id"`
	Ordinal            int16       `json:"ordinal"`
	AssetID            string      `json:"asset_id"`
	AssetKind          string      `json:"asset_kind"`
	ObjectKey          string      `json:"object_key"`
	ObjectVersion      string      `json:"object_version"`
	ObjectEtag         string      `json:"object_etag"`
	ContentType        string      `json:"content_type"`
	ByteSize           int64       `json:"byte_size"`
	Sha256             []byte      `json:"sha256"`
}

func (q *Queries) InsertRecordingPresentationAsset(ctx context.Context, arg InsertRecordingPresentationAssetParams) (RecordingPresentationAsset, error) {
	row := q.db.QueryRow(ctx, insertRecordingPresentationAsset,
		arg.PresentationHandle,
		arg.TenantID,
		arg.RecordingID,
		arg.Ordinal,
		arg.AssetID,
		arg.AssetKind,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.ObjectEtag,
		arg.ContentType,
		arg.ByteSize,
		arg.Sha256,
	)
	var i RecordingPresentationAsset
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.RecordingID,
		&i.Ordinal,
		&i.AssetID,
		&i.AssetKind,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectEtag,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecordingPresentationBaseline = `-- name: InsertRecordingPresentationBaseline :one
with authority as (
    select reservations.tenant_id, reservations.space_id, reservations.episode_id,
        reservations.recording_id, spaces.name as space_name,
        control.control_revision, control.folded_state,
        coalesce(stream.head_sequence, 0)::bigint as chat_head_sequence,
        stream.retained_floor_sequence,
        least($4::timestamptz, now()) as baseline_at
    from recording_pipelines pipelines
    join recording_reservations reservations on reservations.id = pipelines.reservation_id
    join spaces on spaces.tenant_id = reservations.tenant_id and spaces.id = reservations.space_id
    join sync_episode_control control
      on control.tenant_id = reservations.tenant_id
     and control.space_id = reservations.space_id
     and control.episode_id = reservations.episode_id
    left join sync_chat_streams stream
      on stream.tenant_id = reservations.tenant_id and stream.space_id = reservations.space_id
    where pipelines.recording_id = $5
      and reservations.tenant_id = $6
      and reservations.space_id = $7
      and reservations.episode_id = $8
), participant_snapshot as (
    select coalesce(jsonb_agg(jsonb_build_object(
        'participant_id', participants.id,
        'generation', participants.generation,
        'status', participants.status,
        'joined_at', participants.joined_at,
        'left_at', participants.left_at
    ) order by participants.created_at, participants.id)
        filter (where participants.id is not null), '[]'::jsonb) as facts
    from authority
    left join participants
      on participants.tenant_id = authority.tenant_id
     and participants.space_id = authority.space_id
     and participants.episode_id = authority.episode_id
), whiteboard_snapshot as (
    select scene.scene_id, scene.revision,
        jsonb_build_object(
            'scene_id', scene.scene_id,
            'revision', scene.revision,
            'presenting', scene.presenting_episode_id = authority.episode_id,
            'app_state', scene.app_state,
            'elements', coalesce((select jsonb_agg(jsonb_build_object(
                    'id', element.element_id,
                    'type', element.element_type,
                    'version', element.version,
                    'version_nonce', element.version_nonce,
                    'index', element.element_index,
                    'is_deleted', element.is_deleted,
                    'payload', element.payload
                ) order by element.element_index, element.element_id)
                from sync_whiteboard_elements element
                where element.tenant_id = scene.tenant_id
                  and element.space_id = scene.space_id
                  and element.episode_id = scene.episode_id
                  and element.scene_id = scene.scene_id), '[]'::jsonb)
        ) as snapshot
    from authority
    join sync_whiteboard_scenes scene
      on scene.tenant_id = authority.tenant_id
     and scene.space_id = authority.space_id
     and scene.episode_id = authority.episode_id
     and scene.is_current
)
insert into recording_presentation_baselines (
    presentation_handle, tenant_id, space_id, episode_id, recording_id,
    schema_version, profile_version, profile, space_name,
    episode_control_revision, episode_folded_state, participant_facts,
    chat_head_sequence, chat_retained_floor_sequence,
    whiteboard_scene_id, whiteboard_revision, whiteboard_snapshot, baseline_at
)
select $1, authority.tenant_id, authority.space_id,
    authority.episode_id, authority.recording_id, 'recording_presentation.v1',
    $2, $3::jsonb, authority.space_name,
    authority.control_revision, authority.folded_state, participant_snapshot.facts,
    authority.chat_head_sequence, authority.retained_floor_sequence,
    whiteboard_snapshot.scene_id, whiteboard_snapshot.revision,
    whiteboard_snapshot.snapshot, authority.baseline_at
from authority cross join participant_snapshot left join whiteboard_snapshot on true
on conflict (recording_id) do nothing
returning presentation_handle, tenant_id, space_id, episode_id, recording_id, schema_version, profile_version, profile, space_name, episode_control_revision, episode_folded_state, participant_facts, chat_head_sequence, chat_retained_floor_sequence, whiteboard_scene_id, whiteboard_revision, whiteboard_snapshot, baseline_at, created_at
`

type InsertRecordingPresentationBaselineParams struct {
	PresentationHandle pgtype.UUID        `json:"presentation_handle"`
	ProfileVersion     string             `json:"profile_version"`
	Profile            []byte             `json:"profile"`
	BaselineAt         pgtype.Timestamptz `json:"baseline_at"`
	RecordingID        pgtype.UUID        `json:"recording_id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	SpaceID            pgtype.UUID        `json:"space_id"`
	EpisodeID          pgtype.UUID        `json:"episode_id"`
}

func (q *Queries) InsertRecordingPresentationBaseline(ctx context.Context, arg InsertRecordingPresentationBaselineParams) (RecordingPresentationBaseline, error) {
	row := q.db.QueryRow(ctx, insertRecordingPresentationBaseline,
		arg.PresentationHandle,
		arg.ProfileVersion,
		arg.Profile,
		arg.BaselineAt,
		arg.RecordingID,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
	)
	var i RecordingPresentationBaseline
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.SchemaVersion,
		&i.ProfileVersion,
		&i.Profile,
		&i.SpaceName,
		&i.EpisodeControlRevision,
		&i.EpisodeFoldedState,
		&i.ParticipantFacts,
		&i.ChatHeadSequence,
		&i.ChatRetainedFloorSequence,
		&i.WhiteboardSceneID,
		&i.WhiteboardRevision,
		&i.WhiteboardSnapshot,
		&i.BaselineAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecordingPresentationSource = `-- name: InsertRecordingPresentationSource :one
with baseline as (
    select baselines.presentation_handle, baselines.tenant_id, baselines.space_id, baselines.episode_id, baselines.recording_id, baselines.schema_version, baselines.profile_version, baselines.profile, baselines.space_name, baselines.episode_control_revision, baselines.episode_folded_state, baselines.participant_facts, baselines.chat_head_sequence, baselines.chat_retained_floor_sequence, baselines.whiteboard_scene_id, baselines.whiteboard_revision, baselines.whiteboard_snapshot, baselines.baseline_at, baselines.created_at from recording_presentation_baselines baselines
    where baselines.tenant_id = $3
      and baselines.space_id = $4
      and baselines.episode_id = $5
      and baselines.recording_id = $6
      and baselines.baseline_at <= $2::timestamptz
), pipeline as (
    select pipelines.recording_id
    from recording_pipelines pipelines
    where pipelines.recording_id = $6
      and pipelines.tenant_id = $3
      and pipelines.capture_epoch = $1
      and pipelines.capture_ready_at = $2
), control_delta as (
    select coalesce(jsonb_agg(jsonb_build_object(
        'revision', events.revision, 'event_name', events.event_name,
        'payload', events.payload, 'created_at', events.created_at
    ) order by events.revision) filter (where events.revision is not null), '[]'::jsonb) as events,
    coalesce(max(events.revision), baseline.episode_control_revision)::bigint as end_revision
    from baseline
    left join sync_control_events events
      on events.tenant_id = baseline.tenant_id
     and events.space_id = baseline.space_id
     and events.episode_id = baseline.episode_id
     and events.revision > baseline.episode_control_revision
     and events.created_at <= $2
    group by baseline.episode_control_revision
), participant_snapshot as (
    select coalesce(jsonb_agg(jsonb_build_object(
        'participant_id', participants.id,
        'generation', participants.generation,
        'status', participants.status,
        'joined_at', participants.joined_at,
        'left_at', participants.left_at
    ) order by participants.created_at, participants.id)
        filter (where participants.id is not null), '[]'::jsonb) as facts
    from baseline
    left join participants
      on participants.tenant_id = baseline.tenant_id
     and participants.space_id = baseline.space_id
     and participants.episode_id = baseline.episode_id
), chat_snapshot as (
    select coalesce(max(stream.head_sequence), 0)::bigint as head_sequence,
        max(stream.retained_floor_sequence)::bigint as retained_floor_sequence,
        coalesce(jsonb_agg(messages.body order by messages.sequence)
            filter (where messages.sequence is not null), '[]'::jsonb) as messages
    from baseline
    left join sync_chat_streams stream
      on stream.tenant_id = baseline.tenant_id and stream.space_id = baseline.space_id
    left join lateral (
        select message.sequence, jsonb_build_object(
            'message_id', message.message_id,
            'sequence', message.sequence,
            'participant_id', message.participant_id,
            'participant_generation', message.participant_generation,
            'display_name', message.display_name,
            'message_text', message.message_text,
            'created_at', message.created_at,
            'attachments', coalesce((select jsonb_agg(jsonb_build_object(
                'attachment_id', attachment.attachment_id,
                'object_key', attachment.object_key,
                'immutable_object_identity', attachment.immutable_object_identity,
                'original_filename', attachment.original_filename,
                'mime_type', attachment.mime_type,
                'byte_length', attachment.byte_length,
                'sha256', encode(attachment.sha256, 'hex')
            ) order by attachment.message_ordinal)
            from sync_chat_attachments attachment
            where attachment.tenant_id = message.tenant_id
              and attachment.space_id = message.space_id
              and attachment.message_sequence = message.sequence
              and attachment.status = 'attached'), '[]'::jsonb)
        ) as body
        from sync_chat_messages message
        where message.tenant_id = baseline.tenant_id
          and message.space_id = baseline.space_id
          and message.episode_id = baseline.episode_id
          and message.created_at <= $2
        order by message.sequence desc
        limit 100
    ) messages on true
), whiteboard_delta as (
    select coalesce(jsonb_agg(jsonb_build_object(
        'operation_name', receipts.operation_name,
        'operation_id', receipts.operation_id,
        'scene_id', receipts.scene_id,
        'revision', receipts.revision,
        'elements', receipts.event_elements,
        'presenting', receipts.event_presenting,
        'completed_at', receipts.completed_at
    ) order by receipts.completed_at, receipts.operation_id)
        filter (where receipts.operation_id is not null), '[]'::jsonb) as events,
    coalesce(max(receipts.revision), baseline.whiteboard_revision, 0)::bigint as end_revision
    from baseline
    left join sync_whiteboard_operation_receipts receipts
      on receipts.tenant_id = baseline.tenant_id
     and receipts.space_id = baseline.space_id
     and receipts.episode_id = baseline.episode_id
     and receipts.completed_at > baseline.baseline_at
     and receipts.completed_at <= $2
    group by baseline.whiteboard_revision
), capture_plan_head as (
    select coalesce(max(plans.revision), 0)::bigint as revision
    from baseline
    left join recording_capture_plans plans
      on plans.tenant_id = baseline.tenant_id
     and plans.space_id = baseline.space_id
     and plans.episode_id = baseline.episode_id
     and plans.recording_id = baseline.recording_id
     and plans.capture_epoch = $1
     and plans.created_at <= $2
)
insert into recording_presentation_sources (
    presentation_handle, tenant_id, space_id, episode_id, recording_id,
    capture_epoch, capture_ready_at,
    episode_control_start_revision, episode_control_events, episode_control_end_revision,
    participant_facts, chat_start_sequence, chat_retained_floor_sequence,
    initial_chat_messages, whiteboard_start_revision, whiteboard_events,
    whiteboard_end_revision, capture_plan_start_revision
)
select baseline.presentation_handle, baseline.tenant_id, baseline.space_id,
    baseline.episode_id, baseline.recording_id, $1,
    $2, baseline.episode_control_revision,
    control_delta.events, control_delta.end_revision, participant_snapshot.facts,
    chat_snapshot.head_sequence, chat_snapshot.retained_floor_sequence,
    chat_snapshot.messages, coalesce(baseline.whiteboard_revision, 0),
    whiteboard_delta.events, whiteboard_delta.end_revision, capture_plan_head.revision
from baseline join pipeline on pipeline.recording_id = baseline.recording_id
cross join control_delta cross join participant_snapshot cross join chat_snapshot
cross join whiteboard_delta cross join capture_plan_head
on conflict (presentation_handle) do nothing
returning presentation_handle, tenant_id, space_id, episode_id, recording_id, capture_epoch, capture_ready_at, episode_control_start_revision, episode_control_events, episode_control_end_revision, participant_facts, chat_start_sequence, chat_retained_floor_sequence, initial_chat_messages, whiteboard_start_revision, whiteboard_events, whiteboard_end_revision, capture_plan_start_revision, created_at
`

type InsertRecordingPresentationSourceParams struct {
	CaptureEpoch   int64              `json:"capture_epoch"`
	CaptureReadyAt pgtype.Timestamptz `json:"capture_ready_at"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	SpaceID        pgtype.UUID        `json:"space_id"`
	EpisodeID      pgtype.UUID        `json:"episode_id"`
	RecordingID    pgtype.UUID        `json:"recording_id"`
}

func (q *Queries) InsertRecordingPresentationSource(ctx context.Context, arg InsertRecordingPresentationSourceParams) (RecordingPresentationSource, error) {
	row := q.db.QueryRow(ctx, insertRecordingPresentationSource,
		arg.CaptureEpoch,
		arg.CaptureReadyAt,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.RecordingID,
	)
	var i RecordingPresentationSource
	err := row.Scan(
		&i.PresentationHandle,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.RecordingID,
		&i.CaptureEpoch,
		&i.CaptureReadyAt,
		&i.EpisodeControlStartRevision,
		&i.EpisodeControlEvents,
		&i.EpisodeControlEndRevision,
		&i.ParticipantFacts,
		&i.ChatStartSequence,
		&i.ChatRetainedFloorSequence,
		&i.InitialChatMessages,
		&i.WhiteboardStartRevision,
		&i.WhiteboardEvents,
		&i.WhiteboardEndRevision,
		&i.CapturePlanStartRevision,
		&i.CreatedAt,
	)
	return i, err
}

const listRecordingPresentationAssetsForRender = `-- name: ListRecordingPresentationAssetsForRender :many
select ordinal, asset_id, asset_kind, object_key, object_version,
    object_etag, content_type, byte_size, sha256
from recording_presentation_assets
where tenant_id = $1
  and recording_id = $2
  and presentation_handle = $3
order by ordinal
`

type ListRecordingPresentationAssetsForRenderParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	RecordingID        pgtype.UUID `json:"recording_id"`
	PresentationHandle pgtype.UUID `json:"presentation_handle"`
}

type ListRecordingPresentationAssetsForRenderRow struct {
	Ordinal       int16  `json:"ordinal"`
	AssetID       string `json:"asset_id"`
	AssetKind     string `json:"asset_kind"`
	ObjectKey     string `json:"object_key"`
	ObjectVersion string `json:"object_version"`
	ObjectEtag    string `json:"object_etag"`
	ContentType   string `json:"content_type"`
	ByteSize      int64  `json:"byte_size"`
	Sha256        []byte `json:"sha256"`
}

func (q *Queries) ListRecordingPresentationAssetsForRender(ctx context.Context, arg ListRecordingPresentationAssetsForRenderParams) ([]ListRecordingPresentationAssetsForRenderRow, error) {
	rows, err := q.db.Query(ctx, listRecordingPresentationAssetsForRender, arg.TenantID, arg.RecordingID, arg.PresentationHandle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingPresentationAssetsForRenderRow
	for rows.Next() {
		var i ListRecordingPresentationAssetsForRenderRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.AssetID,
			&i.AssetKind,
			&i.ObjectKey,
			&i.ObjectVersion,
			&i.ObjectEtag,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingPresentationReactions = `-- name: ListRecordingPresentationReactions :many
select reaction_id, presentation_handle, tenant_id, space_id, episode_id, recording_id, participant_id, participant_generation, display_name, reaction, occurred_at, expires_at, created_at from recording_presentation_reactions
where tenant_id = $1
  and recording_id = $2
  and presentation_handle = $3
  and occurred_at <= $4
order by occurred_at, reaction_id
`

type ListRecordingPresentationReactionsParams struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	RecordingID        pgtype.UUID        `json:"recording_id"`
	PresentationHandle pgtype.UUID        `json:"presentation_handle"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) ListRecordingPresentationReactions(ctx context.Context, arg ListRecordingPresentationReactionsParams) ([]RecordingPresentationReaction, error) {
	rows, err := q.db.Query(ctx, listRecordingPresentationReactions,
		arg.TenantID,
		arg.RecordingID,
		arg.PresentationHandle,
		arg.EndedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingPresentationReaction
	for rows.Next() {
		var i RecordingPresentationReaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.PresentationHandle,
			&i.TenantID,
			&i.SpaceID,
			&i.EpisodeID,
			&i.RecordingID,
			&i.ParticipantID,
			&i.ParticipantGeneration,
			&i.DisplayName,
			&i.Reaction,
			&i.OccurredAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
