// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whiteboard_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWhiteboardFileCleanup = `-- name: ClaimWhiteboardFileCleanup :many
with candidates as (
    select file.upload_id
    from sync_whiteboard_files file
    join episodes episode
        on episode.tenant_id = file.tenant_id
        and episode.space_id = file.space_id
        and episode.id = file.episode_id
    where (
        file.cleanup_claimed_until is null
        or file.cleanup_claimed_until <= $3
    )
        and (
            (
                file.status in ('pending', 'finalizing', 'failed')
                and file.expires_at <= $3
            )
            or (
                episode.status = 'ended'
                and episode.ended_at <= $4
            )
        )
    order by
        case
            when episode.status = 'ended' and episode.ended_at <= $4
                then episode.ended_at
            else file.expires_at
        end,
        file.upload_id
    for update of file skip locked
    limit $5
)
update sync_whiteboard_files file
set
    cleanup_claim_token = $1,
    cleanup_claimed_until = $2,
    cleanup_attempts = cleanup_attempts + 1,
    updated_at = now()
from candidates
where file.upload_id = candidates.upload_id
returning file.upload_id, file.object_key
`

type ClaimWhiteboardFileCleanupParams struct {
	ClaimToken  pgtype.UUID        `json:"claim_token"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
	NowAt       pgtype.Timestamptz `json:"now_at"`
	EndedBefore pgtype.Timestamptz `json:"ended_before"`
	BatchLimit  int32              `json:"batch_limit"`
}

type ClaimWhiteboardFileCleanupRow struct {
	UploadID  pgtype.UUID `json:"upload_id"`
	ObjectKey string      `json:"object_key"`
}

func (q *Queries) ClaimWhiteboardFileCleanup(ctx context.Context, arg ClaimWhiteboardFileCleanupParams) ([]ClaimWhiteboardFileCleanupRow, error) {
	rows, err := q.db.Query(ctx, claimWhiteboardFileCleanup,
		arg.ClaimToken,
		arg.LeaseUntil,
		arg.NowAt,
		arg.EndedBefore,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimWhiteboardFileCleanupRow
	for rows.Next() {
		var i ClaimWhiteboardFileCleanupRow
		if err := rows.Scan(&i.UploadID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimWhiteboardFileUploadFinalize = `-- name: ClaimWhiteboardFileUploadFinalize :one
update sync_whiteboard_files file
set status = 'finalizing', updated_at = now()
from participants participant, sync_whiteboard_scenes scene
where file.upload_id = $1
    and file.tenant_id = $2
    and file.space_id = $3
    and file.episode_id = $4
    and file.participant_id = $5
    and file.participant_generation = $6
    and file.status = 'pending'
    and file.expires_at > $7
    and participant.tenant_id = file.tenant_id
    and participant.space_id = file.space_id
    and participant.episode_id = file.episode_id
    and participant.id = file.participant_id
    and participant.generation = file.participant_generation
    and participant.status = 'active'
    and scene.tenant_id = file.tenant_id
    and scene.space_id = file.space_id
    and scene.scene_id = file.scene_id
    and scene.is_current
returning
    file.upload_id,
    file.tenant_id,
    file.space_id,
    file.episode_id,
    file.scene_id,
    file.participant_id,
    file.participant_generation,
    file.file_id,
    file.object_key,
    file.mime_type,
    file.byte_length,
    file.sha256,
    file.expires_at
`

type ClaimWhiteboardFileUploadFinalizeParams struct {
	UploadID              pgtype.UUID        `json:"upload_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	EpisodeID             pgtype.UUID        `json:"episode_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantGeneration int64              `json:"participant_generation"`
	NowAt                 pgtype.Timestamptz `json:"now_at"`
}

type ClaimWhiteboardFileUploadFinalizeRow struct {
	UploadID              pgtype.UUID        `json:"upload_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	EpisodeID             pgtype.UUID        `json:"episode_id"`
	SceneID               pgtype.UUID        `json:"scene_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantGeneration int64              `json:"participant_generation"`
	FileID                string             `json:"file_id"`
	ObjectKey             string             `json:"object_key"`
	MimeType              string             `json:"mime_type"`
	ByteLength            int64              `json:"byte_length"`
	Sha256                []byte             `json:"sha256"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ClaimWhiteboardFileUploadFinalize(ctx context.Context, arg ClaimWhiteboardFileUploadFinalizeParams) (ClaimWhiteboardFileUploadFinalizeRow, error) {
	row := q.db.QueryRow(ctx, claimWhiteboardFileUploadFinalize,
		arg.UploadID,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.ParticipantID,
		arg.ParticipantGeneration,
		arg.NowAt,
	)
	var i ClaimWhiteboardFileUploadFinalizeRow
	err := row.Scan(
		&i.UploadID,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.SceneID,
		&i.ParticipantID,
		&i.ParticipantGeneration,
		&i.FileID,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteLength,
		&i.Sha256,
		&i.ExpiresAt,
	)
	return i, err
}

const completeWhiteboardFileCleanup = `-- name: CompleteWhiteboardFileCleanup :execrows
delete from sync_whiteboard_files
where upload_id = $1
    and cleanup_claim_token = $2
`

type CompleteWhiteboardFileCleanupParams struct {
	UploadID   pgtype.UUID `json:"upload_id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) CompleteWhiteboardFileCleanup(ctx context.Context, arg CompleteWhiteboardFileCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWhiteboardFileCleanup, arg.UploadID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWhiteboardFileUpload = `-- name: CompleteWhiteboardFileUpload :execrows
update sync_whiteboard_files
set
    status = 'ready',
    immutable_object_identity = $1,
    finalized_at = now(),
    updated_at = now()
where upload_id = $2
    and status = 'finalizing'
`

type CompleteWhiteboardFileUploadParams struct {
	ImmutableObjectIdentity pgtype.Text `json:"immutable_object_identity"`
	UploadID                pgtype.UUID `json:"upload_id"`
}

func (q *Queries) CompleteWhiteboardFileUpload(ctx context.Context, arg CompleteWhiteboardFileUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWhiteboardFileUpload, arg.ImmutableObjectIdentity, arg.UploadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failWhiteboardFileUpload = `-- name: FailWhiteboardFileUpload :execrows
update sync_whiteboard_files
set status = 'failed', updated_at = now()
where upload_id = $1
    and status in ('pending', 'finalizing')
`

func (q *Queries) FailWhiteboardFileUpload(ctx context.Context, uploadID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, failWhiteboardFileUpload, uploadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReadyWhiteboardFile = `-- name: GetReadyWhiteboardFile :one
select
    file.upload_id,
    file.tenant_id,
    file.space_id,
    file.episode_id,
    file.scene_id,
    file.participant_id,
    file.participant_generation,
    file.file_id,
    file.object_key,
    file.mime_type,
    file.byte_length,
    file.sha256,
    file.expires_at
from sync_whiteboard_files file
join participants participant
    on participant.tenant_id = file.tenant_id
    and participant.space_id = file.space_id
    and participant.episode_id = file.episode_id
    and participant.id = $1
    and participant.generation = $2
join episodes episode
    on episode.tenant_id = file.tenant_id
    and episode.space_id = file.space_id
    and episode.id = file.episode_id
join sync_whiteboard_scenes scene
    on scene.tenant_id = file.tenant_id
    and scene.space_id = file.space_id
    and scene.scene_id = file.scene_id
where file.tenant_id = $3
    and file.space_id = $4
    and file.episode_id = $5
    and file.file_id = $6
    and file.status = 'ready'
    and participant.status = 'active'
    and episode.status = 'active'
    and scene.is_current
`

type GetReadyWhiteboardFileParams struct {
	ParticipantID         pgtype.UUID `json:"participant_id"`
	ParticipantGeneration int64       `json:"participant_generation"`
	TenantID              pgtype.UUID `json:"tenant_id"`
	SpaceID               pgtype.UUID `json:"space_id"`
	EpisodeID             pgtype.UUID `json:"episode_id"`
	FileID                string      `json:"file_id"`
}

type GetReadyWhiteboardFileRow struct {
	UploadID              pgtype.UUID        `json:"upload_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	EpisodeID             pgtype.UUID        `json:"episode_id"`
	SceneID               pgtype.UUID        `json:"scene_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantGeneration int64              `json:"participant_generation"`
	FileID                string             `json:"file_id"`
	ObjectKey             string             `json:"object_key"`
	MimeType              string             `json:"mime_type"`
	ByteLength            int64              `json:"byte_length"`
	Sha256                []byte             `json:"sha256"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetReadyWhiteboardFile(ctx context.Context, arg GetReadyWhiteboardFileParams) (GetReadyWhiteboardFileRow, error) {
	row := q.db.QueryRow(ctx, getReadyWhiteboardFile,
		arg.ParticipantID,
		arg.ParticipantGeneration,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.FileID,
	)
	var i GetReadyWhiteboardFileRow
	err := row.Scan(
		&i.UploadID,
		&i.TenantID,
		&i.SpaceID,
		&i.EpisodeID,
		&i.SceneID,
		&i.ParticipantID,
		&i.ParticipantGeneration,
		&i.FileID,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteLength,
		&i.Sha256,
		&i.ExpiresAt,
	)
	return i, err
}

const reserveWhiteboardFileUpload = `-- name: ReserveWhiteboardFileUpload :execrows
insert into sync_whiteboard_files (
    upload_id,
    tenant_id,
    space_id,
    episode_id,
    scene_id,
    participant_id,
    participant_generation,
    file_id,
    object_key,
    mime_type,
    byte_length,
    sha256,
    expires_at
)
select
    $1,
    participant.tenant_id,
    participant.space_id,
    participant.episode_id,
    scene.scene_id,
    participant.id,
    participant.generation,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
from participants participant
join episodes episode
    on episode.tenant_id = participant.tenant_id
    and episode.space_id = participant.space_id
    and episode.id = participant.episode_id
join sync_whiteboard_scenes scene
    on scene.tenant_id = participant.tenant_id
    and scene.space_id = participant.space_id
    and scene.scene_id = $8
    and scene.is_current
left join sync_whiteboard_permissions permission
    on permission.tenant_id = participant.tenant_id
    and permission.space_id = participant.space_id
    and permission.episode_id = participant.episode_id
    and permission.participant_id = participant.id
where participant.tenant_id = $9
    and participant.space_id = $10
    and participant.episode_id = $11
    and participant.id = $12
    and participant.generation = $13
    and participant.status = 'active'
    and episode.status = 'active'
    and coalesce(
        permission.can_draw,
        participant.capabilities @> array['drawWhiteboard']::text[]
    )
`

type ReserveWhiteboardFileUploadParams struct {
	UploadID              pgtype.UUID        `json:"upload_id"`
	FileID                string             `json:"file_id"`
	ObjectKey             string             `json:"object_key"`
	MimeType              string             `json:"mime_type"`
	ByteLength            int64              `json:"byte_length"`
	Sha256                []byte             `json:"sha256"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	SceneID               pgtype.UUID        `json:"scene_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	EpisodeID             pgtype.UUID        `json:"episode_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantGeneration int64              `json:"participant_generation"`
}

func (q *Queries) ReserveWhiteboardFileUpload(ctx context.Context, arg ReserveWhiteboardFileUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveWhiteboardFileUpload,
		arg.UploadID,
		arg.FileID,
		arg.ObjectKey,
		arg.MimeType,
		arg.ByteLength,
		arg.Sha256,
		arg.ExpiresAt,
		arg.SceneID,
		arg.TenantID,
		arg.SpaceID,
		arg.EpisodeID,
		arg.ParticipantID,
		arg.ParticipantGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
