/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as RoomErrorRouteImport } from './routes/room/error'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as DocsSdkReactRouteImport } from './routes/docs/sdk-react'
import { Route as DocsHooksRouteImport } from './routes/docs/hooks'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsComponentsRouteImport } from './routes/docs/components'
import { Route as DocsAuthenticationRouteImport } from './routes/docs/authentication'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomErrorRoute = RoomErrorRouteImport.update({
  id: '/room/error',
  path: '/room/error',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSdkReactRoute = DocsSdkReactRouteImport.update({
  id: '/docs/sdk-react',
  path: '/docs/sdk-react',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHooksRoute = DocsHooksRouteImport.update({
  id: '/docs/hooks',
  path: '/docs/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRoute = DocsComponentsRouteImport.update({
  id: '/docs/components',
  path: '/docs/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/docs/authentication',
  path: '/docs/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/docs/api-reference',
  path: '/docs/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hooks': typeof DocsHooksRoute
  '/docs/sdk-react': typeof DocsSdkReactRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/error': typeof RoomErrorRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hooks': typeof DocsHooksRoute
  '/docs/sdk-react': typeof DocsSdkReactRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/error': typeof RoomErrorRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hooks': typeof DocsHooksRoute
  '/docs/sdk-react': typeof DocsSdkReactRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/error': typeof RoomErrorRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/components'
    | '/docs/getting-started'
    | '/docs/hooks'
    | '/docs/sdk-react'
    | '/room/$roomId'
    | '/room/error'
    | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/components'
    | '/docs/getting-started'
    | '/docs/hooks'
    | '/docs/sdk-react'
    | '/room/$roomId'
    | '/room/error'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/components'
    | '/docs/getting-started'
    | '/docs/hooks'
    | '/docs/sdk-react'
    | '/room/$roomId'
    | '/room/error'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsComponentsRoute: typeof DocsComponentsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsHooksRoute: typeof DocsHooksRoute
  DocsSdkReactRoute: typeof DocsSdkReactRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomErrorRoute: typeof RoomErrorRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/error': {
      id: '/room/error'
      path: '/room/error'
      fullPath: '/room/error'
      preLoaderRoute: typeof RoomErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sdk-react': {
      id: '/docs/sdk-react'
      path: '/docs/sdk-react'
      fullPath: '/docs/sdk-react'
      preLoaderRoute: typeof DocsSdkReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hooks': {
      id: '/docs/hooks'
      path: '/docs/hooks'
      fullPath: '/docs/hooks'
      preLoaderRoute: typeof DocsHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components': {
      id: '/docs/components'
      path: '/docs/components'
      fullPath: '/docs/components'
      preLoaderRoute: typeof DocsComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/docs/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/docs/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsComponentsRoute: DocsComponentsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsHooksRoute: DocsHooksRoute,
  DocsSdkReactRoute: DocsSdkReactRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomErrorRoute: RoomErrorRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
