import type { ChalkAssignableParticipantRole, ChalkReaction, ChalkSessionSnapshot } from "@q9labsai/chalk-client";
import type { Dispatch, SetStateAction } from "react";

import type { UseChatReturn } from "../../hooks/useChat";
import type { UseInteractionsReturn } from "../../hooks/useInteractions";
import type { UseLayoutReturn } from "../../hooks/useLayout";
import type { UseMeetingParticipantsReturn } from "../../hooks/useMeetingParticipants";
import type { UseScreenShareReturn } from "../../hooks/useScreenShare";
import type { MeetingRoomDiagnosticsSnapshot } from "./diagnostics";
import type { MeetingPanelName } from "./types";
import type { useMeetingRoomController } from "./useMeetingRoomController";
import type { useMeetingRoomDerived } from "./useMeetingRoomDerived";
import type { MeetingRoomChat } from "./useMeetingRoomChat";
import type { MeetingRoomInteractions } from "./useMeetingRoomInteractions";
import type { MeetingWhiteboardState } from "./useMeetingRoomPanels";

type ExpectedMeetingRoomController = {
  readonly simulatorMediaDisabled: boolean;
  readonly roomName: string;
  readonly isHost: boolean;
  readonly panel: MeetingPanelName | null;
  readonly selfName: string;
  readonly isMuted: boolean;
  readonly isCameraOff: boolean;
  readonly handRaised: boolean;
  readonly raisedHandCount: number;
  readonly activeReactions: MeetingRoomInteractions["activeReactions"];
  readonly secondsElapsed: number;
  readonly formattedDuration: string;
  readonly actionsOpen: boolean;
  readonly reactionPickerOpen: boolean;
  readonly chatDraft: string;
  readonly chatAttachments: MeetingRoomChat["chatAttachments"];
  readonly chatAttachmentsLoading: boolean;
  readonly participantCount: number;
  readonly canChat: boolean;
  readonly canParticipants: boolean;
  readonly canScreenShare: boolean;
  readonly canReactions: boolean;
  readonly canHandRaise: boolean;
  readonly canWhiteboard: boolean;
  readonly canManageAdmission: boolean;
  readonly canSetParticipantRole: boolean;
  readonly canTransferHost: boolean;
  readonly canRequestMedia: boolean;
  readonly canMuteParticipants: boolean;
  readonly canRemoveParticipants: boolean;
  readonly canStopParticipantCamera: boolean;
  readonly canStopParticipantScreenShare: boolean;
  readonly admissionRequests: ChalkSessionSnapshot["admissionRequests"];
  readonly roomDiagnostics: MeetingRoomDiagnosticsSnapshot;
  readonly participants: UseMeetingParticipantsReturn;
  readonly chat: UseChatReturn;
  readonly interactions: UseInteractionsReturn;
  readonly screenShare: UseScreenShareReturn;
  readonly layout: UseLayoutReturn;
  readonly whiteboard: MeetingWhiteboardState;
  readonly derived: ReturnType<typeof useMeetingRoomDerived>;
  readonly setActionsOpen: Dispatch<SetStateAction<boolean>>;
  readonly setReactionPickerOpen: Dispatch<SetStateAction<boolean>>;
  readonly setChatDraft: Dispatch<SetStateAction<string>>;
  readonly handleLeave: () => void;
  readonly openPanel: (nextPanel: MeetingPanelName) => void;
  readonly closePanel: () => void;
  readonly handleInviteParticipants: () => void;
  readonly toggleAudio: () => void;
  readonly toggleVideo: () => void;
  readonly toggleScreenShare: () => void;
  readonly toggleHand: () => void;
  readonly sendReaction: (reaction: ChalkReaction) => void;
  readonly sendChatMessage: () => void;
  readonly pickChatAttachments: (() => void) | undefined;
  readonly removeChatAttachment: (attachmentId: string) => void;
  readonly openChatAttachment: (attachmentId: string) => void;
  readonly markChatMessageVisible: (sequence: string) => void;
  readonly admitParticipant: (admissionRequestId: string) => void;
  readonly denyAdmission: (admissionRequestId: string) => void;
  readonly setParticipantRole: (participantSessionId: string, role: ChalkAssignableParticipantRole) => void;
  readonly transferHost: (participantSessionId: string) => void;
  readonly removeParticipant: (participantSessionId: string) => void;
  readonly muteParticipant: (participantSessionId: string) => void;
  readonly requestUnmuteParticipant: (participantSessionId: string) => void;
  readonly requestStartParticipantCamera: (participantSessionId: string) => void;
  readonly stopParticipantCamera: (participantSessionId: string) => void;
  readonly stopParticipantScreenShare: (participantSessionId: string) => void;
};

type IsAssignableBothWays<Current, Expected> = Current extends Expected ? (Expected extends Current ? true : false) : false;
type Assert<T extends true> = T;

export type MeetingRoomControllerContractCheck = Assert<IsAssignableBothWays<ReturnType<typeof useMeetingRoomController>, ExpectedMeetingRoomController>>;
