# Generated by tools/contract-fixture-proof/src/emitters/sync-elixir.mjs
# Do not edit by hand.
# credo:disable-for-this-file Credo.Check.Refactor.CyclomaticComplexity
# credo:disable-for-this-file Credo.Check.Refactor.Nesting
defmodule ChalkSync.Contract.GeneratedV1 do
  @moduledoc false

  @protocol_version 1
  @client_commands %{
    "set_hand_raised" => :set_hand_raised,
    "set_display_name" => :set_display_name,
    "set_admission_policy" => :set_admission_policy,
    "assign_roles" => :assign_roles
  }
  @client_operations %{
    "admit_participant" => :admit_participant,
    "deny_admission" => :deny_admission,
    "mute_participant" => :mute_participant,
    "stop_participant_camera" => :stop_participant_camera,
    "stop_participant_screen_share" => :stop_participant_screen_share,
    "remove_participant" => :remove_participant,
    "start_recording" => :start_recording,
    "stop_recording" => :stop_recording,
    "participant_leave" => :participant_leave,
    "start_episode" => :start_episode,
    "extend_episode" => :extend_episode,
    "end_episode" => :end_episode
  }
  @event_origins %{
    "participant_joined" => "lifecycle",
    "participant_left" => "external",
    "episode_started" => "lifecycle",
    "episode_ended" => "external",
    "hand_raised" => "command",
    "hand_lowered" => "command",
    "participant_display_name_changed" => "command",
    "admission_policy_changed" => "command",
    "role_assigned" => "command",
    "deadline_changed" => "external",
    "admission_requested" => "lifecycle",
    "admission_denied" => "external",
    "admission_expired" => "external",
    "participant_microphone_stopped" => "external",
    "participant_camera_stopped" => "external",
    "participant_screen_share_stopped" => "external",
    "recording_status_changed" => "external"
  }
  @limits %{
    "decodedInboundFrameBytes" => 65_536,
    "correlationReservedBytes" => 1160,
    "tokenBytes" => 8192,
    "commandIdMinBytes" => 16,
    "commandIdMaxBytes" => 64,
    "requestIdMinBytes" => 16,
    "requestIdMaxBytes" => 64,
    "decodedCommandPayloadBytes" => 16_384,
    "encodedLiveEventBytes" => 32_768,
    "replayPageMaxEvents" => 128,
    "replayPageEncodedBytes" => 262_144,
    "completeReplayMaxEvents" => 2048,
    "completeReplayEncodedBytes" => 2_097_152,
    "snapshotEncodedBytes" => 1_048_576,
    "projectionSnapshotEncodedBytes" => 1_048_576,
    "projectionMaxItems" => 1500,
    "directedRequestTtlMs" => 30_000,
    "directedRequestsPerActorTarget" => 4,
    "collaborationFrameBytes" => 32_768,
    "collaborationQueueMaxFrames" => 256,
    "collaborationBurstMax" => 8,
    "chatMessageUtf8Bytes" => 16_384,
    "chatMessageUnicodeScalars" => 4000,
    "chatAttachmentMaxItems" => 5,
    "chatAttachmentFileNameUtf8Bytes" => 255,
    "chatAttachmentMaxBytes" => 26_214_400,
    "chatPageMaxMessages" => 100,
    "chatPageEncodedBytes" => 131_072,
    "reactionTtlMs" => 5000,
    "reactionRateWindowMs" => 10_000,
    "reactionRateMax" => 10,
    "protocolErrorDetailBytes" => 1024
  }
  @correlation_reserved_bytes @limits["correlationReservedBytes"]
  @close_codes %{
    1000 => %{
      "code" => 1000,
      "connection" => "closed",
      "reasons" => ["terminal event acknowledged", "terminal recovery drained"]
    },
    1008 => %{
      "code" => 1008,
      "connection" => "closed",
      "reasons" => ["invalid token", "policy violation"]
    },
    1009 => %{
      "code" => 1009,
      "connection" => "closed",
      "reasons" => ["malformed frame", "oversized frame"]
    },
    1012 => %{
      "code" => 1012,
      "connection" => "closed",
      "reasons" => ["service restart", "server draining", "terminal acknowledgement timeout"]
    }
  }
  @metadata %{
    "version" => 1,
    "protocol" => %{
      "field" => "protocol",
      "value" => 1,
      "transport" => "websocket-json-text",
      "route" => "/v1/sync"
    },
    "directions" => %{
      "clientToServer" => "client-to-server",
      "serverToClient" => "server-to-client"
    },
    "phases" => [
      %{
        "id" => "awaiting_hello",
        "accepts" => ["hello", "ping"],
        "hello" => %{"transitionsTo" => "recovering", "deadlineMs" => 5000}
      },
      %{
        "id" => "recovering",
        "accepts" => ["recovery_ack", "ping"],
        "recoveryComplete" => %{"transitionsTo" => "live"}
      },
      %{
        "id" => "live",
        "accepts" => [
          "command",
          "live_target",
          "directed_request",
          "delivery_ack",
          "request_ack",
          "reaction_send",
          "chat_send",
          "chat_page_request",
          "chat_read_set",
          "ping"
        ],
        "heartbeat" => %{"intervalMs" => 20_000, "missedDeadlinesBeforeClose" => 2}
      },
      %{"id" => "terminal", "transitionsTo" => "closed"},
      %{"id" => "draining", "transitionsTo" => "closed"}
    ],
    "streams" => %{
      "control" => %{
        "required" => true,
        "authority" => "postgres",
        "version" => "revision-and-digest",
        "cursor" => "controlCursor",
        "recovery" => ["snapshot", "bounded_exact_replay", "up_to_date", "terminal"]
      },
      "media" => %{
        "required" => true,
        "authority" => "media-plane-observation",
        "version" => "projection-id-and-exact-next-sequence",
        "cursor" => nil,
        "recovery" => ["replace_latest_snapshot"]
      },
      "presence" => %{
        "required" => true,
        "authority" => "sync-live-projection",
        "version" => "projection-id-and-exact-next-sequence",
        "cursor" => nil,
        "recovery" => ["replace_latest_snapshot"]
      },
      "requests" => %{
        "required" => true,
        "authority" => "directed-live-delivery",
        "version" => "none",
        "cursor" => nil,
        "recovery" => ["none"]
      }
    },
    "correlation" => %{
      "optionalTopLevelFields" => %{
        "journey_id" => %{
          "kind" => "string",
          "minBytes" => 36,
          "maxBytes" => 36,
          "format" => "chalk-journey-id",
          "pattern" => "^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        },
        "traceparent" => %{
          "kind" => "string",
          "minBytes" => 55,
          "maxBytes" => 55,
          "format" => "w3c-traceparent",
          "pattern" => "^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$"
        },
        "tracestate" => %{
          "kind" => "string",
          "minBytes" => 1,
          "maxBytes" => 512,
          "format" => "w3c-tracestate",
          "pattern" =>
            "^[a-z][a-z0-9_*\\-/]{0,255}=[\\x21-\\x2b\\x2d-\\x3c\\x3e-\\x7e]{1,256}(,[a-z][a-z0-9_*\\-/]{0,255}=[\\x21-\\x2b\\x2d-\\x3c\\x3e-\\x7e]{1,256})*$"
        }
      },
      "acceptedOn" => %{"hello" => "client-to-server", "serverFrames" => "server-to-client"},
      "upgradeHeaders" => ["x-chalk-journey-id", "traceparent", "tracestate"],
      "rule" => "propagate_from_first_observed_layer_to_every_downstream_frame"
    },
    "externalIntents" => [
      "admit_participant",
      "deny_admission",
      "admission_request_expired",
      "mute_participant",
      "stop_participant_camera",
      "stop_participant_screen_share",
      "remove_participant",
      "start_recording",
      "stop_recording",
      "participant_leave",
      "start_episode",
      "extend_episode",
      "end_episode",
      "tenant_set_deadline",
      "tenant_end_episode",
      "maximum_duration_expired"
    ],
    "limits" => %{
      "decodedInboundFrameBytes" => 65_536,
      "correlationReservedBytes" => 1160,
      "tokenBytes" => 8192,
      "commandIdMinBytes" => 16,
      "commandIdMaxBytes" => 64,
      "requestIdMinBytes" => 16,
      "requestIdMaxBytes" => 64,
      "decodedCommandPayloadBytes" => 16_384,
      "encodedLiveEventBytes" => 32_768,
      "replayPageMaxEvents" => 128,
      "replayPageEncodedBytes" => 262_144,
      "completeReplayMaxEvents" => 2048,
      "completeReplayEncodedBytes" => 2_097_152,
      "snapshotEncodedBytes" => 1_048_576,
      "projectionSnapshotEncodedBytes" => 1_048_576,
      "projectionMaxItems" => 1500,
      "directedRequestTtlMs" => 30_000,
      "directedRequestsPerActorTarget" => 4,
      "collaborationFrameBytes" => 32_768,
      "collaborationQueueMaxFrames" => 256,
      "collaborationBurstMax" => 8,
      "chatMessageUtf8Bytes" => 16_384,
      "chatMessageUnicodeScalars" => 4000,
      "chatAttachmentMaxItems" => 5,
      "chatAttachmentFileNameUtf8Bytes" => 255,
      "chatAttachmentMaxBytes" => 26_214_400,
      "chatPageMaxMessages" => 100,
      "chatPageEncodedBytes" => 131_072,
      "reactionTtlMs" => 5000,
      "reactionRateWindowMs" => 10_000,
      "reactionRateMax" => 10,
      "protocolErrorDetailBytes" => 1024
    },
    "collaboration" => %{
      "extension" => "collaboration_v1",
      "capabilities" => ["sendReaction", "sendChat"],
      "reactions" => ["👍", "❤️", "😂", "😮", "😢", "🎉"],
      "attachmentMimeTypes" => [
        "image/png",
        "image/jpeg",
        "image/gif",
        "image/webp",
        "application/pdf",
        "text/plain",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-powerpoint",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.oasis.opendocument.text",
        "application/vnd.oasis.opendocument.spreadsheet",
        "application/vnd.oasis.opendocument.presentation"
      ],
      "chatCursor" => %{
        "exactFields" => ["after_sequence", "retained_floor_sequence"],
        "afterSequence" => "nullableUnsignedDecimal",
        "retainedFloorSequence" => "nullableUnsignedDecimal"
      },
      "helloExtension" => %{"exactFields" => ["name", "chat_cursor"]},
      "welcomeExtension" => %{
        "exactFields" => [
          "name",
          "capabilities",
          "participant_capabilities",
          "chat_head_sequence",
          "retained_floor_sequence",
          "read_receipts"
        ]
      },
      "clientFrames" => %{
        "sendReaction" => %{
          "type" => "reaction_send",
          "exactFields" => ["type", "operation_id", "reaction"]
        },
        "sendChat" => %{
          "type" => "chat_send",
          "exactFields" => ["type", "client_message_id", "text", "attachment_ids"]
        },
        "readChatPage" => %{
          "type" => "chat_page_request",
          "exactFields" => ["type", "request_id", "direction", "cursor_sequence", "limit"],
          "directions" => ["older", "newer"]
        },
        "setChatRead" => %{
          "type" => "chat_read_set",
          "exactFields" => ["type", "request_id", "sequence"]
        }
      },
      "serverFrames" => %{
        "reaction" => %{
          "type" => "reaction",
          "exactFields" => [
            "type",
            "event_id",
            "participant_id",
            "display_name",
            "reaction",
            "occurred_at",
            "expires_at"
          ]
        },
        "reactionResult" => %{
          "type" => "reaction_result",
          "acceptedFields" => ["type", "operation_id", "outcome", "reaction"],
          "rejectedFields" => ["type", "operation_id", "outcome", "error_code"],
          "outcomes" => ["accepted", "rejected"]
        },
        "chatMessage" => %{
          "type" => "chat_message",
          "exactFields" => [
            "type",
            "message_id",
            "client_message_id",
            "sequence",
            "participant_id",
            "display_name",
            "text",
            "attachments",
            "created_at"
          ]
        },
        "chatSendResult" => %{
          "type" => "chat_send_result",
          "acceptedFields" => ["type", "client_message_id", "outcome", "message"],
          "rejectedFields" => ["type", "client_message_id", "outcome", "error_code"],
          "outcomes" => ["accepted", "rejected"]
        },
        "chatPage" => %{
          "type" => "chat_page",
          "loadedFields" => [
            "type",
            "request_id",
            "outcome",
            "messages",
            "has_more",
            "head_sequence",
            "retained_floor_sequence"
          ],
          "resetFields" => ["type", "request_id", "outcome", "retained_floor_sequence"],
          "outcomes" => ["loaded", "cursor_reset"]
        },
        "chatHead" => %{
          "type" => "chat_head",
          "exactFields" => ["type", "head_sequence", "retained_floor_sequence"]
        },
        "chatReadReceipt" => %{
          "type" => "chat_read_receipt",
          "exactFields" => [
            "type",
            "participant_id",
            "participant_generation",
            "sequence",
            "read_at"
          ]
        },
        "chatReadResult" => %{
          "type" => "chat_read_result",
          "acceptedFields" => [
            "type",
            "request_id",
            "outcome",
            "participant_id",
            "participant_generation",
            "sequence",
            "read_at"
          ],
          "rejectedFields" => ["type", "request_id", "outcome", "error_code"],
          "outcomes" => ["accepted", "rejected"]
        }
      },
      "errorCodes" => [
        "capability_denied",
        "invalid_payload",
        "rate_limited",
        "overloaded",
        "episode_ended",
        "participant_stale",
        "client_message_id_conflict",
        "attachment_not_found",
        "attachment_not_ready",
        "attachment_already_claimed",
        "attachment_quota_exceeded",
        "dependency_unavailable"
      ]
    },
    "continuity" => %{
      "cursor" => %{
        "field" => "streams.control.cursor",
        "resume" => "events_after_cursor_when_digest_matches",
        "stream" => "control"
      },
      "events" => %{
        "baseRevisionField" => "base_revision",
        "revisionField" => "revision",
        "rule" => "revision_equals_base_revision_plus_one",
        "stream" => "control"
      },
      "snapshotFallback" => %{
        "when" => [
          "cursor_missing",
          "cursor_future",
          "cursor_malformed",
          "cursor_expired",
          "cursor_unavailable",
          "cursor_same_revision_digest_mismatch"
        ],
        "welcomeMode" => "snapshot"
      },
      "replay" => %{
        "pageAcknowledgement" => "recovery_ack",
        "pageCompletion" => "recovery_complete_after_acknowledged_head",
        "liveEventsAfter" => "recovery_complete",
        "maxEvents" => 2048,
        "maxEncodedBytes" => 2_097_152
      }
    },
    "idempotency" => %{
      "key" => "command_id",
      "outcomes" => ["committed", "satisfied", "rejected"],
      "scope" => "participant",
      "duplicate" => "reuses_original_semantic_outcome",
      "conflict" => "preserves_original_receipt"
    },
    "closeCodes" => [
      %{
        "code" => 1000,
        "connection" => "closed",
        "reasons" => ["terminal event acknowledged", "terminal recovery drained"]
      },
      %{
        "code" => 1008,
        "connection" => "closed",
        "reasons" => ["invalid token", "policy violation"]
      },
      %{
        "code" => 1009,
        "connection" => "closed",
        "reasons" => ["malformed frame", "oversized frame"]
      },
      %{
        "code" => 1012,
        "connection" => "closed",
        "reasons" => ["service restart", "server draining", "terminal acknowledgement timeout"]
      }
    ]
  }
  @correlation_field_keys ["journey_id", "traceparent", "tracestate"]
  @capabilities [
    "publishAudio",
    "publishVideo",
    "publishScreen",
    "subscribe",
    "raiseHand",
    "renameSelf",
    "sendChat",
    "sendReaction",
    "drawWhiteboard",
    "manageWhiteboard",
    "manageAdmission",
    "assignRoles",
    "muteOthers",
    "stopVideoOthers",
    "stopScreenOthers",
    "requestMediaOthers",
    "removeParticipant",
    "manageRecording",
    "startEpisode",
    "extendEpisode",
    "endEpisode",
    "manageMembers",
    "clearSpaceContent"
  ]
  @terminal_reasons ["episode_ended", "participant_inactive", "stale_participant_generation"]
  @rejection_reasons [
    "episode_ended",
    "participant_inactive",
    "stale_participant_generation",
    "capability_denied",
    "invalid_state",
    "invalid_target",
    "role_not_eligible",
    "screen_share_in_use",
    "recording_in_progress",
    "command_id_conflict",
    "external_operation_failed"
  ]
  @retryable_codes [
    "overloaded",
    "server_draining",
    "dependency_unavailable",
    "decision_unavailable",
    "external_operation_pending"
  ]
  @protocol_error_codes ["protocol_error", "invalid_frame", "unsupported_protocol"]
  @live_target_names ["set_microphone_enabled", "set_camera_enabled", "set_screen_share_enabled"]
  @live_target_outcomes [
    "confirmed",
    "satisfied",
    "retryable_failure",
    "terminal_failure",
    "ambiguous"
  ]
  @directed_request_names ["request_unmute", "request_start_camera"]
  @directed_request_results [
    "delivered",
    "target_unavailable",
    "expired",
    "rejected",
    "rate_limited"
  ]
  @collaboration_capabilities ["sendReaction", "sendChat"]
  @reactions ["👍", "❤️", "😂", "😮", "😢", "🎉"]
  @collaboration_error_codes [
    "capability_denied",
    "invalid_payload",
    "rate_limited",
    "overloaded",
    "episode_ended",
    "participant_stale",
    "client_message_id_conflict",
    "attachment_not_found",
    "attachment_not_ready",
    "attachment_already_claimed",
    "attachment_quota_exceeded",
    "dependency_unavailable"
  ]
  @media_sources ["microphone", "camera", "screen"]
  @presence_states ["connected", "disconnected"]
  @uuid ~r/\A[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\z/i
  @traceparent ~r/\A00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}\z/
  @tracestate ~r/\A[a-z][a-z0-9_*\x2f-]{0,255}=[\x21-\x2b\x2d-\x3c\x3e-\x7e]{1,256}(,[a-z][a-z0-9_*\x2f-]{0,255}=[\x21-\x2b\x2d-\x3c\x3e-\x7e]{1,256})*\z/
  @digest ~r/\A[0-9a-f]{64}\z/

  def protocol_version, do: @protocol_version
  def client_commands, do: @client_commands
  def client_operations, do: @client_operations
  def limits, do: @limits
  def close_code(code), do: Map.get(@close_codes, code)
  def metadata, do: @metadata

  @spec decode_client_frame(map()) :: {:ok, tuple() | :ping} | {:error, atom()}
  def decode_client_frame(frame) when is_map(frame) do
    if frame_within_limit?(frame, @limits["decodedInboundFrameBytes"]) do
      case frame["type"] do
        "hello" ->
          decode_hello(frame)

        "command" ->
          decode_command(frame)

        "operation" ->
          decode_operation(frame)

        "live_target" ->
          decode_live_target(frame)

        "directed_request" ->
          decode_directed_request(frame)

        "request_ack" ->
          decode_request_ack(frame)

        "reaction_send" ->
          decode_reaction_send(frame)

        "chat_send" ->
          decode_chat_send(frame)

        "chat_page_request" ->
          decode_chat_page_request(frame)

        "chat_read_set" ->
          decode_chat_read_set(frame)

        "delivery_ack" ->
          decode_delivery_ack(frame)

        "recovery_ack" ->
          decode_recovery_ack(frame)

        "ping" ->
          if(exact_keys?(frame, ["type"]), do: {:ok, :ping}, else: {:error, :invalid_ping})

        nil ->
          {:error, :missing_type}

        _ ->
          {:error, :unknown_type}
      end
    else
      {:error, :frame_too_large}
    end
  end

  def decode_client_frame(_frame), do: {:error, :missing_type}

  defp decode_hello(
         %{
           "type" => "hello",
           "protocol" => @protocol_version,
           "token" => token,
           "streams" => streams
         } = frame
       ) do
    cond do
      correlation_exact_keys?(frame, ["type", "protocol", "token", "streams"]) and
        valid_token?(token) and valid_streams?(streams) ->
        {:ok,
         {:hello,
          %{
            token: token,
            streams: streams,
            extensions: [],
            correlation: correlation_fields(frame)
          }}}

      correlation_exact_keys?(frame, ["type", "protocol", "token", "streams", "extensions"]) and
        valid_token?(token) and valid_streams?(streams) and
          valid_collaborations_hello_extensions?(frame["extensions"]) ->
        {:ok,
         {:hello,
          %{
            token: token,
            streams: streams,
            extensions: frame["extensions"],
            correlation: correlation_fields(frame)
          }}}

      true ->
        {:error, :invalid_hello}
    end
  end

  defp decode_hello(%{"protocol" => protocol}) when is_integer(protocol),
    do: {:error, :unsupported_protocol}

  defp decode_hello(_frame), do: {:error, :invalid_hello}

  defp decode_command(%{"command_id" => command_id, "name" => name, "payload" => payload} = frame) do
    if exact_keys?(frame, ["type", "command_id", "name", "payload"]) and
         valid_command_id?(command_id) and valid_command_payload?(name, payload),
       do:
         {:ok,
          {:command, %{command_id: command_id, name: @client_commands[name], payload: payload}}},
       else: {:error, :invalid_command}
  end

  defp decode_command(_frame), do: {:error, :invalid_command}

  defp valid_command_payload?("set_hand_raised", %{"raised" => raised} = payload) do
    exact_keys?(payload, ["raised"]) and is_boolean(raised)
  end

  defp valid_command_payload?("set_display_name", %{"display_name" => display_name} = payload) do
    exact_keys?(payload, ["display_name"]) and bounded_string?(display_name, 1, 256) and
      display_name != "" and display_name == String.trim(display_name)
  end

  defp valid_command_payload?("set_admission_policy", %{"policy" => policy} = payload) do
    exact_keys?(payload, ["policy"]) and policy in ["open", "knock", "members_only"]
  end

  defp valid_command_payload?(
         "assign_roles",
         %{"participant_id" => participant_id, "role" => role} = payload
       ) do
    exact_keys?(payload, ["participant_id", "role"]) and valid_uuid?(participant_id) and
      bounded_string?(role, 1, 64) and role != "" and role == String.trim(role)
  end

  defp valid_command_payload?(_name, _payload), do: false

  defp decode_operation(
         %{"command_id" => command_id, "name" => name, "payload" => payload} = frame
       ) do
    if exact_keys?(frame, ["type", "command_id", "name", "payload"]) and
         valid_command_id?(command_id) and valid_operation_payload?(name, payload),
       do:
         {:ok,
          {:operation,
           %{command_id: command_id, name: @client_operations[name], payload: payload}}},
       else: {:error, :invalid_operation}
  end

  defp decode_operation(_frame), do: {:error, :invalid_operation}

  defp valid_operation_payload?(
         "admit_participant",
         %{"admission_request_id" => admission_request_id} = payload
       ) do
    exact_keys?(payload, ["admission_request_id"]) and valid_uuid?(admission_request_id)
  end

  defp valid_operation_payload?(
         "deny_admission",
         %{"admission_request_id" => admission_request_id} = payload
       ) do
    exact_keys?(payload, ["admission_request_id"]) and valid_uuid?(admission_request_id)
  end

  defp valid_operation_payload?(
         "mute_participant",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_operation_payload?(
         "stop_participant_camera",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_operation_payload?(
         "stop_participant_screen_share",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_operation_payload?(
         "remove_participant",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_operation_payload?("start_recording", %{"recording_id" => recording_id} = payload) do
    exact_keys?(payload, ["recording_id"]) and valid_uuid?(recording_id)
  end

  defp valid_operation_payload?("stop_recording", %{"recording_id" => recording_id} = payload) do
    exact_keys?(payload, ["recording_id"]) and valid_uuid?(recording_id)
  end

  defp valid_operation_payload?("participant_leave", %{} = payload) do
    exact_keys?(payload, []) and true
  end

  defp valid_operation_payload?("start_episode", %{} = payload) do
    exact_keys?(payload, []) and true
  end

  defp valid_operation_payload?(
         "extend_episode",
         %{"extension_seconds" => extension_seconds} = payload
       ) do
    exact_keys?(payload, ["extension_seconds"]) and valid_positive_integer?(extension_seconds)
  end

  defp valid_operation_payload?("end_episode", %{} = payload) do
    exact_keys?(payload, []) and true
  end

  defp valid_operation_payload?(_name, _payload), do: false

  defp decode_live_target(
         %{"operation_id" => operation_id, "name" => name, "enabled" => enabled} = frame
       ) do
    if exact_keys?(frame, ["type", "operation_id", "name", "enabled"]) and
         valid_request_id?(operation_id) and name in @live_target_names and is_boolean(enabled),
       do: {:ok, {:live_target, %{operation_id: operation_id, name: name, enabled: enabled}}},
       else: {:error, :invalid_live_target}
  end

  defp decode_live_target(_frame), do: {:error, :invalid_live_target}

  defp decode_directed_request(
         %{"request_id" => request_id, "name" => name, "target_participant_id" => target_id} =
           frame
       ) do
    if exact_keys?(frame, ["type", "request_id", "name", "target_participant_id"]) and
         valid_request_id?(request_id) and name in @directed_request_names and
         valid_uuid?(target_id),
       do:
         {:ok,
          {:directed_request,
           %{request_id: request_id, name: name, target_participant_id: target_id}}},
       else: {:error, :invalid_directed_request}
  end

  defp decode_directed_request(_frame), do: {:error, :invalid_directed_request}

  defp decode_request_ack(%{"request_id" => request_id} = frame) do
    if exact_keys?(frame, ["type", "request_id"]) and valid_request_id?(request_id),
      do: {:ok, {:request_ack, request_id}},
      else: {:error, :invalid_request_ack}
  end

  defp decode_request_ack(_frame), do: {:error, :invalid_request_ack}

  defp decode_reaction_send(%{"operation_id" => operation_id, "reaction" => reaction} = frame) do
    if exact_keys?(frame, ["type", "operation_id", "reaction"]) and
         valid_request_id?(operation_id) and reaction in @reactions,
       do: {:ok, {:reaction_send, %{operation_id: operation_id, reaction: reaction}}},
       else: {:error, :invalid_reaction}
  end

  defp decode_reaction_send(_frame), do: {:error, :invalid_reaction}

  defp decode_chat_send(
         %{
           "client_message_id" => client_message_id,
           "text" => text,
           "attachment_ids" => attachment_ids
         } = frame
       ) do
    if exact_keys?(frame, ["type", "client_message_id", "text", "attachment_ids"]) and
         valid_request_id?(client_message_id) and valid_v2_chat_content?(text, attachment_ids),
       do:
         {:ok,
          {:chat_send,
           %{client_message_id: client_message_id, text: text, attachment_ids: attachment_ids}}},
       else: {:error, :invalid_chat_message}
  end

  defp decode_chat_send(_frame), do: {:error, :invalid_chat_message}

  defp decode_chat_page_request(
         %{
           "request_id" => request_id,
           "direction" => direction,
           "cursor_sequence" => cursor,
           "limit" => limit
         } = frame
       ) do
    if exact_keys?(frame, ["type", "request_id", "direction", "cursor_sequence", "limit"]) and
         valid_request_id?(request_id) and direction in ["older", "newer"] and
         valid_nullable_unsigned_decimal?(cursor) and valid_positive_integer?(limit) and
         limit <= @limits["chatPageMaxMessages"],
       do:
         {:ok,
          {:chat_page_request,
           %{request_id: request_id, direction: direction, cursor_sequence: cursor, limit: limit}}},
       else: {:error, :invalid_chat_page_request}
  end

  defp decode_chat_page_request(_frame), do: {:error, :invalid_chat_page_request}

  defp decode_chat_read_set(%{"request_id" => request_id, "sequence" => sequence} = frame) do
    if exact_keys?(frame, ["type", "request_id", "sequence"]) and valid_request_id?(request_id) and
         valid_unsigned_decimal?(sequence),
       do: {:ok, {:chat_read_set, %{request_id: request_id, sequence: sequence}}},
       else: {:error, :invalid_chat_read}
  end

  defp decode_chat_read_set(_frame), do: {:error, :invalid_chat_read}

  defp decode_delivery_ack(
         %{"stream" => "control", "revision" => revision, "state_digest" => digest} = frame
       ) do
    if exact_keys?(frame, ["type", "stream", "revision", "state_digest"]) and
         valid_positive_integer?(revision) and valid_digest?(digest),
       do: {:ok, {:delivery_ack, %{stream: :control, revision: revision, state_digest: digest}}},
       else: {:error, :invalid_delivery_ack}
  end

  defp decode_delivery_ack(_frame), do: {:error, :invalid_delivery_ack}

  defp decode_recovery_ack(
         %{"recovery_id" => recovery_id, "revision" => revision, "state_digest" => digest} = frame
       ) do
    if exact_keys?(frame, ["type", "recovery_id", "revision", "state_digest"]) and
         valid_uuid?(recovery_id) and valid_non_negative_integer?(revision) and
         valid_digest?(digest),
       do:
         {:ok,
          {:recovery_ack, %{recovery_id: recovery_id, revision: revision, state_digest: digest}}},
       else: {:error, :invalid_recovery_ack}
  end

  defp decode_recovery_ack(_frame), do: {:error, :invalid_recovery_ack}

  @spec valid_server_frame?(map()) :: boolean()
  def valid_server_frame?(%{"type" => "welcome"} = frame), do: valid_welcome?(frame)
  def valid_server_frame?(%{"type" => "replay_page"} = frame), do: valid_replay_page?(frame)

  def valid_server_frame?(%{"type" => "recovery_complete"} = frame),
    do:
      correlation_exact_keys?(frame, ["type", "recovery_id", "head"]) and
        valid_uuid?(frame["recovery_id"]) and valid_cursor?(frame["head"])

  def valid_server_frame?(%{"type" => "event"} = frame),
    do:
      valid_event?(frame) and server_frame_within_limit?(frame, @limits["encodedLiveEventBytes"])

  def valid_server_frame?(%{"type" => "ack"} = frame), do: valid_ack?(frame)

  def valid_server_frame?(%{"type" => type} = frame)
      when type in ["projection_snapshot", "projection_event"], do: valid_projection?(frame)

  def valid_server_frame?(%{"type" => "live_target_result"} = frame),
    do: valid_live_target_result?(frame)

  def valid_server_frame?(%{"type" => "directed_request"} = frame),
    do: valid_directed_request_delivery?(frame)

  def valid_server_frame?(%{"type" => "directed_request_result"} = frame),
    do: valid_directed_request_result?(frame)

  def valid_server_frame?(%{"type" => "reaction"} = frame),
    do:
      valid_reaction?(frame) and
        server_frame_within_limit?(frame, @limits["collaborationFrameBytes"])

  def valid_server_frame?(%{"type" => "reaction_result"} = frame),
    do: valid_reaction_result?(frame)

  def valid_server_frame?(%{"type" => "chat_message"} = frame),
    do:
      valid_chat_message?(frame) and
        server_frame_within_limit?(frame, @limits["collaborationFrameBytes"])

  def valid_server_frame?(%{"type" => "chat_send_result"} = frame),
    do: valid_chat_send_result?(frame)

  def valid_server_frame?(%{"type" => "chat_page"} = frame), do: valid_chat_page?(frame)
  def valid_server_frame?(%{"type" => "chat_head"} = frame), do: valid_chat_head?(frame)

  def valid_server_frame?(%{"type" => "chat_read_receipt"} = frame),
    do: valid_chat_read_receipt?(frame)

  def valid_server_frame?(%{"type" => "chat_read_result"} = frame),
    do: valid_chat_read_result?(frame)

  def valid_server_frame?(
        %{"type" => "retryable_error", "command_id" => id, "code" => code} = frame
      ),
      do:
        correlation_exact_keys?(frame, ["type", "command_id", "code"]) and valid_command_id?(id) and
          code in @retryable_codes

  def valid_server_frame?(%{"type" => "error", "code" => code, "detail" => detail} = frame),
    do:
      correlation_exact_keys?(frame, ["type", "code", "detail"]) and code in @protocol_error_codes and
        bounded_string?(detail, 0, @limits["protocolErrorDetailBytes"])

  def valid_server_frame?(%{"type" => "pong"} = frame),
    do: correlation_exact_keys?(frame, ["type"])

  def valid_server_frame?(_frame), do: false

  defp valid_streams?(
         %{"control" => control, "media" => media, "presence" => presence, "requests" => requests} =
           streams
       ) do
    exact_keys?(streams, ["control", "media", "presence", "requests"]) and
      exact_keys?(control, ["cursor"]) and valid_cursor?(control["cursor"]) and
      Enum.all?(
        [media, presence, requests],
        &(exact_keys?(&1, ["cursor"]) and &1["cursor"] == nil)
      )
  end

  defp valid_streams?(_streams), do: false

  defp valid_collaborations_hello_extensions?([
         %{"name" => name, "chat_cursor" => cursor} = extension
       ])
       when name == "collaboration_v1" do
    exact_keys?(extension, ["name", "chat_cursor"]) and valid_chat_cursor?(cursor)
  end

  defp valid_collaborations_hello_extensions?(_extensions), do: false

  defp valid_welcome?(
         %{
           "protocol" => @protocol_version,
           "participant_id" => participant_id,
           "participant_generation" => generation,
           "recovery_id" => recovery_id,
           "head" => head,
           "mode" => mode
         } = frame
       ) do
    base = [
      "type",
      "protocol",
      "participant_id",
      "participant_generation",
      "recovery_id",
      "head",
      "mode"
    ]

    base = if Map.has_key?(frame, "extensions"), do: base ++ ["extensions"], else: base

    valid_extensions =
      not Map.has_key?(frame, "extensions") or
        valid_collaborations_welcome_extensions?(frame["extensions"])

    valid_base =
      valid_uuid?(participant_id) and valid_positive_integer?(generation) and
        valid_uuid?(recovery_id) and valid_cursor?(head) and valid_extensions

    case mode do
      "snapshot" ->
        correlation_exact_keys?(frame, base ++ ["snapshot"]) and valid_base and
          valid_snapshot?(frame["snapshot"]) and
          server_frame_within_limit?(frame, @limits["snapshotEncodedBytes"])

      mode when mode in ["replay", "up_to_date"] ->
        correlation_exact_keys?(frame, base) and valid_base

      "terminal" ->
        correlation_exact_keys?(frame, base ++ ["reason"]) and valid_base and
          frame["reason"] in @terminal_reasons

      _ ->
        false
    end
  end

  defp valid_welcome?(_frame), do: false

  defp valid_collaborations_welcome_extensions?([
         %{
           "name" => "collaboration_v1",
           "capabilities" => capabilities,
           "participant_capabilities" => participant_capabilities,
           "chat_head_sequence" => head,
           "retained_floor_sequence" => floor,
           "read_receipts" => receipts
         } = extension
       ]) do
    exact_keys?(extension, [
      "name",
      "capabilities",
      "participant_capabilities",
      "chat_head_sequence",
      "retained_floor_sequence",
      "read_receipts"
    ]) and valid_collaboration_capabilities?(capabilities) and is_map(participant_capabilities) and
      Enum.all?(participant_capabilities, fn {participant_id, values} ->
        valid_uuid?(participant_id) and valid_collaboration_capabilities?(values)
      end) and valid_nullable_unsigned_decimal?(head) and valid_nullable_unsigned_decimal?(floor) and
      is_list(receipts) and length(receipts) <= 500 and
      Enum.all?(receipts, &valid_chat_read_receipt_body?/1)
  end

  defp valid_collaborations_welcome_extensions?(_extensions), do: false

  defp valid_collaboration_capabilities?(capabilities),
    do:
      unique_list?(capabilities) and length(capabilities) <= 2 and
        Enum.all?(capabilities, &(&1 in @collaboration_capabilities))

  defp valid_snapshot?(
         %{
           "participants" => participants,
           "admission_requests" => requests,
           "role_capabilities" => role_capabilities
         } = snapshot
       ) do
    exact_keys?(snapshot, [
      "control_revision",
      "state_schema_version",
      "state_digest",
      "status",
      "admission_policy",
      "deadline_at_ms",
      "deadline_generation",
      "role_capabilities",
      "recording",
      "participants",
      "admission_requests"
    ]) and
      valid_non_negative_integer?(snapshot["control_revision"]) and
      valid_positive_integer?(snapshot["state_schema_version"]) and
      valid_digest?(snapshot["state_digest"]) and
      snapshot["status"] in ["active", "ended"] and
      snapshot["admission_policy"] in ["open", "knock", "members_only"] and
      valid_positive_integer?(snapshot["deadline_at_ms"]) and
      valid_positive_integer?(snapshot["deadline_generation"]) and
      valid_role_capabilities?(role_capabilities) and valid_recording?(snapshot["recording"]) and
      is_list(participants) and length(participants) <= 500 and
      Enum.all?(participants, &valid_participant?(&1, role_capabilities)) and
      is_list(requests) and length(requests) <= 500 and
      Enum.all?(requests, &valid_admission_request?(&1, role_capabilities)) and
      valid_snapshot_collections?(
        snapshot["status"],
        participants,
        requests,
        snapshot["recording"]
      ) and frame_within_limit?(snapshot, @limits["snapshotEncodedBytes"])
  end

  defp valid_snapshot?(_snapshot), do: false

  defp valid_participant?(
         %{
           "participant_id" => id,
           "display_name" => name,
           "hand_raised" => raised,
           "admission_revision" => admission_revision,
           "role" => role,
           "capabilities" => capabilities
         } = participant,
         role_capabilities
       ) do
    exact_keys?(participant, [
      "participant_id",
      "display_name",
      "hand_raised",
      "admission_revision",
      "role",
      "capabilities"
    ]) and valid_uuid?(id) and bounded_string?(name, 1, 256) and is_boolean(raised) and
      valid_positive_integer?(admission_revision) and bounded_string?(role, 1, 64) and
      capabilities == Map.get(role_capabilities, role)
  end

  defp valid_participant?(_participant, _role_capabilities), do: false

  defp valid_admission_request?(
         %{
           "admission_request_id" => request_id,
           "participant_id" => participant_id,
           "display_name" => name,
           "role" => role,
           "expires_at_ms" => expires_at
         } = request,
         role_capabilities
       ),
       do:
         exact_keys?(request, [
           "admission_request_id",
           "participant_id",
           "display_name",
           "role",
           "expires_at_ms"
         ]) and valid_uuid?(request_id) and valid_uuid?(participant_id) and
           bounded_string?(name, 1, 256) and bounded_string?(role, 1, 64) and
           Map.has_key?(role_capabilities, role) and valid_positive_integer?(expires_at)

  defp valid_admission_request?(_request, _role_capabilities), do: false

  defp valid_role_capabilities?(roles) when is_map(roles),
    do:
      map_size(roles) > 0 and
        Enum.all?(roles, fn {role, values} ->
          bounded_string?(role, 1, 64) and is_list(values) and unique_list?(values) and
            length(values) <= 23 and Enum.all?(values, &(&1 in @capabilities))
        end)

  defp valid_role_capabilities?(_roles), do: false
  defp valid_recording?(nil), do: true

  defp valid_recording?(
         %{"recording_id" => id, "status" => status, "failure_code" => failure_code} = recording
       ),
       do:
         exact_keys?(recording, ["recording_id", "status", "failure_code"]) and valid_uuid?(id) and
           status in ["starting", "recording", "stopping", "stopped", "failed"] and
           (is_nil(failure_code) or bounded_string?(failure_code, 1, 96)) and
           status == "failed" == not is_nil(failure_code)

  defp valid_recording?(_recording), do: false

  defp valid_snapshot_collections?(status, participants, requests, recording) do
    participant_ids = Enum.map(participants, & &1["participant_id"])
    request_ids = Enum.map(requests, & &1["admission_request_id"])
    candidate_ids = Enum.map(requests, & &1["participant_id"])

    unique_list?(participant_ids) and unique_list?(request_ids) and unique_list?(candidate_ids) and
      MapSet.disjoint?(MapSet.new(participant_ids), MapSet.new(candidate_ids)) and
      valid_snapshot_state?(status, participants, requests, recording)
  end

  defp valid_snapshot_state?("ended", participants, requests, recording),
    do: participants == [] and requests == [] and is_nil(recording)

  defp valid_snapshot_state?("active", _participants, _requests, _recording), do: true
  defp valid_snapshot_state?(_status, _participants, _requests, _recording), do: false

  defp unique_list?(value) when is_list(value),
    do: MapSet.size(MapSet.new(value)) == length(value)

  defp unique_list?(_value), do: false

  defp valid_event?(
         %{
           "name" => name,
           "event_id" => event_id,
           "base_revision" => base_revision,
           "revision" => revision,
           "schema_version" => schema_version,
           "resulting_state_digest" => digest,
           "payload" => payload
         } = frame
       ) do
    common = [
      "type",
      "stream",
      "name",
      "event_id",
      "base_revision",
      "revision",
      "schema_version",
      "resulting_state_digest",
      "payload"
    ]

    origin = Map.get(@event_origins, name)

    origin_keys =
      if origin == "command_or_external",
        do: ["command_id", "external_operation_id"],
        else: [
          if(origin == "command",
            do: "command_id",
            else:
              if(origin == "lifecycle", do: "lifecycle_intent_id", else: "external_operation_id")
          )
        ]

    Enum.any?(origin_keys, fn key ->
      correlation_exact_keys?(frame, common ++ [key]) and valid_origin_id?(key, frame[key])
    end) and frame["stream"] == "control" and valid_uuid?(event_id) and
      valid_revision_pair?(base_revision, revision) and valid_positive_integer?(schema_version) and
      valid_digest?(digest) and valid_event_payload?(name, payload) and
      frame_within_limit?(frame, @limits["encodedLiveEventBytes"])
  end

  defp valid_event?(_frame), do: false
  defp valid_origin_id?("command_id", id), do: valid_command_id?(id)
  defp valid_origin_id?(_key, id), do: valid_uuid?(id)

  defp valid_event_payload?(
         "participant_joined",
         %{
           "participant_id" => participant_id,
           "display_name" => display_name,
           "role" => role,
           "admission_revision" => admission_revision
         } = payload
       ) do
    exact_keys?(payload, ["participant_id", "display_name", "role", "admission_revision"]) and
      valid_uuid?(participant_id) and bounded_string?(display_name, 1, 256) and
      bounded_string?(role, 1, 64) and role != "" and role == String.trim(role) and
      valid_positive_integer?(admission_revision)
  end

  defp valid_event_payload?(
         "participant_left",
         %{"participant_id" => participant_id, "reason" => reason} = payload
       ) do
    exact_keys?(payload, ["participant_id", "reason"]) and valid_uuid?(participant_id) and
      reason in ["left", "removed"]
  end

  defp valid_event_payload?("episode_started", %{"episode_id" => episode_id} = payload) do
    exact_keys?(payload, ["episode_id"]) and valid_uuid?(episode_id)
  end

  defp valid_event_payload?("episode_ended", %{"reason" => reason} = payload) do
    exact_keys?(payload, ["reason"]) and
      reason in ["ended_by_participant", "tenant_recovery", "maximum_duration"]
  end

  defp valid_event_payload?("hand_raised", %{"participant_id" => participant_id} = payload) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_event_payload?("hand_lowered", %{"participant_id" => participant_id} = payload) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_event_payload?(
         "participant_display_name_changed",
         %{"participant_id" => participant_id, "display_name" => display_name} = payload
       ) do
    exact_keys?(payload, ["participant_id", "display_name"]) and valid_uuid?(participant_id) and
      bounded_string?(display_name, 1, 256)
  end

  defp valid_event_payload?("admission_policy_changed", %{"policy" => policy} = payload) do
    exact_keys?(payload, ["policy"]) and policy in ["open", "knock", "members_only"]
  end

  defp valid_event_payload?(
         "role_assigned",
         %{"participant_id" => participant_id, "role" => role} = payload
       ) do
    exact_keys?(payload, ["participant_id", "role"]) and valid_uuid?(participant_id) and
      bounded_string?(role, 1, 64) and role != "" and role == String.trim(role)
  end

  defp valid_event_payload?(
         "deadline_changed",
         %{"deadline_at_ms" => deadline_at_ms, "deadline_generation" => deadline_generation} =
           payload
       ) do
    exact_keys?(payload, ["deadline_at_ms", "deadline_generation"]) and
      valid_positive_integer?(deadline_at_ms) and valid_positive_integer?(deadline_generation)
  end

  defp valid_event_payload?(
         "admission_requested",
         %{
           "admission_request_id" => admission_request_id,
           "participant_id" => participant_id,
           "display_name" => display_name,
           "role" => role,
           "expires_at_ms" => expires_at_ms
         } = payload
       ) do
    exact_keys?(payload, [
      "admission_request_id",
      "participant_id",
      "display_name",
      "role",
      "expires_at_ms"
    ]) and valid_uuid?(admission_request_id) and valid_uuid?(participant_id) and
      bounded_string?(display_name, 1, 256) and bounded_string?(role, 1, 64) and role != "" and
      role == String.trim(role) and valid_positive_integer?(expires_at_ms)
  end

  defp valid_event_payload?(
         "admission_denied",
         %{"admission_request_id" => admission_request_id} = payload
       ) do
    exact_keys?(payload, ["admission_request_id"]) and valid_uuid?(admission_request_id)
  end

  defp valid_event_payload?(
         "admission_expired",
         %{"admission_request_id" => admission_request_id} = payload
       ) do
    exact_keys?(payload, ["admission_request_id"]) and valid_uuid?(admission_request_id)
  end

  defp valid_event_payload?(
         "participant_microphone_stopped",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_event_payload?(
         "participant_camera_stopped",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_event_payload?(
         "participant_screen_share_stopped",
         %{"participant_id" => participant_id} = payload
       ) do
    exact_keys?(payload, ["participant_id"]) and valid_uuid?(participant_id)
  end

  defp valid_event_payload?(
         "recording_status_changed",
         %{"recording_id" => recording_id, "status" => status, "failure_code" => failure_code} =
           payload
       ) do
    exact_keys?(payload, ["recording_id", "status", "failure_code"]) and valid_uuid?(recording_id) and
      status in ["starting", "recording", "stopping", "stopped", "failed"] and
      (is_nil(failure_code) or bounded_string?(failure_code, 1, 96))
  end

  defp valid_event_payload?(_name, _payload), do: false

  defp valid_replay_page?(
         %{
           "recovery_id" => recovery_id,
           "first_revision" => first_revision,
           "last_revision" => last_revision,
           "events" => events
         } = frame
       ) do
    correlation_exact_keys?(frame, [
      "type",
      "recovery_id",
      "first_revision",
      "last_revision",
      "events"
    ]) and valid_uuid?(recovery_id) and is_list(events) and
      length(events) <= @limits["replayPageMaxEvents"] and
      server_frame_within_limit?(frame, @limits["replayPageEncodedBytes"]) and
      valid_replay_range?(events, first_revision, last_revision)
  end

  defp valid_replay_page?(_frame), do: false
  defp valid_replay_range?([], _first, _last), do: false

  defp valid_replay_range?([first | rest], first_revision, last_revision) do
    valid_event?(first) and first["revision"] == first_revision and
      Enum.reduce_while(rest, first, fn event, previous ->
        if valid_event?(event) and event["base_revision"] == previous["revision"],
          do: {:cont, event},
          else: {:halt, false}
      end)
      |> case do
        false -> false
        last -> last["revision"] == last_revision
      end
  end

  defp valid_ack?(
         %{
           "outcome" => "committed",
           "command_id" => id,
           "delivery" => delivery,
           "event_id" => event_id,
           "revision" => revision,
           "state_digest" => digest
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "command_id",
           "delivery",
           "outcome",
           "event_id",
           "revision",
           "state_digest"
         ]) and valid_ack_base?(id, delivery) and valid_uuid?(event_id) and
           valid_positive_integer?(revision) and valid_digest?(digest)

  defp valid_ack?(
         %{
           "outcome" => "satisfied",
           "command_id" => id,
           "delivery" => delivery,
           "revision" => revision,
           "state_digest" => digest
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "command_id",
           "delivery",
           "outcome",
           "revision",
           "state_digest"
         ]) and valid_ack_base?(id, delivery) and valid_non_negative_integer?(revision) and
           valid_digest?(digest)

  defp valid_ack?(
         %{"outcome" => outcome, "command_id" => id, "delivery" => delivery, "reason" => reason} =
           frame
       )
       when outcome in ["rejected", "command_id_conflict"],
       do:
         correlation_exact_keys?(frame, ["type", "command_id", "delivery", "outcome", "reason"]) and
           valid_ack_base?(id, delivery) and reason in @rejection_reasons and
           (outcome != "command_id_conflict" or reason == "command_id_conflict")

  defp valid_ack?(_frame), do: false

  defp valid_ack_base?(id, delivery),
    do: valid_command_id?(id) and delivery in ["original", "duplicate"]

  defp valid_projection?(
         %{
           "type" => "projection_snapshot",
           "stream" => stream,
           "projection_id" => projection_id,
           "sequence" => 0,
           "items" => items
         } = frame
       ) do
    correlation_exact_keys?(frame, ["type", "stream", "projection_id", "sequence", "items"]) and
      valid_uuid?(projection_id) and is_list(items) and
      length(items) <= projection_item_limit(stream) and
      Enum.all?(items, &valid_projection_item?(stream, &1)) and
      server_frame_within_limit?(frame, @limits["projectionSnapshotEncodedBytes"])
  end

  defp valid_projection?(
         %{
           "type" => "projection_event",
           "stream" => stream,
           "projection_id" => projection_id,
           "sequence" => sequence,
           "item" => item
         } = frame
       ) do
    correlation_exact_keys?(frame, ["type", "stream", "projection_id", "sequence", "item"]) and
      valid_uuid?(projection_id) and valid_positive_integer?(sequence) and
      valid_projection_item?(stream, item) and
      server_frame_within_limit?(frame, @limits["encodedLiveEventBytes"])
  end

  defp valid_projection?(_frame), do: false
  defp projection_item_limit("media"), do: 1_500
  defp projection_item_limit("presence"), do: 500
  defp projection_item_limit(_stream), do: -1

  defp valid_projection_item?(
         "media",
         %{
           "participant_id" => id,
           "source" => source,
           "enabled" => enabled,
           "publication_id" => publication_id
         } = item
       ),
       do:
         exact_keys?(item, ["participant_id", "source", "enabled", "publication_id"]) and
           valid_uuid?(id) and source in @media_sources and is_boolean(enabled) and
           (is_nil(publication_id) or bounded_string?(publication_id, 1, 256)) and
           enabled == not is_nil(publication_id)

  defp valid_projection_item?(
         "presence",
         %{
           "participant_id" => id,
           "state" => state,
           "speaking" => speaking,
           "active_speaker" => active
         } = item
       ),
       do:
         exact_keys?(item, ["participant_id", "state", "speaking", "active_speaker"]) and
           valid_uuid?(id) and state in @presence_states and is_boolean(speaking) and
           is_boolean(active) and (state != "disconnected" or (not speaking and not active))

  defp valid_projection_item?(_stream, _item), do: false

  defp valid_live_target_result?(
         %{"operation_id" => id, "name" => name, "outcome" => outcome, "error_code" => error_code} =
           frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "operation_id", "name", "outcome", "error_code"]) and
           valid_request_id?(id) and name in @live_target_names and
           outcome in @live_target_outcomes and
           (is_nil(error_code) or
              bounded_string?(error_code, 1, @limits["protocolErrorDetailBytes"]))

  defp valid_live_target_result?(_frame), do: false

  defp valid_directed_request_delivery?(
         %{
           "request_id" => id,
           "name" => name,
           "actor_participant_id" => actor_id,
           "expires_at_ms" => expires_at
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "request_id",
           "name",
           "actor_participant_id",
           "expires_at_ms"
         ]) and valid_request_id?(id) and name in @directed_request_names and
           valid_uuid?(actor_id) and valid_positive_integer?(expires_at)

  defp valid_directed_request_delivery?(_frame), do: false

  defp valid_directed_request_result?(%{"request_id" => id, "result" => result} = frame),
    do:
      correlation_exact_keys?(frame, ["type", "request_id", "result"]) and valid_request_id?(id) and
        result in @directed_request_results

  defp valid_directed_request_result?(_frame), do: false

  defp valid_reaction?(
         %{
           "event_id" => event_id,
           "participant_id" => participant_id,
           "display_name" => display_name,
           "reaction" => reaction,
           "occurred_at" => occurred_at,
           "expires_at" => expires_at
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "event_id",
           "participant_id",
           "display_name",
           "reaction",
           "occurred_at",
           "expires_at"
         ]) and valid_uuid?(event_id) and valid_uuid?(participant_id) and
           bounded_string?(display_name, 1, 256) and reaction in @reactions and
           valid_iso_timestamp?(occurred_at) and valid_iso_timestamp?(expires_at) and
           frame_within_limit?(frame, @limits["collaborationFrameBytes"])

  defp valid_reaction?(_frame), do: false

  defp valid_reaction_result?(
         %{"outcome" => "accepted", "operation_id" => operation_id, "reaction" => reaction} =
           frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "operation_id", "outcome", "reaction"]) and
           valid_request_id?(operation_id) and valid_reaction?(reaction)

  defp valid_reaction_result?(
         %{"outcome" => "rejected", "operation_id" => operation_id, "error_code" => error_code} =
           frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "operation_id", "outcome", "error_code"]) and
           valid_request_id?(operation_id) and error_code in @collaboration_error_codes

  defp valid_reaction_result?(_frame), do: false

  defp valid_chat_message?(
         %{
           "message_id" => message_id,
           "client_message_id" => client_message_id,
           "sequence" => sequence,
           "participant_id" => participant_id,
           "display_name" => display_name,
           "text" => text,
           "attachments" => attachments,
           "created_at" => created_at
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "message_id",
           "client_message_id",
           "sequence",
           "participant_id",
           "display_name",
           "text",
           "attachments",
           "created_at"
         ]) and valid_uuid?(message_id) and valid_request_id?(client_message_id) and
           valid_unsigned_decimal?(sequence) and valid_uuid?(participant_id) and
           bounded_string?(display_name, 1, 256) and is_list(attachments) and
           valid_v2_chat_content?(text, Enum.map(attachments, & &1["attachment_id"])) and
           Enum.all?(attachments, &valid_chat_attachment?/1) and valid_iso_timestamp?(created_at) and
           frame_within_limit?(frame, @limits["collaborationFrameBytes"])

  defp valid_chat_message?(_frame), do: false

  defp valid_chat_attachment?(
         %{
           "attachment_id" => id,
           "file_name" => file_name,
           "mime_type" => mime_type,
           "byte_length" => byte_length
         } = attachment
       ),
       do:
         exact_keys?(attachment, ["attachment_id", "file_name", "mime_type", "byte_length"]) and
           valid_uuid?(id) and
           bounded_string?(file_name, 1, @limits["chatAttachmentFileNameUtf8Bytes"]) and
           mime_type in [
             "image/png",
             "image/jpeg",
             "image/gif",
             "image/webp",
             "application/pdf",
             "text/plain",
             "application/msword",
             "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
             "application/vnd.ms-excel",
             "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "application/vnd.ms-powerpoint",
             "application/vnd.openxmlformats-officedocument.presentationml.presentation",
             "application/vnd.oasis.opendocument.text",
             "application/vnd.oasis.opendocument.spreadsheet",
             "application/vnd.oasis.opendocument.presentation"
           ] and valid_positive_integer?(byte_length) and
           byte_length <= @limits["chatAttachmentMaxBytes"]

  defp valid_chat_attachment?(_attachment), do: false

  defp valid_chat_send_result?(
         %{
           "outcome" => "accepted",
           "client_message_id" => client_message_id,
           "message" => message
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "client_message_id", "outcome", "message"]) and
           valid_request_id?(client_message_id) and valid_chat_message?(message)

  defp valid_chat_send_result?(
         %{
           "outcome" => "rejected",
           "client_message_id" => client_message_id,
           "error_code" => error_code
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "client_message_id", "outcome", "error_code"]) and
           valid_request_id?(client_message_id) and error_code in @collaboration_error_codes

  defp valid_chat_send_result?(_frame), do: false

  defp valid_chat_page?(
         %{
           "outcome" => "loaded",
           "request_id" => request_id,
           "messages" => messages,
           "has_more" => has_more,
           "head_sequence" => head,
           "retained_floor_sequence" => floor
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "request_id",
           "outcome",
           "messages",
           "has_more",
           "head_sequence",
           "retained_floor_sequence"
         ]) and valid_request_id?(request_id) and is_list(messages) and
           length(messages) <= @limits["chatPageMaxMessages"] and
           Enum.all?(messages, &valid_chat_message?/1) and is_boolean(has_more) and
           valid_nullable_unsigned_decimal?(head) and valid_nullable_unsigned_decimal?(floor) and
           server_frame_within_limit?(frame, @limits["chatPageEncodedBytes"])

  defp valid_chat_page?(
         %{
           "outcome" => "cursor_reset",
           "request_id" => request_id,
           "retained_floor_sequence" => floor
         } = frame
       ),
       do:
         correlation_exact_keys?(frame, [
           "type",
           "request_id",
           "outcome",
           "retained_floor_sequence"
         ]) and valid_request_id?(request_id) and valid_unsigned_decimal?(floor)

  defp valid_chat_page?(_frame), do: false

  defp valid_chat_head?(%{"head_sequence" => head, "retained_floor_sequence" => floor} = frame),
    do:
      correlation_exact_keys?(frame, ["type", "head_sequence", "retained_floor_sequence"]) and
        valid_nullable_unsigned_decimal?(head) and valid_nullable_unsigned_decimal?(floor)

  defp valid_chat_head?(_frame), do: false

  defp valid_chat_read_receipt?(%{"type" => "chat_read_receipt"} = frame),
    do:
      correlation_exact_keys?(frame, [
        "type",
        "participant_id",
        "participant_generation",
        "sequence",
        "read_at"
      ]) and valid_chat_read_receipt_body?(Map.drop(frame, ["type" | @correlation_field_keys]))

  defp valid_chat_read_receipt?(_frame), do: false

  defp valid_chat_read_receipt_body?(
         %{
           "participant_id" => participant_id,
           "participant_generation" => generation,
           "sequence" => sequence,
           "read_at" => read_at
         } = receipt
       ),
       do:
         exact_keys?(receipt, ["participant_id", "participant_generation", "sequence", "read_at"]) and
           valid_uuid?(participant_id) and valid_positive_integer?(generation) and
           valid_unsigned_decimal?(sequence) and valid_iso_timestamp?(read_at)

  defp valid_chat_read_receipt_body?(_receipt), do: false

  defp valid_chat_read_result?(%{"outcome" => "accepted", "request_id" => request_id} = frame),
    do:
      correlation_exact_keys?(frame, [
        "type",
        "request_id",
        "outcome",
        "participant_id",
        "participant_generation",
        "sequence",
        "read_at"
      ]) and valid_request_id?(request_id) and
        valid_chat_read_receipt_body?(
          Map.drop(frame, ["type", "request_id", "outcome" | @correlation_field_keys])
        )

  defp valid_chat_read_result?(
         %{"outcome" => "rejected", "request_id" => request_id, "error_code" => error_code} =
           frame
       ),
       do:
         correlation_exact_keys?(frame, ["type", "request_id", "outcome", "error_code"]) and
           valid_request_id?(request_id) and error_code in @collaboration_error_codes

  defp valid_chat_read_result?(_frame), do: false

  defp valid_chat_cursor?(
         %{"after_sequence" => after_sequence, "retained_floor_sequence" => floor} = cursor
       ),
       do:
         exact_keys?(cursor, ["after_sequence", "retained_floor_sequence"]) and
           valid_nullable_unsigned_decimal?(after_sequence) and
           valid_nullable_unsigned_decimal?(floor)

  defp valid_chat_cursor?(_cursor), do: false
  defp valid_nullable_unsigned_decimal?(nil), do: true
  defp valid_nullable_unsigned_decimal?(value), do: valid_unsigned_decimal?(value)
  defp valid_unsigned_decimal?(value), do: is_binary(value) and value =~ ~r/\A(?:0|[1-9][0-9]*)\z/

  defp valid_v2_chat_content?(text, attachment_ids),
    do:
      bounded_string?(text, 0, @limits["chatMessageUtf8Bytes"]) and
        String.length(text) <= @limits["chatMessageUnicodeScalars"] and is_list(attachment_ids) and
        length(attachment_ids) <= @limits["chatAttachmentMaxItems"] and
        unique_list?(attachment_ids) and Enum.all?(attachment_ids, &valid_uuid?/1) and
        (text != "" or attachment_ids != [])

  defp valid_iso_timestamp?(value), do: bounded_string?(value, 1, 64)

  defp valid_cursor?(nil), do: true

  defp valid_cursor?(
         %{"revision" => revision, "state_schema_version" => version, "state_digest" => digest} =
           cursor
       ),
       do:
         exact_keys?(cursor, ["revision", "state_schema_version", "state_digest"]) and
           valid_non_negative_integer?(revision) and valid_positive_integer?(version) and
           valid_digest?(digest)

  defp valid_cursor?(_cursor), do: false
  defp valid_token?(value), do: bounded_string?(value, 0, @limits["tokenBytes"])

  defp valid_command_id?(value),
    do: bounded_string?(value, @limits["commandIdMinBytes"], @limits["commandIdMaxBytes"])

  defp valid_request_id?(value),
    do: bounded_string?(value, @limits["requestIdMinBytes"], @limits["requestIdMaxBytes"])

  defp bounded_string?(value, minimum, maximum),
    do: is_binary(value) and byte_size(value) >= minimum and byte_size(value) <= maximum

  defp valid_uuid?(value), do: is_binary(value) and value =~ @uuid
  defp valid_digest?(value), do: is_binary(value) and value =~ @digest
  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0
  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1

  defp valid_revision_pair?(base, revision),
    do: valid_non_negative_integer?(base) and revision == base + 1

  defp valid_correlation_fields?(frame) when is_map(frame),
    do:
      Enum.all?(@correlation_field_keys, fn key ->
        not Map.has_key?(frame, key) or valid_correlation_field?(key, frame[key])
      end)

  defp valid_correlation_field?("journey_id", value),
    do: valid_uuid?(value) and not (value =~ ~r/\A0{8}-0{4}-0{4}-0{4}-0{12}\z/)

  defp valid_correlation_field?("traceparent", value),
    do:
      bounded_string?(value, 55, 55) and value =~ @traceparent and
        not (value =~ ~r/\A00-0{32}-[0-9a-f]{16}-[0-9a-f]{2}\z/) and
        not (value =~ ~r/\A00-[0-9a-f]{32}-0{16}-[0-9a-f]{2}\z/)

  defp valid_correlation_field?("tracestate", value),
    do: bounded_string?(value, 1, 512) and value =~ @tracestate

  defp valid_correlation_field?(_key, _value), do: false

  defp correlation_fields(frame),
    do:
      Enum.reduce(@correlation_field_keys, %{}, fn key, fields ->
        if Map.has_key?(frame, key), do: Map.put(fields, key, frame[key]), else: fields
      end)

  defp correlation_exact_keys?(map, keys) when is_map(map),
    do:
      valid_correlation_fields?(map) and map_size(map) >= length(keys) and
        Enum.all?(keys, &Map.has_key?(map, &1)) and
        Enum.all?(Map.keys(map), &(&1 in keys or &1 in @correlation_field_keys))

  defp exact_keys?(map, keys) when is_map(map),
    do: map_size(map) == length(keys) and Enum.all?(keys, &Map.has_key?(map, &1))

  defp exact_keys?(_value, _keys), do: false

  defp server_frame_within_limit?(frame, limit) do
    budget = if complete_correlation?(frame), do: limit, else: limit - @correlation_reserved_bytes
    frame_within_limit?(frame, budget)
  end

  defp complete_correlation?(frame),
    do: Enum.all?(@correlation_field_keys, &Map.has_key?(frame, &1))

  defp frame_within_limit?(frame, limit), do: frame |> JSON.encode!() |> byte_size() <= limit
end
