// @ts-check

import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { codegenPath, loadSyncContract } from "./sync-contract.mjs";

const execute = promisify(execFile);
const sourceDirectory = path.dirname(fileURLToPath(import.meta.url));
const syncDirectory = path.resolve(sourceDirectory, "../../../../apps/sync");
const outputPath = codegenPath("CODEGEN_SYNC_ELIXIR_OUTPUT_PATH", "apps/sync/lib/chalk_sync/contract/generated.ex");
const contract = await loadSyncContract();
const source = renderElixir(contract);

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
await execute("mix", ["format", outputPath], { cwd: syncDirectory });

/**
 * @param {Record<string, any>} contract
 */
function renderElixir(contract) {
  const snapshot = contract.welcome.modes.find((mode) => mode.id === "snapshot").snapshot;
  const commands = contract.commands.slice().sort((left, right) => left.name.localeCompare(right.name));
  const metadata = {
    version: contract.version,
    protocol: contract.protocol,
    directions: contract.directions,
    phases: contract.phases,
    continuity: contract.continuity,
    idempotency: contract.idempotency,
    closeCodes: contract.closeCodes,
    errorConnection: contract.error.connection,
  };
  const commandTypes = commands.map((command) => `:${command.name}`).join(" | ");
  const eventClauses = contract.events.map(renderEventClause).join("\n\n");
  const ackClauses = contract.acks.map(renderAckClause).join("\n");

  return `# Generated by tools/contract-codegen/src/emitters/sync-elixir.mjs
# Do not edit by hand.
defmodule ChalkSync.Contract.Generated do
  @moduledoc false

  @protocol_version ${contract.protocol.value}
  @client_commands %{${commands.map((command) => `${inspectString(command.name)} => :${command.name}`).join(", ")}}
  @close_codes ${renderCloseCodes(contract.closeCodes)}
  @metadata ${renderElixirValue(metadata)}

  @type command_name :: ${commandTypes}
  @type client_frame ::
          {:hello, %{token: String.t(), cursor: non_neg_integer() | nil}}
          | {:command, %{command_id: String.t(), name: command_name(), payload: map()}}
          | :ping

  def protocol_version, do: @protocol_version
  def client_commands, do: @client_commands
  def close_code(code), do: Map.get(@close_codes, code)
  def metadata, do: @metadata

  @spec decode_client_frame(map()) :: {:ok, client_frame()} | {:error, atom()}
  def decode_client_frame(frame) when is_map(frame) do
    case Map.fetch(frame, "type") do
      :error -> {:error, :missing_type}
      {:ok, "hello"} -> decode_hello(frame)
      {:ok, "command"} -> decode_command(frame)
      {:ok, "ping"} -> {:ok, :ping}
      {:ok, _type} -> {:error, :unknown_type}
    end
  end

  def decode_client_frame(_frame), do: {:error, :missing_type}

  @spec valid_server_frame?(map()) :: boolean()
  def valid_server_frame?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "snapshot", "snapshot" => snapshot}) do
    is_binary(participant_id) and valid_snapshot?(snapshot)
  end

  def valid_server_frame?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "replay", "events" => events, "control_revision" => revision}) do
    is_binary(participant_id) and valid_non_negative_integer?(revision) and is_list(events) and Enum.all?(events, &valid_event_frame?/1)
  end

  def valid_server_frame?(%{"type" => "event"} = frame), do: valid_event_frame?(frame)

${ackClauses}

  def valid_server_frame?(%{"type" => "error", "code" => code, "message" => message}), do: is_binary(code) and is_binary(message)
  def valid_server_frame?(%{"type" => "pong"}), do: true
  def valid_server_frame?(_frame), do: false

  defp decode_hello(frame) do
    case Map.fetch(frame, "protocol") do
      {:ok, @protocol_version} ->
        case Map.get(frame, "token") do
          token when is_binary(token) -> decode_hello_cursor(frame, token)
          _ -> {:error, :invalid_hello}
        end

      {:ok, _version} ->
        {:error, :unsupported_protocol}

      :error ->
        {:error, :invalid_hello}
    end
  end

  defp decode_hello_cursor(frame, token) do
    case control_cursor(frame) do
      :missing -> {:ok, {:hello, %{token: token, cursor: nil}}}
      :invalid -> {:error, :invalid_cursor}
      {:present, nil} -> {:ok, {:hello, %{token: token, cursor: nil}}}
      {:present, cursor} when is_integer(cursor) and cursor >= 0 -> {:ok, {:hello, %{token: token, cursor: cursor}}}
      {:present, _cursor} -> {:error, :invalid_cursor}
    end
  end

  defp decode_command(frame) do
    case {Map.get(frame, "command_id"), Map.get(frame, "name")} do
      {command_id, name} when is_binary(command_id) and is_binary(name) ->
        case @client_commands do
          %{^name => command} -> decode_command_payload(frame, command_id, command)
          _ -> {:error, :unknown_command}
        end

      _ ->
        {:error, :invalid_command}
    end
  end

  defp decode_command_payload(frame, command_id, command) do
    case Map.get(frame, "payload", %{}) do
      payload when is_map(payload) -> {:ok, {:command, %{command_id: command_id, name: command, payload: payload}}}
      _ -> {:error, :invalid_payload}
    end
  end

  defp control_cursor(frame) do
    with {:ok, streams} <- optional_map(frame, "streams"),
         {:ok, control} <- optional_map(streams, "control") do
      case Map.fetch(control, "cursor") do
        {:ok, cursor} -> {:present, cursor}
        :error -> :missing
      end
    else
      :missing -> :missing
      :invalid -> :invalid
    end
  end

  defp optional_map(container, key) do
    case Map.fetch(container, key) do
      {:ok, value} when is_map(value) -> {:ok, value}
      {:ok, _value} -> :invalid
      :error -> :missing
    end
  end

  defp valid_snapshot?(%{"control_revision" => revision, "participants" => participants}) do
    valid_non_negative_integer?(revision) and is_list(participants) and Enum.all?(participants, &valid_participant?/1)
  end

  defp valid_snapshot?(_snapshot), do: false

  defp valid_participant?(%{"participant_id" => participant_id, "display_name" => display_name, "hand_raised" => hand_raised}) do
    is_binary(participant_id) and is_binary(display_name) and is_boolean(hand_raised)
  end

  defp valid_participant?(_participant), do: false

${eventClauses}

  defp valid_event_frame?(_frame), do: false

  defp valid_revision_pair?(base_revision, revision) do
    valid_non_negative_integer?(base_revision) and valid_positive_integer?(revision) and revision == base_revision + 1
  end

  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0
  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1
end
`;
}

/**
 * @param {Record<string, any>} event
 */
function renderEventClause(event) {
  const payloadChecks = Object.entries(event.payload)
    .map(([name, field]) => `${elixirPredicate(field, nameToVariable(name))}`)
    .join(" and ");
  const payloadPattern = Object.keys(event.payload)
    .map((name) => `${inspectString(snakeCase(name))} => ${nameToVariable(name)}`)
    .join(", ");

  return `  defp valid_event_frame?(%{"type" => ${inspectString(event.type)}, "stream" => ${inspectString(event.stream)}, "name" => ${inspectString(event.name)}, "base_revision" => base_revision, "revision" => revision, "payload" => %{${payloadPattern}}}) do
    valid_revision_pair?(base_revision, revision) and ${payloadChecks}
  end`;
}

/**
 * @param {Record<string, any>} ack
 */
function renderAckClause(ack) {
  const extra = ack.revision ? ` and valid_positive_integer?(revision)` : " and is_binary(reason)";
  const field = ack.revision ? `"revision" => revision` : `"reason" => reason`;
  return `  def valid_server_frame?(%{
        "type" => ${inspectString(ack.type)},
        "command_id" => command_id,
        "result" => ${inspectString(ack.result)},
        ${field}
      }),
      do: is_binary(command_id)${extra}`;
}

/**
 * @param {unknown} value
 */
function renderElixirValue(value) {
  if (value === null) {
    return "nil";
  }
  if (typeof value === "string") {
    return inspectString(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(renderElixirValue).join(", ")}]`;
  }
  return `%{${Object.entries(value)
    .map(([key, child]) => `${inspectString(key)} => ${renderElixirValue(child)}`)
    .join(", ")}}`;
}

/**
 * @param {Record<string, any>[]} closeCodes
 */
function renderCloseCodes(closeCodes) {
  return `%{${closeCodes.map((closeCode) => `${closeCode.code} => ${renderElixirValue(closeCode)}`).join(", ")}}`;
}

/**
 * @param {string} value
 */
function inspectString(value) {
  return JSON.stringify(value);
}

/**
 * @param {string} value
 */
function snakeCase(value) {
  return value.replace(/[A-Z]/gu, (letter) => `_${letter.toLowerCase()}`);
}

/**
 * @param {string} value
 */
function nameToVariable(value) {
  return snakeCase(value);
}

/**
 * @param {Record<string, any>} field
 * @param {string} variable
 */
function elixirPredicate(field, variable) {
  switch (field.kind) {
    case "boolean":
      return `is_boolean(${variable})`;
    case "integer":
      return field.minimum > 0 ? `valid_positive_integer?(${variable})` : `valid_non_negative_integer?(${variable})`;
    default:
      return `is_binary(${variable})`;
  }
}
