// @ts-check

import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { codegenPath, loadSyncContract, syncProtocolVersion } from "./sync-contract.mjs";

const execute = promisify(execFile);
const sourceDirectory = path.dirname(fileURLToPath(import.meta.url));
const syncDirectory = path.resolve(sourceDirectory, "../../../../apps/sync");
const protocolVersion = syncProtocolVersion();
const outputPath = codegenPath("CODEGEN_SYNC_ELIXIR_OUTPUT_PATH", protocolVersion === 1 ? "apps/sync/lib/chalk_sync/contract/generated.ex" : "apps/sync/lib/chalk_sync/contract/generated_v2.ex");
const contract = await loadSyncContract(undefined, protocolVersion);
const source = contract.version === 1 ? renderElixir(contract) : renderV2Elixir(contract);

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
await execute("mix", ["format", outputPath], { cwd: syncDirectory });

/**
 * @param {Record<string, any>} contract
 */
function renderElixir(contract) {
  const snapshot = contract.welcome.modes.find((mode) => mode.id === "snapshot").snapshot;
  const commands = contract.commands.slice().sort((left, right) => left.name.localeCompare(right.name));
  const metadata = {
    version: contract.version,
    protocol: contract.protocol,
    directions: contract.directions,
    phases: contract.phases,
    continuity: contract.continuity,
    idempotency: contract.idempotency,
    closeCodes: contract.closeCodes,
    errorConnection: contract.error.connection,
  };
  const commandTypes = commands.map((command) => `:${command.name}`).join(" | ");
  const eventClauses = contract.events.map(renderEventClause).join("\n\n");
  const ackClauses = contract.acks.map(renderAckClause).join("\n");

  return `# Generated by tools/contract-codegen/src/emitters/sync-elixir.mjs
# Do not edit by hand.
defmodule ChalkSync.Contract.Generated do
  @moduledoc false

  @protocol_version ${contract.protocol.value}
  @client_commands %{${commands.map((command) => `${inspectString(command.name)} => :${command.name}`).join(", ")}}
  @close_codes ${renderCloseCodes(contract.closeCodes)}
  @metadata ${renderElixirValue(metadata)}

  @type command_name :: ${commandTypes}
  @type client_frame ::
          {:hello, %{token: String.t(), cursor: non_neg_integer() | nil}}
          | {:command, %{command_id: String.t(), name: command_name(), payload: map()}}
          | :ping

  def protocol_version, do: @protocol_version
  def client_commands, do: @client_commands
  def close_code(code), do: Map.get(@close_codes, code)
  def metadata, do: @metadata

  @spec decode_client_frame(map()) :: {:ok, client_frame()} | {:error, atom()}
  def decode_client_frame(frame) when is_map(frame) do
    case Map.fetch(frame, "type") do
      :error -> {:error, :missing_type}
      {:ok, "hello"} -> decode_hello(frame)
      {:ok, "command"} -> decode_command(frame)
      {:ok, "ping"} -> {:ok, :ping}
      {:ok, _type} -> {:error, :unknown_type}
    end
  end

  def decode_client_frame(_frame), do: {:error, :missing_type}

  @spec valid_server_frame?(map()) :: boolean()
  def valid_server_frame?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "snapshot", "snapshot" => snapshot}) do
    is_binary(participant_id) and valid_snapshot?(snapshot)
  end

  def valid_server_frame?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "replay", "events" => events, "control_revision" => revision}) do
    is_binary(participant_id) and valid_non_negative_integer?(revision) and is_list(events) and Enum.all?(events, &valid_event_frame?/1)
  end

  def valid_server_frame?(%{"type" => "event"} = frame), do: valid_event_frame?(frame)

${ackClauses}

  def valid_server_frame?(%{"type" => "error", "code" => code, "message" => message}), do: is_binary(code) and is_binary(message)
  def valid_server_frame?(%{"type" => "pong"}), do: true
  def valid_server_frame?(_frame), do: false

  defp decode_hello(frame) do
    case Map.fetch(frame, "protocol") do
      {:ok, @protocol_version} ->
        case Map.get(frame, "token") do
          token when is_binary(token) -> decode_hello_cursor(frame, token)
          _ -> {:error, :invalid_hello}
        end

      {:ok, _version} ->
        {:error, :unsupported_protocol}

      :error ->
        {:error, :invalid_hello}
    end
  end

  defp decode_hello_cursor(frame, token) do
    case control_cursor(frame) do
      :missing -> {:ok, {:hello, %{token: token, cursor: nil}}}
      :invalid -> {:error, :invalid_cursor}
      {:present, nil} -> {:ok, {:hello, %{token: token, cursor: nil}}}
      {:present, cursor} when is_integer(cursor) and cursor >= 0 -> {:ok, {:hello, %{token: token, cursor: cursor}}}
      {:present, _cursor} -> {:error, :invalid_cursor}
    end
  end

  defp decode_command(frame) do
    case {Map.get(frame, "command_id"), Map.get(frame, "name")} do
      {command_id, name} when is_binary(command_id) and is_binary(name) ->
        case @client_commands do
          %{^name => command} -> decode_command_payload(frame, command_id, command)
          _ -> {:error, :unknown_command}
        end

      _ ->
        {:error, :invalid_command}
    end
  end

  defp decode_command_payload(frame, command_id, command) do
    case Map.get(frame, "payload", %{}) do
      payload when is_map(payload) -> {:ok, {:command, %{command_id: command_id, name: command, payload: payload}}}
      _ -> {:error, :invalid_payload}
    end
  end

  defp control_cursor(frame) do
    with {:ok, streams} <- optional_map(frame, "streams"),
         {:ok, control} <- optional_map(streams, "control") do
      case Map.fetch(control, "cursor") do
        {:ok, cursor} -> {:present, cursor}
        :error -> :missing
      end
    else
      :missing -> :missing
      :invalid -> :invalid
    end
  end

  defp optional_map(container, key) do
    case Map.fetch(container, key) do
      {:ok, value} when is_map(value) -> {:ok, value}
      {:ok, _value} -> :invalid
      :error -> :missing
    end
  end

  defp valid_snapshot?(%{"control_revision" => revision, "participants" => participants}) do
    valid_non_negative_integer?(revision) and is_list(participants) and Enum.all?(participants, &valid_participant?/1)
  end

  defp valid_snapshot?(_snapshot), do: false

  defp valid_participant?(%{"participant_id" => participant_id, "display_name" => display_name, "hand_raised" => hand_raised}) do
    is_binary(participant_id) and is_binary(display_name) and is_boolean(hand_raised)
  end

  defp valid_participant?(_participant), do: false

${eventClauses}

  defp valid_event_frame?(_frame), do: false

  defp valid_revision_pair?(base_revision, revision) do
    valid_non_negative_integer?(base_revision) and valid_positive_integer?(revision) and revision == base_revision + 1
  end

  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0
  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1
end
`;
}

/**
 * @param {Record<string, any>} contract
 */
function renderV2Elixir(contract) {
  const metadata = {
    version: contract.version,
    protocol: contract.protocol,
    directions: contract.directions,
    phases: contract.phases,
    limits: contract.limits,
    stateDigest: contract.stateDigest,
    continuity: contract.continuity,
    idempotency: contract.idempotency,
    closeCodes: contract.closeCodes,
  };
  const lines = [
    "# Generated by tools/contract-codegen/src/emitters/sync-elixir.mjs",
    "# Do not edit by hand.",
    "defmodule ChalkSync.Contract.GeneratedV2 do",
    "  @moduledoc false",
    "",
    "  @protocol_version 2",
    '  @client_commands %{"lower_hand" => :lower_hand, "raise_hand" => :raise_hand}',
    "  @limits " + renderElixirValue(contract.limits),
    "  @close_codes " + renderCloseCodes(contract.closeCodes),
    "  @metadata " + renderElixirValue(metadata),
    "  @uuid ~r/\\A[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\z/i",
    "  @digest ~r/\\A[0-9a-f]{64}\\z/",
    "",
    "  @type command_name :: :raise_hand | :lower_hand",
    "  @type cursor :: %{revision: non_neg_integer(), state_schema_version: pos_integer(), state_digest: String.t()}",
    "  @type client_frame :: {:hello, %{token: String.t(), cursor: cursor() | nil}} | {:command, %{command_id: String.t(), name: command_name(), payload: %{}}} | {:delivery_ack, %{stream: :control, revision: pos_integer(), state_digest: String.t()}} | {:recovery_ack, %{recovery_id: String.t(), revision: non_neg_integer(), state_digest: String.t()}} | :ping",
    "",
    "  def protocol_version, do: @protocol_version",
    "  def client_commands, do: @client_commands",
    "  def limits, do: @limits",
    "  def close_code(code), do: Map.get(@close_codes, code)",
    "  def metadata, do: @metadata",
    "",
    "  @spec decode_client_frame(map()) :: {:ok, client_frame()} | {:error, atom()}",
    "  def decode_client_frame(frame) when is_map(frame) do",
    '    if frame_within_limit?(frame, @limits["decodedInboundFrameBytes"]) do',
    '      case Map.get(frame, "type") do',
    '        "hello" -> decode_hello(frame)',
    '        "command" -> decode_command(frame)',
    '        "delivery_ack" -> decode_delivery_ack(frame)',
    '        "recovery_ack" -> decode_recovery_ack(frame)',
    '        "ping" -> decode_ping(frame)',
    "        nil -> {:error, :missing_type}",
    "        _ -> {:error, :unknown_type}",
    "      end",
    "    else",
    "      {:error, :frame_too_large}",
    "    end",
    "  end",
    "",
    "  def decode_client_frame(_frame), do: {:error, :missing_type}",
    "",
    "  @spec valid_server_frame?(map()) :: boolean()",
    '  def valid_server_frame?(%{"type" => "welcome"} = frame), do: valid_welcome?(frame)',
    '  def valid_server_frame?(%{"type" => "replay_page"} = frame), do: valid_replay_page?(frame)',
    '  def valid_server_frame?(%{"type" => "recovery_complete"} = frame), do: valid_recovery_complete?(frame)',
    '  def valid_server_frame?(%{"type" => "event"} = frame), do: valid_event_frame?(frame)',
    '  def valid_server_frame?(%{"type" => "ack"} = frame), do: valid_ack?(frame)',
    '  def valid_server_frame?(%{"type" => "retryable_error"} = frame), do: valid_retryable_error?(frame)',
    '  def valid_server_frame?(%{"type" => "error"} = frame), do: valid_error?(frame)',
    '  def valid_server_frame?(%{"type" => "pong"} = frame), do: exact_keys?(frame, ["type"])',
    "",
    "  def valid_server_frame?(_frame), do: false",
    "",
    "  defp decode_hello(%{",
    '         "type" => "hello",',
    '         "protocol" => @protocol_version,',
    '         "token" => token,',
    '         "streams" => %{"control" => %{"cursor" => cursor}} = streams',
    "       } = frame) do",
    '    if exact_keys?(frame, ["type", "protocol", "token", "streams"]) and exact_keys?(streams, ["control"]) and',
    '         exact_keys?(streams["control"], ["cursor"]) and valid_token?(token) and valid_cursor?(cursor) do',
    "      {:ok, {:hello, %{token: token, cursor: cursor}}}",
    "    else",
    "      {:error, :invalid_hello}",
    "    end",
    "  end",
    "",
    '  defp decode_hello(%{"protocol" => protocol}) when is_integer(protocol), do: {:error, :unsupported_protocol}',
    "  defp decode_hello(_frame), do: {:error, :invalid_hello}",
    "",
    '  defp decode_command(%{"type" => "command", "command_id" => command_id, "name" => name, "payload" => payload} = frame) do',
    '    with true <- exact_keys?(frame, ["type", "command_id", "name", "payload"]),',
    "         true <- valid_command_id?(command_id),",
    "         true <- exact_keys?(payload, []),",
    "         {:ok, command} <- Map.fetch(@client_commands, name) do",
    "      {:ok, {:command, %{command_id: command_id, name: command, payload: %{}}}}",
    "    else",
    "      :error -> {:error, :unknown_command}",
    "      _ -> {:error, :invalid_command}",
    "    end",
    "  end",
    "",
    "  defp decode_command(_frame), do: {:error, :invalid_command}",
    "",
    '  defp decode_delivery_ack(%{"type" => "delivery_ack", "stream" => "control", "revision" => revision, "state_digest" => digest} = frame) do',
    '    if exact_keys?(frame, ["type", "stream", "revision", "state_digest"]) and valid_positive_integer?(revision) and valid_digest?(digest) do',
    "      {:ok, {:delivery_ack, %{stream: :control, revision: revision, state_digest: digest}}}",
    "    else",
    "      {:error, :invalid_delivery_ack}",
    "    end",
    "  end",
    "",
    "  defp decode_delivery_ack(_frame), do: {:error, :invalid_delivery_ack}",
    "",
    '  defp decode_recovery_ack(%{"type" => "recovery_ack", "recovery_id" => recovery_id, "revision" => revision, "state_digest" => digest} = frame) do',
    '    if exact_keys?(frame, ["type", "recovery_id", "revision", "state_digest"]) and valid_uuid?(recovery_id) and valid_non_negative_integer?(revision) and valid_digest?(digest) do',
    "      {:ok, {:recovery_ack, %{recovery_id: recovery_id, revision: revision, state_digest: digest}}}",
    "    else",
    "      {:error, :invalid_recovery_ack}",
    "    end",
    "  end",
    "",
    "  defp decode_recovery_ack(_frame), do: {:error, :invalid_recovery_ack}",
    "",
    '  defp decode_ping(%{"type" => "ping"} = frame) do',
    '    if exact_keys?(frame, ["type"]), do: {:ok, :ping}, else: {:error, :invalid_ping}',
    "  end",
    "",
    '  defp valid_welcome?(%{"mode" => "snapshot", "snapshot" => snapshot} = frame) do',
    '    exact_keys?(frame, ["type", "protocol", "participant_session_id", "participant_session_generation", "recovery_id", "head", "mode", "snapshot"]) and',
    "      valid_welcome_base?(frame) and valid_snapshot?(snapshot)",
    "  end",
    "",
    '  defp valid_welcome?(%{"mode" => "replay"} = frame), do: valid_welcome_without_content?(frame)',
    '  defp valid_welcome?(%{"mode" => "up_to_date"} = frame), do: valid_welcome_without_content?(frame)',
    "",
    '  defp valid_welcome?(%{"mode" => "terminal", "reason" => reason} = frame) do',
    '    exact_keys?(frame, ["type", "protocol", "participant_session_id", "participant_session_generation", "recovery_id", "head", "mode", "reason"]) and',
    '      valid_welcome_base?(frame) and reason in ["session_ended", "participant_inactive", "stale_participant_generation"]',
    "  end",
    "",
    "  defp valid_welcome?(_frame), do: false",
    "",
    "  defp valid_welcome_without_content?(frame) do",
    '    exact_keys?(frame, ["type", "protocol", "participant_session_id", "participant_session_generation", "recovery_id", "head", "mode"]) and valid_welcome_base?(frame)',
    "  end",
    "",
    "  defp valid_welcome_base?(%{",
    '         "type" => "welcome",',
    '         "protocol" => @protocol_version,',
    '         "participant_session_id" => participant_session_id,',
    '         "participant_session_generation" => generation,',
    '         "recovery_id" => recovery_id,',
    '         "head" => head',
    "       }) do",
    "    valid_uuid?(participant_session_id) and valid_positive_integer?(generation) and valid_uuid?(recovery_id) and valid_cursor?(head)",
    "  end",
    "",
    "  defp valid_welcome_base?(_frame), do: false",
    "",
    "  defp valid_replay_page?(%{",
    '         "type" => "replay_page",',
    '         "recovery_id" => recovery_id,',
    '         "first_revision" => first_revision,',
    '         "last_revision" => last_revision,',
    '         "events" => events',
    "       } = frame) do",
    '    exact_keys?(frame, ["type", "recovery_id", "first_revision", "last_revision", "events"]) and valid_uuid?(recovery_id) and',
    "      valid_positive_integer?(first_revision) and valid_positive_integer?(last_revision) and is_list(events) and",
    '      length(events) <= @limits["replayPageMaxEvents"] and frame_within_limit?(frame, @limits["replayPageEncodedBytes"]) and',
    "      valid_replay_range?(events, first_revision, last_revision)",
    "  end",
    "",
    "  defp valid_replay_page?(_frame), do: false",
    "",
    '  defp valid_recovery_complete?(%{"type" => "recovery_complete", "recovery_id" => recovery_id, "head" => head} = frame) do',
    '    exact_keys?(frame, ["type", "recovery_id", "head"]) and valid_uuid?(recovery_id) and valid_cursor?(head)',
    "  end",
    "",
    "  defp valid_recovery_complete?(_frame), do: false",
    "",
    "  defp valid_event_frame?(%{",
    '         "type" => "event",',
    '         "stream" => "control",',
    '         "name" => name,',
    '         "event_id" => event_id,',
    '         "base_revision" => base_revision,',
    '         "revision" => revision,',
    '         "schema_version" => schema_version,',
    '         "resulting_state_digest" => digest,',
    '         "payload" => payload',
    "       } = frame) do",
    "    valid_uuid?(event_id) and valid_revision_pair?(base_revision, revision) and valid_positive_integer?(schema_version) and valid_digest?(digest) and",
    '      frame_within_limit?(frame, @limits["encodedLiveEventBytes"]) and valid_named_event?(frame, name, payload)',
    "  end",
    "",
    "  defp valid_event_frame?(_frame), do: false",
    "",
    '  defp valid_named_event?(%{"lifecycle_intent_id" => intent_id} = frame, "participant_joined", payload) do',
    '    exact_keys?(frame, ["type", "stream", "name", "event_id", "base_revision", "revision", "schema_version", "resulting_state_digest", "payload", "lifecycle_intent_id"]) and',
    '      valid_uuid?(intent_id) and exact_keys?(payload, ["display_name", "participant_session_id"]) and',
    '      valid_display_name?(payload["display_name"]) and valid_uuid?(payload["participant_session_id"])',
    "  end",
    "",
    '  defp valid_named_event?(%{"lifecycle_intent_id" => intent_id} = frame, "participant_left", payload) do',
    '    exact_keys?(frame, ["type", "stream", "name", "event_id", "base_revision", "revision", "schema_version", "resulting_state_digest", "payload", "lifecycle_intent_id"]) and',
    '      valid_uuid?(intent_id) and exact_keys?(payload, ["participant_session_id"]) and valid_uuid?(payload["participant_session_id"])',
    "  end",
    "",
    '  defp valid_named_event?(%{"lifecycle_intent_id" => intent_id} = frame, "session_ended", payload) do',
    '    exact_keys?(frame, ["type", "stream", "name", "event_id", "base_revision", "revision", "schema_version", "resulting_state_digest", "payload", "lifecycle_intent_id"]) and',
    "      valid_uuid?(intent_id) and exact_keys?(payload, [])",
    "  end",
    "",
    '  defp valid_named_event?(%{"command_id" => command_id} = frame, name, payload) when name in ["hand_raised", "hand_lowered"] do',
    '    exact_keys?(frame, ["type", "stream", "name", "event_id", "base_revision", "revision", "schema_version", "resulting_state_digest", "payload", "command_id"]) and',
    '      valid_command_id?(command_id) and exact_keys?(payload, ["participant_session_id"]) and valid_uuid?(payload["participant_session_id"])',
    "  end",
    "",
    "  defp valid_named_event?(_frame, _name, _payload), do: false",
    "",
    '  defp valid_ack?(%{"result" => "committed", "command_id" => command_id, "event_id" => event_id, "revision" => revision} = frame) do',
    '    exact_keys?(frame, ["type", "command_id", "result", "event_id", "revision"]) and valid_command_id?(command_id) and valid_uuid?(event_id) and valid_positive_integer?(revision)',
    "  end",
    "",
    '  defp valid_ack?(%{"result" => "duplicate", "command_id" => command_id, "event_id" => event_id, "revision" => revision} = frame) do',
    '    exact_keys?(frame, ["type", "command_id", "result", "event_id", "revision"]) and valid_command_id?(command_id) and valid_uuid?(event_id) and valid_positive_integer?(revision)',
    "  end",
    "",
    '  defp valid_ack?(%{"result" => "rejected", "command_id" => command_id, "reason" => reason} = frame) do',
    '    exact_keys?(frame, ["type", "command_id", "result", "reason"]) and valid_command_id?(command_id) and',
    '      reason in ["session_ended", "participant_inactive", "stale_participant_generation", "capability_denied", "invalid_state", "command_id_conflict"]',
    "  end",
    "",
    "  defp valid_ack?(_frame), do: false",
    "",
    '  defp valid_retryable_error?(%{"type" => "retryable_error", "command_id" => command_id, "code" => code} = frame) do',
    '    exact_keys?(frame, ["type", "command_id", "code"]) and valid_command_id?(command_id) and',
    '      code in ["overloaded", "server_draining", "dependency_unavailable", "decision_unavailable"]',
    "  end",
    "",
    "  defp valid_retryable_error?(_frame), do: false",
    "",
    '  defp valid_error?(%{"type" => "error", "code" => code, "detail" => detail} = frame) do',
    '    exact_keys?(frame, ["type", "code", "detail"]) and code in ["protocol_error", "invalid_frame", "unsupported_protocol"] and',
    '      is_binary(detail) and byte_size(detail) <= @limits["protocolErrorDetailBytes"]',
    "  end",
    "",
    "  defp valid_error?(_frame), do: false",
    "",
    "  defp valid_snapshot?(%{",
    '         "control_revision" => revision,',
    '         "state_schema_version" => schema_version,',
    '         "state_digest" => digest,',
    '         "status" => status,',
    '         "participants" => participants',
    "       } = snapshot) do",
    '    exact_keys?(snapshot, ["control_revision", "state_schema_version", "state_digest", "status", "participants"]) and',
    '      valid_non_negative_integer?(revision) and valid_positive_integer?(schema_version) and valid_digest?(digest) and status in ["active", "ended"] and',
    "      is_list(participants) and length(participants) <= 500 and Enum.all?(participants, &valid_participant?/1) and",
    '      frame_within_limit?(snapshot, @limits["snapshotEncodedBytes"])',
    "  end",
    "",
    "  defp valid_snapshot?(_snapshot), do: false",
    "",
    '  defp valid_participant?(%{"participant_session_id" => participant_session_id, "display_name" => display_name, "hand_raised" => hand_raised} = participant) do',
    '    exact_keys?(participant, ["participant_session_id", "display_name", "hand_raised"]) and valid_uuid?(participant_session_id) and',
    "      valid_display_name?(display_name) and is_boolean(hand_raised)",
    "  end",
    "",
    "  defp valid_participant?(_participant), do: false",
    "",
    "  defp valid_replay_range?([], _first_revision, _last_revision), do: false",
    "",
    "  defp valid_replay_range?([first | rest], first_revision, last_revision) do",
    '    valid_event_frame?(first) and first["revision"] == first_revision and',
    "      Enum.reduce_while(rest, first, fn event, previous ->",
    '        if valid_event_frame?(event) and event["base_revision"] == previous["revision"] do',
    "          {:cont, event}",
    "        else",
    "          {:halt, :invalid}",
    "        end",
    "      end) |> case do",
    "        :invalid -> false",
    '        last -> last["revision"] == last_revision',
    "      end",
    "  end",
    "",
    "  defp valid_revision_pair?(base_revision, revision) do",
    "    valid_non_negative_integer?(base_revision) and valid_positive_integer?(revision) and revision == base_revision + 1",
    "  end",
    "",
    "  defp valid_cursor?(nil), do: true",
    "",
    '  defp valid_cursor?(%{"revision" => revision, "state_schema_version" => schema_version, "state_digest" => digest} = cursor) do',
    '    exact_keys?(cursor, ["revision", "state_schema_version", "state_digest"]) and valid_non_negative_integer?(revision) and',
    "      valid_positive_integer?(schema_version) and valid_digest?(digest)",
    "  end",
    "",
    "  defp valid_cursor?(_cursor), do: false",
    "",
    '  defp valid_token?(token), do: is_binary(token) and byte_size(token) <= @limits["tokenBytes"]',
    '  defp valid_command_id?(value), do: is_binary(value) and byte_size(value) >= @limits["commandIdMinBytes"] and byte_size(value) <= @limits["commandIdMaxBytes"]',
    "  defp valid_display_name?(value), do: is_binary(value) and byte_size(value) <= 256",
    "  defp valid_uuid?(value), do: is_binary(value) and value =~ @uuid",
    "  defp valid_digest?(value), do: is_binary(value) and value =~ @digest",
    "  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0",
    "  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1",
    "",
    "  defp exact_keys?(map, keys) when is_map(map) do",
    "    map_size(map) == length(keys) and Enum.all?(keys, &Map.has_key?(map, &1))",
    "  end",
    "",
    "  defp exact_keys?(_value, _keys), do: false",
    "",
    "  defp frame_within_limit?(frame, limit), do: frame |> JSON.encode!() |> byte_size() <= limit",
    "end",
  ];

  return lines.join("\n") + "\n";
}

/**
 * @param {Record<string, any>} event
 */
function renderEventClause(event) {
  const payloadChecks = Object.entries(event.payload)
    .map(([name, field]) => `${elixirPredicate(field, nameToVariable(name))}`)
    .join(" and ");
  const payloadPattern = Object.keys(event.payload)
    .map((name) => `${inspectString(snakeCase(name))} => ${nameToVariable(name)}`)
    .join(", ");

  return `  defp valid_event_frame?(%{"type" => ${inspectString(event.type)}, "stream" => ${inspectString(event.stream)}, "name" => ${inspectString(event.name)}, "base_revision" => base_revision, "revision" => revision, "payload" => %{${payloadPattern}}}) do
    valid_revision_pair?(base_revision, revision) and ${payloadChecks}
  end`;
}

/**
 * @param {Record<string, any>} ack
 */
function renderAckClause(ack) {
  const extra = ack.revision ? ` and valid_positive_integer?(revision)` : " and is_binary(reason)";
  const field = ack.revision ? `"revision" => revision` : `"reason" => reason`;
  return `  def valid_server_frame?(%{
        "type" => ${inspectString(ack.type)},
        "command_id" => command_id,
        "result" => ${inspectString(ack.result)},
        ${field}
      }),
      do: is_binary(command_id)${extra}`;
}

/**
 * @param {unknown} value
 */
function renderElixirValue(value) {
  if (value === null) {
    return "nil";
  }
  if (typeof value === "string") {
    return inspectString(value);
  }
  if (typeof value === "number") {
    const rendered = String(value);
    if (Number.isInteger(value) && Math.abs(value) >= 10_000) {
      const sign = rendered.startsWith("-") ? "-" : "";
      const digits = sign ? rendered.slice(1) : rendered;
      return sign + digits.replace(/\B(?=(\d{3})+(?!\d))/gu, "_");
    }
    return rendered;
  }
  if (typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(renderElixirValue).join(", ")}]`;
  }
  return `%{${Object.entries(value)
    .map(([key, child]) => `${inspectString(key)} => ${renderElixirValue(child)}`)
    .join(", ")}}`;
}

/**
 * @param {Record<string, any>[]} closeCodes
 */
function renderCloseCodes(closeCodes) {
  return `%{${closeCodes.map((closeCode) => `${closeCode.code} => ${renderElixirValue(closeCode)}`).join(", ")}}`;
}

/**
 * @param {string} value
 */
function inspectString(value) {
  return JSON.stringify(value);
}

/**
 * @param {string} value
 */
function snakeCase(value) {
  return value.replace(/[A-Z]/gu, (letter) => `_${letter.toLowerCase()}`);
}

/**
 * @param {string} value
 */
function nameToVariable(value) {
  return snakeCase(value);
}

/**
 * @param {Record<string, any>} field
 * @param {string} variable
 */
function elixirPredicate(field, variable) {
  switch (field.kind) {
    case "boolean":
      return `is_boolean(${variable})`;
    case "integer":
      return field.minimum > 0 ? `valid_positive_integer?(${variable})` : `valid_non_negative_integer?(${variable})`;
    default:
      return `is_binary(${variable})`;
  }
}
