// @ts-check

import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { codegenPath, loadSyncContract, syncProtocolVersion } from "./sync-contract.mjs";

const execute = promisify(execFile);
const sourceDirectory = path.dirname(fileURLToPath(import.meta.url));
const syncDirectory = path.resolve(sourceDirectory, "../../../../apps/sync");
const protocolVersion = syncProtocolVersion();
const outputPath = codegenPath("CODEGEN_SYNC_ELIXIR_OUTPUT_PATH", protocolVersion === 1 ? "apps/sync/lib/chalk_sync/contract/generated.ex" : `apps/sync/lib/chalk_sync/contract/generated_v${protocolVersion}.ex`);
const contract = await loadSyncContract(undefined, protocolVersion);
const source = contract.version === 1 ? renderElixir(contract) : renderV3Elixir(contract);

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
await execute("mix", ["format", outputPath], { cwd: syncDirectory });

/**
 * @param {Record<string, any>} contract
 */
function renderElixir(contract) {
  const snapshot = contract.welcome.modes.find((mode) => mode.id === "snapshot").snapshot;
  const commands = contract.commands.slice().sort((left, right) => left.name.localeCompare(right.name));
  const metadata = {
    version: contract.version,
    protocol: contract.protocol,
    directions: contract.directions,
    correlation: contract.correlation,
    phases: contract.phases,
    continuity: contract.continuity,
    idempotency: contract.idempotency,
    closeCodes: contract.closeCodes,
    errorConnection: contract.error.connection,
  };
  const commandTypes = commands.map((command) => `:${command.name}`).join(" | ");
  const eventClauses = contract.events.map(renderEventClause).join("\n\n");
  const ackClauses = contract.acks.map(renderAckClause).join("\n");
  const correlationType = renderCorrelationType(contract.correlation.optionalTopLevelFields);
  const correlationFieldKeys = renderCorrelationFieldKeys(contract.correlation.optionalTopLevelFields);
  const correlationValidation = renderCorrelationValidation(contract.correlation.optionalTopLevelFields);

  return `# Generated by tools/contract-codegen/src/emitters/sync-elixir.mjs
# Do not edit by hand.
defmodule ChalkSync.Contract.Generated do
  @moduledoc false

  @protocol_version ${contract.protocol.value}
  @client_commands %{${commands.map((command) => `${inspectString(command.name)} => :${command.name}`).join(", ")}}
  @correlation_field_keys ${correlationFieldKeys}
  @close_codes ${renderCloseCodes(contract.closeCodes)}
  @metadata ${renderElixirValue(metadata)}

  @type correlation_fields :: ${correlationType}
  @type command_name :: ${commandTypes}
  @type client_frame ::
          {:hello, %{required(:token) => String.t(), required(:cursor) => non_neg_integer() | nil, ${renderCorrelationTypeEntries(contract.correlation.optionalTopLevelFields)}}}
          | {:command, %{required(:command_id) => String.t(), required(:name) => command_name(), required(:payload) => map(), ${renderCorrelationTypeEntries(contract.correlation.optionalTopLevelFields)}}}
          | {:ping, correlation_fields()}

  def protocol_version, do: @protocol_version
  def client_commands, do: @client_commands
  def close_code(code), do: Map.get(@close_codes, code)
  def metadata, do: @metadata

  @spec decode_client_frame(map()) :: {:ok, client_frame()} | {:error, atom()}
  def decode_client_frame(frame) when is_map(frame) do
    if valid_correlation_fields?(frame) do
      case Map.fetch(frame, "type") do
        :error -> {:error, :missing_type}
        {:ok, "hello"} -> decode_hello(frame)
        {:ok, "command"} -> decode_command(frame)
        {:ok, "ping"} -> {:ok, {:ping, correlation_fields(frame)}}
        {:ok, _type} -> {:error, :unknown_type}
      end
    else
      {:error, :invalid_correlation_fields}
    end
  end

  def decode_client_frame(_frame), do: {:error, :missing_type}

  @spec valid_server_frame?(map()) :: boolean()
  def valid_server_frame?(frame) when is_map(frame), do: valid_correlation_fields?(frame) and valid_server_frame_body?(frame)
  def valid_server_frame?(_frame), do: false

  defp valid_server_frame_body?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "snapshot", "snapshot" => snapshot}) do
    is_binary(participant_id) and valid_snapshot?(snapshot)
  end

  defp valid_server_frame_body?(%{"type" => "welcome", "protocol" => @protocol_version, "participant_id" => participant_id, "mode" => "replay", "events" => events, "control_revision" => revision}) do
    is_binary(participant_id) and valid_non_negative_integer?(revision) and is_list(events) and Enum.all?(events, &valid_event_frame?/1)
  end

  defp valid_server_frame_body?(%{"type" => "event"} = frame), do: valid_event_frame?(frame)

${ackClauses}

  defp valid_server_frame_body?(%{"type" => "error", "code" => code, "message" => message}), do: is_binary(code) and is_binary(message)
  defp valid_server_frame_body?(%{"type" => "pong"}), do: true
  defp valid_server_frame_body?(_frame), do: false

  defp decode_hello(frame) do
    case Map.fetch(frame, "protocol") do
      {:ok, @protocol_version} ->
        case Map.get(frame, "token") do
          token when is_binary(token) -> decode_hello_cursor(frame, token)
          _ -> {:error, :invalid_hello}
        end

      {:ok, _version} ->
        {:error, :unsupported_protocol}

      :error ->
        {:error, :invalid_hello}
    end
  end

  defp decode_hello_cursor(frame, token) do
    case control_cursor(frame) do
      :missing -> {:ok, {:hello, Map.merge(%{token: token, cursor: nil}, correlation_fields(frame))}}
      :invalid -> {:error, :invalid_cursor}
      {:present, nil} -> {:ok, {:hello, Map.merge(%{token: token, cursor: nil}, correlation_fields(frame))}}
      {:present, cursor} when is_integer(cursor) and cursor >= 0 -> {:ok, {:hello, Map.merge(%{token: token, cursor: cursor}, correlation_fields(frame))}}
      {:present, _cursor} -> {:error, :invalid_cursor}
    end
  end

  defp decode_command(frame) do
    case {Map.get(frame, "command_id"), Map.get(frame, "name")} do
      {command_id, name} when is_binary(command_id) and is_binary(name) ->
        case @client_commands do
          %{^name => command} -> decode_command_payload(frame, command_id, command)
          _ -> {:error, :unknown_command}
        end

      _ ->
        {:error, :invalid_command}
    end
  end

  defp decode_command_payload(frame, command_id, command) do
    case Map.get(frame, "payload", %{}) do
      payload when is_map(payload) -> {:ok, {:command, Map.merge(%{command_id: command_id, name: command, payload: payload}, correlation_fields(frame))}}
      _ -> {:error, :invalid_payload}
    end
  end

  defp control_cursor(frame) do
    with {:ok, streams} <- optional_map(frame, "streams"),
         {:ok, control} <- optional_map(streams, "control") do
      case Map.fetch(control, "cursor") do
        {:ok, cursor} -> {:present, cursor}
        :error -> :missing
      end
    else
      :missing -> :missing
      :invalid -> :invalid
    end
  end

  defp optional_map(container, key) do
    case Map.fetch(container, key) do
      {:ok, value} when is_map(value) -> {:ok, value}
      {:ok, _value} -> :invalid
      :error -> :missing
    end
  end

  defp valid_snapshot?(%{"control_revision" => revision, "participants" => participants}) do
    valid_non_negative_integer?(revision) and is_list(participants) and Enum.all?(participants, &valid_participant?/1)
  end

  defp valid_snapshot?(_snapshot), do: false

  defp valid_participant?(%{"participant_id" => participant_id, "display_name" => display_name, "hand_raised" => hand_raised}) do
    is_binary(participant_id) and is_binary(display_name) and is_boolean(hand_raised)
  end

  defp valid_participant?(_participant), do: false

${eventClauses}

  defp valid_event_frame?(_frame), do: false

  defp valid_revision_pair?(base_revision, revision) do
    valid_non_negative_integer?(base_revision) and valid_positive_integer?(revision) and revision == base_revision + 1
  end

  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0
  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1

  defp correlation_fields(frame) do
    Enum.reduce(@correlation_field_keys, %{}, fn {wire_key, field}, fields ->
      case Map.fetch(frame, wire_key) do
        {:ok, value} -> Map.put(fields, field, value)
        :error -> fields
      end
    end)
  end

  defp valid_correlation_fields?(frame), do: ${correlationValidation}
end
`;
}

/**
 * @param {Record<string, any>} contract
 */
function renderV3Elixir(contract) {
  const limits = contract.limits;
  const eventOrigins = Object.fromEntries(contract.events.map((event) => [event.name, event.origin]));
  const metadata = {
    version: contract.version,
    protocol: contract.protocol,
    directions: contract.directions,
    phases: contract.phases,
    streams: contract.streams,
    externalIntents: contract.externalIntents,
    limits,
    continuity: contract.continuity,
    idempotency: contract.idempotency,
    closeCodes: contract.closeCodes,
  };
  const lines = [
    "# Generated by tools/contract-codegen/src/emitters/sync-elixir.mjs",
    "# Do not edit by hand.",
    "# credo:disable-for-this-file Credo.Check.Refactor.CyclomaticComplexity",
    "# credo:disable-for-this-file Credo.Check.Refactor.Nesting",
    "defmodule ChalkSync.Contract.GeneratedV3 do",
    "  @moduledoc false",
    "",
    "  @protocol_version 3",
    `  @client_commands %{${contract.commands.map((command) => `${JSON.stringify(command.name)} => :${command.name}`).join(", ")}}`,
    `  @client_operations %{${contract.operations.map((operation) => `${JSON.stringify(operation.name)} => :${operation.name}`).join(", ")}}`,
    `  @event_origins ${renderElixirValue(eventOrigins)}`,
    `  @limits ${renderElixirValue(limits)}`,
    `  @close_codes ${renderCloseCodes(contract.closeCodes)}`,
    `  @metadata ${renderElixirValue(metadata)}`,
    `  @capabilities ${renderElixirValue(contract.capabilities)}`,
    `  @roles ${renderElixirValue(contract.policy.roles)}`,
    `  @terminal_reasons ${renderElixirValue(contract.terminal.reasons)}`,
    `  @rejection_reasons ${renderElixirValue(contract.rejectionReasons)}`,
    `  @retryable_codes ${renderElixirValue(contract.retryableError.codes)}`,
    `  @protocol_error_codes ${renderElixirValue(contract.error.code)}`,
    `  @live_target_names ${renderElixirValue(contract.liveTargetFrames.request.name)}`,
    `  @live_target_outcomes ${renderElixirValue(contract.liveTargetFrames.result.outcome)}`,
    `  @directed_request_names ${renderElixirValue(contract.directedRequestFrames.send.name)}`,
    `  @directed_request_results ${renderElixirValue(contract.directedRequestFrames.result.result)}`,
    `  @media_sources ${renderElixirValue(contract.projectionFrames.mediaSnapshot.items.source)}`,
    `  @presence_states ${renderElixirValue(contract.projectionFrames.presenceSnapshot.items.state)}`,
    "  @uuid ~r/\\A[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\z/i",
    "  @digest ~r/\\A[0-9a-f]{64}\\z/",
    "",
    "  def protocol_version, do: @protocol_version",
    "  def client_commands, do: @client_commands",
    "  def client_operations, do: @client_operations",
    "  def limits, do: @limits",
    "  def close_code(code), do: Map.get(@close_codes, code)",
    "  def metadata, do: @metadata",
    "",
    "  @spec decode_client_frame(map()) :: {:ok, tuple() | :ping} | {:error, atom()}",
    "  def decode_client_frame(frame) when is_map(frame) do",
    '    if frame_within_limit?(frame, @limits["decodedInboundFrameBytes"]) do',
    '      case frame["type"] do',
    '        "hello" -> decode_hello(frame)',
    '        "command" -> decode_command(frame)',
    '        "operation" -> decode_operation(frame)',
    '        "live_target" -> decode_live_target(frame)',
    '        "directed_request" -> decode_directed_request(frame)',
    '        "request_ack" -> decode_request_ack(frame)',
    '        "delivery_ack" -> decode_delivery_ack(frame)',
    '        "recovery_ack" -> decode_recovery_ack(frame)',
    '        "ping" -> if(exact_keys?(frame, ["type"]), do: {:ok, :ping}, else: {:error, :invalid_ping})',
    "        nil -> {:error, :missing_type}",
    "        _ -> {:error, :unknown_type}",
    "      end",
    "    else",
    "      {:error, :frame_too_large}",
    "    end",
    "  end",
    "",
    "  def decode_client_frame(_frame), do: {:error, :missing_type}",
    "",
    '  defp decode_hello(%{"type" => "hello", "protocol" => @protocol_version, "token" => token, "streams" => streams} = frame) do',
    '    if exact_keys?(frame, ["type", "protocol", "token", "streams"]) and valid_token?(token) and valid_streams?(streams),',
    "      do: {:ok, {:hello, %{token: token, streams: streams}}},",
    "      else: {:error, :invalid_hello}",
    "  end",
    '  defp decode_hello(%{"protocol" => protocol}) when is_integer(protocol), do: {:error, :unsupported_protocol}',
    "  defp decode_hello(_frame), do: {:error, :invalid_hello}",
    "",
    '  defp decode_command(%{"command_id" => command_id, "name" => name, "payload" => payload} = frame) do',
    '    if exact_keys?(frame, ["type", "command_id", "name", "payload"]) and valid_command_id?(command_id) and valid_command_payload?(name, payload),',
    "      do: {:ok, {:command, %{command_id: command_id, name: @client_commands[name], payload: payload}}},",
    "      else: {:error, :invalid_command}",
    "  end",
    "  defp decode_command(_frame), do: {:error, :invalid_command}",
    "",
    ...renderV3ElixirCommandPayloads(contract.commands),
    "  defp valid_command_payload?(_name, _payload), do: false",
    "",
    '  defp decode_operation(%{"command_id" => command_id, "name" => name, "payload" => payload} = frame) do',
    '    if exact_keys?(frame, ["type", "command_id", "name", "payload"]) and valid_command_id?(command_id) and valid_operation_payload?(name, payload),',
    "      do: {:ok, {:operation, %{command_id: command_id, name: @client_operations[name], payload: payload}}},",
    "      else: {:error, :invalid_operation}",
    "  end",
    "  defp decode_operation(_frame), do: {:error, :invalid_operation}",
    "",
    ...renderV3ElixirOperationPayloads(contract.operations),
    "  defp valid_operation_payload?(_name, _payload), do: false",
    "",
    '  defp decode_live_target(%{"operation_id" => operation_id, "name" => name, "enabled" => enabled} = frame) do',
    '    if exact_keys?(frame, ["type", "operation_id", "name", "enabled"]) and valid_request_id?(operation_id) and name in @live_target_names and is_boolean(enabled),',
    "      do: {:ok, {:live_target, %{operation_id: operation_id, name: name, enabled: enabled}}},",
    "      else: {:error, :invalid_live_target}",
    "  end",
    "  defp decode_live_target(_frame), do: {:error, :invalid_live_target}",
    "",
    '  defp decode_directed_request(%{"request_id" => request_id, "name" => name, "target_participant_session_id" => target_id} = frame) do',
    '    if exact_keys?(frame, ["type", "request_id", "name", "target_participant_session_id"]) and valid_request_id?(request_id) and name in @directed_request_names and valid_uuid?(target_id),',
    "      do: {:ok, {:directed_request, %{request_id: request_id, name: name, target_participant_session_id: target_id}}},",
    "      else: {:error, :invalid_directed_request}",
    "  end",
    "  defp decode_directed_request(_frame), do: {:error, :invalid_directed_request}",
    "",
    '  defp decode_request_ack(%{"request_id" => request_id} = frame) do',
    '    if exact_keys?(frame, ["type", "request_id"]) and valid_request_id?(request_id), do: {:ok, {:request_ack, request_id}}, else: {:error, :invalid_request_ack}',
    "  end",
    "  defp decode_request_ack(_frame), do: {:error, :invalid_request_ack}",
    "",
    '  defp decode_delivery_ack(%{"stream" => "control", "revision" => revision, "state_digest" => digest} = frame) do',
    '    if exact_keys?(frame, ["type", "stream", "revision", "state_digest"]) and valid_positive_integer?(revision) and valid_digest?(digest), do: {:ok, {:delivery_ack, %{stream: :control, revision: revision, state_digest: digest}}}, else: {:error, :invalid_delivery_ack}',
    "  end",
    "  defp decode_delivery_ack(_frame), do: {:error, :invalid_delivery_ack}",
    "",
    '  defp decode_recovery_ack(%{"recovery_id" => recovery_id, "revision" => revision, "state_digest" => digest} = frame) do',
    '    if exact_keys?(frame, ["type", "recovery_id", "revision", "state_digest"]) and valid_uuid?(recovery_id) and valid_non_negative_integer?(revision) and valid_digest?(digest), do: {:ok, {:recovery_ack, %{recovery_id: recovery_id, revision: revision, state_digest: digest}}}, else: {:error, :invalid_recovery_ack}',
    "  end",
    "  defp decode_recovery_ack(_frame), do: {:error, :invalid_recovery_ack}",
    "",
    "  @spec valid_server_frame?(map()) :: boolean()",
    '  def valid_server_frame?(%{"type" => "welcome"} = frame), do: valid_welcome?(frame)',
    '  def valid_server_frame?(%{"type" => "replay_page"} = frame), do: valid_replay_page?(frame)',
    '  def valid_server_frame?(%{"type" => "recovery_complete"} = frame), do: exact_keys?(frame, ["type", "recovery_id", "head"]) and valid_uuid?(frame["recovery_id"]) and valid_cursor?(frame["head"])',
    '  def valid_server_frame?(%{"type" => "event"} = frame), do: valid_event?(frame)',
    '  def valid_server_frame?(%{"type" => "ack"} = frame), do: valid_ack?(frame)',
    '  def valid_server_frame?(%{"type" => type} = frame) when type in ["projection_snapshot", "projection_event"], do: valid_projection?(frame)',
    '  def valid_server_frame?(%{"type" => "live_target_result"} = frame), do: valid_live_target_result?(frame)',
    '  def valid_server_frame?(%{"type" => "directed_request"} = frame), do: valid_directed_request_delivery?(frame)',
    '  def valid_server_frame?(%{"type" => "directed_request_result"} = frame), do: valid_directed_request_result?(frame)',
    '  def valid_server_frame?(%{"type" => "retryable_error", "command_id" => id, "code" => code} = frame), do: exact_keys?(frame, ["type", "command_id", "code"]) and valid_command_id?(id) and code in @retryable_codes',
    '  def valid_server_frame?(%{"type" => "error", "code" => code, "detail" => detail} = frame), do: exact_keys?(frame, ["type", "code", "detail"]) and code in @protocol_error_codes and bounded_string?(detail, 0, @limits["protocolErrorDetailBytes"])',
    '  def valid_server_frame?(%{"type" => "pong"} = frame), do: exact_keys?(frame, ["type"])',
    "  def valid_server_frame?(_frame), do: false",
    "",
    '  defp valid_streams?(%{"control" => control, "media" => media, "presence" => presence, "requests" => requests} = streams) do',
    '    exact_keys?(streams, ["control", "media", "presence", "requests"]) and exact_keys?(control, ["cursor"]) and valid_cursor?(control["cursor"]) and Enum.all?([media, presence, requests], &(exact_keys?(&1, ["cursor"]) and &1["cursor"] == nil))',
    "  end",
    "  defp valid_streams?(_streams), do: false",
    "",
    '  defp valid_welcome?(%{"protocol" => @protocol_version, "participant_session_id" => participant_id, "participant_session_generation" => generation, "recovery_id" => recovery_id, "head" => head, "mode" => mode} = frame) do',
    '    base = ["type", "protocol", "participant_session_id", "participant_session_generation", "recovery_id", "head", "mode"]',
    "    valid_base = valid_uuid?(participant_id) and valid_positive_integer?(generation) and valid_uuid?(recovery_id) and valid_cursor?(head)",
    "    case mode do",
    '      "snapshot" -> exact_keys?(frame, base ++ ["snapshot"]) and valid_base and valid_snapshot?(frame["snapshot"])',
    '      mode when mode in ["replay", "up_to_date"] -> exact_keys?(frame, base) and valid_base',
    '      "terminal" -> exact_keys?(frame, base ++ ["reason"]) and valid_base and frame["reason"] in @terminal_reasons',
    "      _ -> false",
    "    end",
    "  end",
    "  defp valid_welcome?(_frame), do: false",
    "",
    '  defp valid_snapshot?(%{"participants" => participants, "admission_requests" => requests, "host_participant_session_id" => host_id, "role_capabilities" => role_capabilities} = snapshot) do',
    `    exact_keys?(snapshot, ${renderElixirValue(Object.keys(contract.snapshot).map(snakeCase))}) and`,
    '      valid_non_negative_integer?(snapshot["control_revision"]) and valid_positive_integer?(snapshot["state_schema_version"]) and valid_digest?(snapshot["state_digest"]) and',
    '      snapshot["status"] in ["active", "ended"] and snapshot["admission_policy"] in ["open", "approval", "closed"] and snapshot["host_exit_policy"] in ["require_transfer", "promote_cohost"] and',
    '      valid_positive_integer?(snapshot["deadline_at_ms"]) and valid_positive_integer?(snapshot["deadline_generation"]) and valid_role_capabilities?(role_capabilities) and valid_recording?(snapshot["recording"]) and',
    "      is_list(participants) and length(participants) <= 500 and Enum.all?(participants, &valid_participant?(&1, role_capabilities)) and",
    "      is_list(requests) and length(requests) <= 500 and Enum.all?(requests, &valid_admission_request?/1) and",
    '      valid_snapshot_collections?(snapshot["status"], host_id, participants, requests, snapshot["recording"]) and frame_within_limit?(snapshot, @limits["snapshotEncodedBytes"])',
    "  end",
    "  defp valid_snapshot?(_snapshot), do: false",
    "",
    '  defp valid_participant?(%{"participant_session_id" => id, "display_name" => name, "hand_raised" => raised, "admission_revision" => admission_revision, "role" => role, "eligible_roles" => eligible, "capabilities" => capabilities} = participant, role_capabilities) do',
    '    exact_keys?(participant, ["participant_session_id", "display_name", "hand_raised", "admission_revision", "role", "eligible_roles", "capabilities"]) and valid_uuid?(id) and bounded_string?(name, 1, 256) and is_boolean(raised) and valid_positive_integer?(admission_revision) and role in @roles and non_empty_unique_list?(eligible) and length(eligible) <= 3 and Enum.all?(eligible, &(&1 in @roles)) and role in eligible and (role != "host" or "cohost" in eligible) and capabilities == role_capabilities[role]',
    "  end",
    "  defp valid_participant?(_participant, _role_capabilities), do: false",
    "",
    '  defp valid_admission_request?(%{"admission_request_id" => request_id, "participant_session_id" => participant_id, "display_name" => name, "initial_role" => role, "eligible_roles" => eligible, "expires_at_ms" => expires_at} = request), do: exact_keys?(request, ["admission_request_id", "participant_session_id", "display_name", "initial_role", "eligible_roles", "expires_at_ms"]) and valid_uuid?(request_id) and valid_uuid?(participant_id) and bounded_string?(name, 1, 256) and role in @roles and non_empty_unique_list?(eligible) and length(eligible) <= 3 and Enum.all?(eligible, &(&1 in @roles)) and role in eligible and (role != "host" or "cohost" in eligible) and valid_positive_integer?(expires_at)',
    "  defp valid_admission_request?(_request), do: false",
    '  defp valid_role_capabilities?(%{"host" => host, "cohost" => cohost, "participant" => participant} = roles), do: exact_keys?(roles, ["host", "cohost", "participant"]) and Enum.all?([host, cohost, participant], &(unique_list?(&1) and length(&1) <= 16 and Enum.all?(&1, fn capability -> capability in @capabilities end)))',
    "  defp valid_role_capabilities?(_roles), do: false",
    "  defp valid_recording?(nil), do: true",
    '  defp valid_recording?(%{"recording_id" => id, "status" => status, "failure_code" => failure_code} = recording), do: exact_keys?(recording, ["recording_id", "status", "failure_code"]) and valid_uuid?(id) and status in ["starting", "recording", "stopping", "stopped", "failed"] and (is_nil(failure_code) or bounded_string?(failure_code, 1, 96)) and ((status == "failed") == (not is_nil(failure_code)))',
    "  defp valid_recording?(_recording), do: false",
    "",
    "  defp valid_snapshot_collections?(status, host_id, participants, requests, recording) do",
    '    participant_ids = Enum.map(participants, & &1["participant_session_id"])',
    '    request_ids = Enum.map(requests, & &1["admission_request_id"])',
    '    candidate_ids = Enum.map(requests, & &1["participant_session_id"])',
    "    unique_list?(participant_ids) and unique_list?(request_ids) and unique_list?(candidate_ids) and MapSet.disjoint?(MapSet.new(participant_ids), MapSet.new(candidate_ids)) and valid_snapshot_state?(status, host_id, participants, requests, recording)",
    "  end",
    '  defp valid_snapshot_state?("ended", host_id, participants, requests, recording), do: is_nil(host_id) and participants == [] and requests == [] and is_nil(recording)',
    '  defp valid_snapshot_state?("active", host_id, [], _requests, _recording), do: is_nil(host_id)',
    '  defp valid_snapshot_state?("active", host_id, participants, _requests, _recording) do',
    '    hosts = Enum.filter(participants, &(&1["role"] == "host"))',
    '    valid_uuid?(host_id) and length(hosts) == 1 and hd(hosts)["participant_session_id"] == host_id',
    "  end",
    "  defp valid_snapshot_state?(_status, _host_id, _participants, _requests, _recording), do: false",
    "  defp unique_list?(value) when is_list(value), do: MapSet.size(MapSet.new(value)) == length(value)",
    "  defp unique_list?(_value), do: false",
    "  defp non_empty_unique_list?(value), do: unique_list?(value) and value != []",
    "",
    '  defp valid_event?(%{"name" => name, "event_id" => event_id, "base_revision" => base_revision, "revision" => revision, "schema_version" => schema_version, "resulting_state_digest" => digest, "payload" => payload} = frame) do',
    '    common = ["type", "stream", "name", "event_id", "base_revision", "revision", "schema_version", "resulting_state_digest", "payload"]',
    "    origin = Map.get(@event_origins, name)",
    `    origin_keys = if origin == "command_or_external", do: [${JSON.stringify(contract.eventFrame.commandOriginField)}, ${JSON.stringify(contract.eventFrame.externalOriginField)}], else: [if(origin == "command", do: ${JSON.stringify(contract.eventFrame.commandOriginField)}, else: if(origin == "lifecycle", do: ${JSON.stringify(contract.eventFrame.lifecycleOriginField)}, else: ${JSON.stringify(contract.eventFrame.externalOriginField)}) )]`,
    '    Enum.any?(origin_keys, fn key -> exact_keys?(frame, common ++ [key]) and valid_origin_id?(key, frame[key]) end) and frame["stream"] == "control" and valid_uuid?(event_id) and valid_revision_pair?(base_revision, revision) and valid_positive_integer?(schema_version) and valid_digest?(digest) and valid_event_payload?(name, payload) and frame_within_limit?(frame, @limits["encodedLiveEventBytes"])',
    "  end",
    "  defp valid_event?(_frame), do: false",
    `  defp valid_origin_id?(${JSON.stringify(contract.eventFrame.commandOriginField)}, id), do: valid_command_id?(id)`,
    "  defp valid_origin_id?(_key, id), do: valid_uuid?(id)",
    "",
    ...renderV3ElixirEventPayloads(contract.events),
    "  defp valid_event_payload?(_name, _payload), do: false",
    "",
    '  defp valid_replay_page?(%{"recovery_id" => recovery_id, "first_revision" => first_revision, "last_revision" => last_revision, "events" => events} = frame) do',
    '    exact_keys?(frame, ["type", "recovery_id", "first_revision", "last_revision", "events"]) and valid_uuid?(recovery_id) and is_list(events) and length(events) <= @limits["replayPageMaxEvents"] and frame_within_limit?(frame, @limits["replayPageEncodedBytes"]) and valid_replay_range?(events, first_revision, last_revision)',
    "  end",
    "  defp valid_replay_page?(_frame), do: false",
    "  defp valid_replay_range?([], _first, _last), do: false",
    "  defp valid_replay_range?([first | rest], first_revision, last_revision) do",
    '    valid_event?(first) and first["revision"] == first_revision and Enum.reduce_while(rest, first, fn event, previous -> if valid_event?(event) and event["base_revision"] == previous["revision"], do: {:cont, event}, else: {:halt, false} end) |> case do false -> false; last -> last["revision"] == last_revision end',
    "  end",
    "",
    '  defp valid_ack?(%{"outcome" => "committed", "command_id" => id, "delivery" => delivery, "event_id" => event_id, "revision" => revision, "state_digest" => digest} = frame), do: exact_keys?(frame, ["type", "command_id", "delivery", "outcome", "event_id", "revision", "state_digest"]) and valid_ack_base?(id, delivery) and valid_uuid?(event_id) and valid_positive_integer?(revision) and valid_digest?(digest)',
    '  defp valid_ack?(%{"outcome" => "satisfied", "command_id" => id, "delivery" => delivery, "revision" => revision, "state_digest" => digest} = frame), do: exact_keys?(frame, ["type", "command_id", "delivery", "outcome", "revision", "state_digest"]) and valid_ack_base?(id, delivery) and valid_non_negative_integer?(revision) and valid_digest?(digest)',
    '  defp valid_ack?(%{"outcome" => outcome, "command_id" => id, "delivery" => delivery, "reason" => reason} = frame) when outcome in ["rejected", "command_id_conflict"], do: exact_keys?(frame, ["type", "command_id", "delivery", "outcome", "reason"]) and valid_ack_base?(id, delivery) and reason in @rejection_reasons and (outcome != "command_id_conflict" or reason == "command_id_conflict")',
    "  defp valid_ack?(_frame), do: false",
    '  defp valid_ack_base?(id, delivery), do: valid_command_id?(id) and delivery in ["original", "duplicate"]',
    "",
    '  defp valid_projection?(%{"type" => "projection_snapshot", "stream" => stream, "projection_id" => projection_id, "sequence" => 0, "items" => items} = frame) do',
    '    exact_keys?(frame, ["type", "stream", "projection_id", "sequence", "items"]) and valid_uuid?(projection_id) and is_list(items) and length(items) <= projection_item_limit(stream) and Enum.all?(items, &valid_projection_item?(stream, &1)) and frame_within_limit?(frame, @limits["projectionSnapshotEncodedBytes"])',
    "  end",
    '  defp valid_projection?(%{"type" => "projection_event", "stream" => stream, "projection_id" => projection_id, "sequence" => sequence, "item" => item} = frame) do',
    '    exact_keys?(frame, ["type", "stream", "projection_id", "sequence", "item"]) and valid_uuid?(projection_id) and valid_positive_integer?(sequence) and valid_projection_item?(stream, item) and frame_within_limit?(frame, @limits["encodedLiveEventBytes"])',
    "  end",
    "  defp valid_projection?(_frame), do: false",
    '  defp projection_item_limit("media"), do: 1_500',
    '  defp projection_item_limit("presence"), do: 500',
    "  defp projection_item_limit(_stream), do: -1",
    '  defp valid_projection_item?("media", %{"participant_session_id" => id, "source" => source, "enabled" => enabled, "publication_id" => publication_id} = item), do: exact_keys?(item, ["participant_session_id", "source", "enabled", "publication_id"]) and valid_uuid?(id) and source in @media_sources and is_boolean(enabled) and (is_nil(publication_id) or bounded_string?(publication_id, 1, 256)) and enabled == not is_nil(publication_id)',
    '  defp valid_projection_item?("presence", %{"participant_session_id" => id, "state" => state, "speaking" => speaking, "active_speaker" => active} = item), do: exact_keys?(item, ["participant_session_id", "state", "speaking", "active_speaker"]) and valid_uuid?(id) and state in @presence_states and is_boolean(speaking) and is_boolean(active) and (state != "disconnected" or (not speaking and not active))',
    "  defp valid_projection_item?(_stream, _item), do: false",
    "",
    '  defp valid_live_target_result?(%{"operation_id" => id, "name" => name, "outcome" => outcome, "error_code" => error_code} = frame), do: exact_keys?(frame, ["type", "operation_id", "name", "outcome", "error_code"]) and valid_request_id?(id) and name in @live_target_names and outcome in @live_target_outcomes and (is_nil(error_code) or bounded_string?(error_code, 1, @limits["protocolErrorDetailBytes"]))',
    "  defp valid_live_target_result?(_frame), do: false",
    '  defp valid_directed_request_delivery?(%{"request_id" => id, "name" => name, "actor_participant_session_id" => actor_id, "expires_at_ms" => expires_at} = frame), do: exact_keys?(frame, ["type", "request_id", "name", "actor_participant_session_id", "expires_at_ms"]) and valid_request_id?(id) and name in @directed_request_names and valid_uuid?(actor_id) and valid_positive_integer?(expires_at)',
    "  defp valid_directed_request_delivery?(_frame), do: false",
    '  defp valid_directed_request_result?(%{"request_id" => id, "result" => result} = frame), do: exact_keys?(frame, ["type", "request_id", "result"]) and valid_request_id?(id) and result in @directed_request_results',
    "  defp valid_directed_request_result?(_frame), do: false",
    "",
    "  defp valid_cursor?(nil), do: true",
    '  defp valid_cursor?(%{"revision" => revision, "state_schema_version" => version, "state_digest" => digest} = cursor), do: exact_keys?(cursor, ["revision", "state_schema_version", "state_digest"]) and valid_non_negative_integer?(revision) and valid_positive_integer?(version) and valid_digest?(digest)',
    "  defp valid_cursor?(_cursor), do: false",
    '  defp valid_token?(value), do: bounded_string?(value, 0, @limits["tokenBytes"])',
    '  defp valid_command_id?(value), do: bounded_string?(value, @limits["commandIdMinBytes"], @limits["commandIdMaxBytes"])',
    '  defp valid_request_id?(value), do: bounded_string?(value, @limits["requestIdMinBytes"], @limits["requestIdMaxBytes"])',
    "  defp bounded_string?(value, minimum, maximum), do: is_binary(value) and byte_size(value) >= minimum and byte_size(value) <= maximum",
    "  defp valid_uuid?(value), do: is_binary(value) and value =~ @uuid",
    "  defp valid_digest?(value), do: is_binary(value) and value =~ @digest",
    "  defp valid_non_negative_integer?(value), do: is_integer(value) and value >= 0",
    "  defp valid_positive_integer?(value), do: is_integer(value) and value >= 1",
    "  defp valid_revision_pair?(base, revision), do: valid_non_negative_integer?(base) and revision == base + 1",
    "  defp exact_keys?(map, keys) when is_map(map), do: map_size(map) == length(keys) and Enum.all?(keys, &Map.has_key?(map, &1))",
    "  defp exact_keys?(_value, _keys), do: false",
    "  defp frame_within_limit?(frame, limit), do: frame |> JSON.encode!() |> byte_size() <= limit",
    "end",
  ];
  return `${lines.join("\n")}\n`;
}

/** @param {Record<string, any>[]} commands */
function renderV3ElixirCommandPayloads(commands) {
  return commands.flatMap((command) => {
    const fields = Object.entries(command.payload).map(([name, field]) => [snakeCase(name), field]);
    const pattern = fields.map(([name]) => `${JSON.stringify(name)} => ${name}`).join(", ");
    const keys = fields.map(([name]) => name);
    const checks = fields.map(([name, field]) => renderV3ElixirFieldCheck(field, name)).join(" and ");
    return [`  defp valid_command_payload?(${JSON.stringify(command.name)}, %{${pattern}} = payload) do`, `    exact_keys?(payload, ${renderElixirValue(keys)}) and ${checks}`, "  end", ""];
  });
}

/** @param {Record<string, any>[]} operations */
function renderV3ElixirOperationPayloads(operations) {
  return operations.flatMap((operation) => {
    const fields = Object.keys(operation.payload).map(snakeCase);
    const pattern = fields.map((name) => `${JSON.stringify(name)} => ${name}`).join(", ");
    const checks = fields.length === 0 ? "true" : fields.map((name) => `valid_uuid?(${name})`).join(" and ");
    return [`  defp valid_operation_payload?(${JSON.stringify(operation.name)}, %{${pattern}} = payload) do`, `    exact_keys?(payload, ${renderElixirValue(fields)}) and ${checks}`, "  end", ""];
  });
}

/** @param {Record<string, any>[]} events */
function renderV3ElixirEventPayloads(events) {
  return events.flatMap((event) => {
    const fields = Object.entries(event.payload).map(([name, field]) => [snakeCase(name), field]);
    const pattern = fields.map(([name]) => `${JSON.stringify(name)} => ${name}`).join(", ");
    const keys = fields.map(([name]) => name);
    const checks = fields.map(([name, field]) => renderV3ElixirFieldCheck(field, name)).join(" and ");
    return [`  defp valid_event_payload?(${JSON.stringify(event.name)}, %{${pattern}} = payload) do`, `    exact_keys?(payload, ${renderElixirValue(keys)}) and ${checks}`, "  end", ""];
  });
}

/** @param {Record<string, any>} field @param {string} variable */
function renderV3ElixirFieldCheck(field, variable) {
  if (field === "uuid") return `valid_uuid?(${variable})`;
  if (Array.isArray(field)) return `${variable} in ${renderElixirValue(field)}`;
  if (field.kind === "boolean") return `is_boolean(${variable})`;
  if (field.kind === "integer") return field.minimum > 0 ? `valid_positive_integer?(${variable})` : `valid_non_negative_integer?(${variable})`;
  if (field.kind === "array") {
    const values = field.of === "role" ? "@roles" : "@capabilities";
    return `is_list(${variable}) and length(${variable}) <= ${field.maxItems} and Enum.all?(${variable}, &(&1 in ${values}))`;
  }
  if (field.format === "uuid") return `valid_uuid?(${variable})`;
  if (field.enum) return `${variable} in ${renderElixirValue(field.enum)}`;
  const minimum = field.minBytes ?? 0;
  const trimmed = field.trimmedNonEmpty ? ` and ${variable} != "" and ${variable} == String.trim(${variable})` : "";
  const check = `bounded_string?(${variable}, ${minimum}, ${field.maxBytes})${trimmed}`;
  return field.nullable ? `(is_nil(${variable}) or ${check})` : check;
}

/**
 * @param {Record<string, any>} event
 */
function renderEventClause(event) {
  const payloadChecks = Object.entries(event.payload)
    .map(([name, field]) => `${elixirPredicate(field, nameToVariable(name))}`)
    .join(" and ");
  const payloadPattern = Object.keys(event.payload)
    .map((name) => `${inspectString(snakeCase(name))} => ${nameToVariable(name)}`)
    .join(", ");

  return `  defp valid_event_frame?(%{"type" => ${inspectString(event.type)}, "stream" => ${inspectString(event.stream)}, "name" => ${inspectString(event.name)}, "base_revision" => base_revision, "revision" => revision, "payload" => %{${payloadPattern}}} = frame) do
    valid_correlation_fields?(frame) and valid_revision_pair?(base_revision, revision) and ${payloadChecks}
  end`;
}

/**
 * @param {Record<string, any>} ack
 */
function renderAckClause(ack) {
  const extra = ack.revision ? ` and valid_positive_integer?(revision)` : " and is_binary(reason)";
  const field = ack.revision ? `"revision" => revision` : `"reason" => reason`;
  return `  defp valid_server_frame_body?(%{
        "type" => ${inspectString(ack.type)},
        "command_id" => command_id,
        "result" => ${inspectString(ack.result)},
        ${field}
      }),
      do: is_binary(command_id)${extra}`;
}

/**
 * @param {unknown} value
 */
function renderElixirValue(value) {
  if (value === null) {
    return "nil";
  }
  if (typeof value === "string") {
    return inspectString(value);
  }
  if (typeof value === "number") {
    const rendered = String(value);
    if (Number.isInteger(value) && Math.abs(value) >= 10_000) {
      const sign = rendered.startsWith("-") ? "-" : "";
      const digits = sign ? rendered.slice(1) : rendered;
      return sign + digits.replace(/\B(?=(\d{3})+(?!\d))/gu, "_");
    }
    return rendered;
  }
  if (typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(renderElixirValue).join(", ")}]`;
  }
  return `%{${Object.entries(value)
    .map(([key, child]) => `${inspectString(key)} => ${renderElixirValue(child)}`)
    .join(", ")}}`;
}

/**
 * @param {Record<string, any>[]} closeCodes
 */
function renderCloseCodes(closeCodes) {
  return `%{${closeCodes.map((closeCode) => `${closeCode.code} => ${renderElixirValue(closeCode)}`).join(", ")}}`;
}

/**
 * @param {string} value
 */
function inspectString(value) {
  return JSON.stringify(value);
}

/**
 * @param {string} value
 */
function snakeCase(value) {
  return value.replace(/[A-Z]/gu, (letter) => `_${letter.toLowerCase()}`);
}

/**
 * @param {string} value
 */
function nameToVariable(value) {
  return snakeCase(value);
}

/**
 * @param {Record<string, any>} field
 * @param {string} variable
 */
function elixirPredicate(field, variable) {
  switch (field.kind) {
    case "boolean":
      return `is_boolean(${variable})`;
    case "integer":
      return field.minimum > 0 ? `valid_positive_integer?(${variable})` : `valid_non_negative_integer?(${variable})`;
    default:
      return `is_binary(${variable})`;
  }
}

/**
 * @param {Record<string, any>} fields
 */
function renderCorrelationType(fields) {
  return `%{${renderCorrelationTypeEntries(fields)}}`;
}

/**
 * @param {Record<string, any>} fields
 */
function renderCorrelationTypeEntries(fields) {
  return Object.entries(fields)
    .map(([name, field]) => `optional(:${inspectString(name)}) => ${elixirType(field)}`)
    .join(", ");
}

/**
 * @param {Record<string, any>} fields
 */
function renderCorrelationFieldKeys(fields) {
  return `%{${Object.keys(fields)
    .map((name) => `${inspectString(name)} => :${inspectString(name)}`)
    .join(", ")}}`;
}

/**
 * @param {Record<string, any>} fields
 */
function renderCorrelationValidation(fields) {
  const checks = Object.entries(fields).map(([name, field]) => `(not Map.has_key?(frame, ${inspectString(name)}) or ${elixirPredicate(field, `frame[${inspectString(name)}]`)})`);
  return checks.join(" and ") || "true";
}

/**
 * @param {Record<string, any>} field
 */
function elixirType(field) {
  switch (field.kind) {
    case "boolean":
      return "boolean()";
    case "integer":
      return field.minimum > 0 ? "pos_integer()" : "non_neg_integer()";
    case "array":
      return "list()";
    case "object":
      return "map()";
    default:
      return "String.t()";
  }
}
