export const Theme = {
  colors: {
    // Chalk Light foundations. Keep these names in sync with docs/design.md;
    // the aliases below let existing SDK consumers migrate without a color
    // fork between old and new surfaces.
    paper: "#F7F6F2",
    paper2: "#F1F0EB",
    surface: "#FFFFFF",
    surfaceMuted: "#FBFAF7",
    ink: "#0C0E12",
    ink2: "#555B65",
    ink3: "#858A92",
    inkSecondary: "#555B65",
    inkTertiary: "#858A92",
    line: "#DEDDD7",
    lineStrong: "#C9C8C2",
    chalkGreen: "#80B879",
    washGreen: "#EDF6EB",
    chalkYellow: "#D9B641",
    washYellow: "#FFF8E5",
    chalkBlue: "#55AAC9",
    washBlue: "#EAF7FB",
    chalkPink: "#D67B7B",
    washPink: "#FDF0F0",
    successBackground: "#E8F1E4",
    warningBackground: "#FDF2CF",
    information: "#315F72",
    informationBackground: "#E6F3F8",
    dangerBackground: "#F8E4E4",

    // Existing names are public through the theme entry point. They are
    // semantic aliases, rather than a second palette, so old screens receive
    // the same warm-light treatment as new surfaces.
    background: "#F7F6F2",
    foreground: "#0C0E12",
    card: "#FFFFFF",
    cardForeground: "#0C0E12",
    popover: "#FFFFFF",
    popoverForeground: "#0C0E12",
    primary: "#0C0E12",
    primaryForeground: "#FFFFFF",
    secondary: "#F1F0EB",
    secondaryForeground: "#0C0E12",
    muted: "#FBFAF7",
    mutedForeground: "#555B65",
    accent: "#EAF7FB",
    accentForeground: "#0C0E12",
    destructive: "#B94C4C",
    destructiveForeground: "#FFFFFF",
    border: "#DEDDD7",
    input: "#C9C8C2",
    ring: "#55AAC9",
    success: "#4F8C4A",
    warning: "#9A7314",
    error: "#B94C4C",
    brandTeal: "#55AAC9",
    brandCyan: "#55AAC9",
    placeholder: "#858A92",
    stageBackground: "#F1F0EB",
    stageAccent: "#80B879",
    tileBackground: "#FBFAF7",
    controlsBackground: "rgba(255,255,255,0.96)",
    glassSurface: "rgba(255,255,255,0.92)",
    speakingAccent: "#80B879",
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 10,
    lg: 12,
    xl: 16,
    "2xl": 24,
    full: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    "2xl": 24,
    "3xl": 32,
    "4xl": 40,
    "5xl": 48,
    "6xl": 64,
  },
  typography: {
    eyebrow: {
      fontSize: 12,
      fontWeight: "700" as const,
      textTransform: "uppercase" as const,
      letterSpacing: 1.2,
    },
    title: {
      fontSize: 32,
      fontWeight: "800" as const,
      lineHeight: 40,
    },
    heading: {
      fontSize: 22,
      fontWeight: "700" as const,
      lineHeight: 28,
    },
    subheading: {
      fontSize: 18,
      fontWeight: "700" as const,
      lineHeight: 24,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
    },
    label: {
      fontSize: 14,
      fontWeight: "600" as const,
    },
    meta: {
      fontSize: 13,
      lineHeight: 18,
    },
  },
  shadows: {
    sm: {
      shadowColor: "#0C0E12",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: "#0C0E12",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.09,
      shadowRadius: 12,
      elevation: 4,
    },
    lg: {
      shadowColor: "#0C0E12",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};
