import { DEFAULT_CHALK_THEME_TOKENS, type ChalkThemeTokenValues } from "./theme-tokens";

const tokens = DEFAULT_CHALK_THEME_TOKENS;

export type NativeColorScheme = "dark" | "light";

export function createNativeTheme(themeTokens: ChalkThemeTokenValues = tokens, colorScheme: NativeColorScheme = "dark") {
  const tokens = themeTokens;

  return {
    colorScheme,
    colors: {
      background: tokens.canvas,
      foreground: tokens.text,
      card: tokens.chrome,
      cardForeground: tokens.text,
      surface: tokens.surface,
      popover: tokens.surface,
      popoverForeground: tokens.text,
      primary: tokens.accent,
      primaryForeground: tokens.accentText,
      secondary: tokens.chrome,
      secondaryForeground: tokens.text,
      muted: tokens.chrome,
      mutedForeground: tokens.mutedText,
      accent: tokens.chrome,
      accentForeground: tokens.text,
      destructive: tokens.dangerSurface,
      destructiveForeground: tokens.danger,
      border: tokens.line,
      input: tokens.line,
      ring: tokens.focus,
      success: tokens.positive,
      error: tokens.danger,
      stageBackground: tokens.stage,
      stageAccent: tokens.positive,
      tileBackground: tokens.chrome,
      controlsBackground: tokens.chrome,
      glassSurface: tokens.surface,
      transparent: "transparent",
      onDark: tokens.text,
      darkCanvas: tokens.canvas,
      raisedSurface: tokens.chrome,
      insetSurface: tokens.surface,
      elevatedSurface: tokens.chrome,
      nearDarkSurface: tokens.stage,
      lightSurface: tokens.chrome,
      lightText: tokens.text,
      lightMutedText: tokens.mutedText,
      lightSubtleText: tokens.mutedText,
      info: tokens.accent,
      dangerStrong: tokens.danger,
      warning: tokens.positive,
      placeholder: tokens.mutedText,
      statusOffline: tokens.mutedText,
      whiteOverlay04: "rgba(255,255,255,0.04)",
      whiteOverlay05: "rgba(255,255,255,0.05)",
      whiteOverlay06: "rgba(255,255,255,0.06)",
      whiteOverlay08: "rgba(255,255,255,0.08)",
      whiteOverlay10: "rgba(255,255,255,0.1)",
      whiteOverlay12: "rgba(255,255,255,0.12)",
      whiteOverlay16: "rgba(255,255,255,0.16)",
      whiteOverlay20: "rgba(255,255,255,0.2)",
      whiteOverlay25: "rgba(255,255,255,0.25)",
      whiteOverlay40: "rgba(255,255,255,0.4)",
      whiteOverlay50: "rgba(255,255,255,0.5)",
      whiteOverlay60: "rgba(255,255,255,0.6)",
      whiteOverlay68: "rgba(255,255,255,0.68)",
      whiteOverlay72: "rgba(255,255,255,0.72)",
      darkOverlay16: "rgba(0,0,0,0.16)",
      darkOverlay30: "rgba(0,0,0,0.3)",
      darkOverlay40: "rgba(0,0,0,0.4)",
      darkOverlay45: "rgba(0,0,0,0.45)",
      darkOverlay50: "rgba(0,0,0,0.5)",
      darkOverlay55: "rgba(0,0,0,0.55)",
      canvasOverlay85: "rgba(10,10,10,0.85)",
      chromeOverlay82: "rgba(10,10,12,0.82)",
      accentOverlay04: "rgba(27,182,166,0.04)",
      dangerSurfaceOverlay94: "rgba(127,29,29,0.94)",
    },
    avatarPalettes: [
      ["#14b8a6", "#0f766e", "#99f6e4"],
      ["#f59e0b", "#b45309", "#fde68a"],
      ["#ec4899", "#be185d", "#fbcfe8"],
      ["#8b5cf6", "#6d28d9", "#ddd6fe"],
      ["#06b6d4", "#0e7490", "#cffafe"],
      ["#22c55e", "#15803d", "#bbf7d0"],
    ] as const,
    logo: {
      arc: "#7EC8E3",
      mint: "#A8D5A2",
      mintDark: "#8BC585",
      gold: "#F5D76E",
      goldDark: "#E8C85A",
      sky: "#7EC8E3",
      skyDark: "#5FB8D9",
      coral: "#F0A0A0",
      coralDark: "#E88888",
    },
    radius: {
      xs: 4,
      sm: 8,
      md: 10,
      lg: 12,
      xl: 16,
      "2xl": 24,
      full: 9999,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      "2xl": 24,
      "3xl": 32,
      "4xl": 40,
      "5xl": 48,
      "6xl": 64,
    },
    typography: {
      eyebrow: {
        fontSize: 12,
        fontWeight: "700" as const,
        textTransform: "uppercase" as const,
        letterSpacing: 1.2,
      },
      title: {
        fontSize: 32,
        fontWeight: "800" as const,
        lineHeight: 40,
      },
      heading: {
        fontSize: 22,
        fontWeight: "700" as const,
        lineHeight: 28,
      },
      subheading: {
        fontSize: 18,
        fontWeight: "700" as const,
        lineHeight: 24,
      },
      body: {
        fontSize: 15,
        lineHeight: 22,
      },
      label: {
        fontSize: 14,
        fontWeight: "600" as const,
      },
      meta: {
        fontSize: 13,
        lineHeight: 18,
      },
    },
    shadows: {
      sm: {
        shadowColor: tokens.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
      },
      md: {
        shadowColor: tokens.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
      },
      lg: {
        shadowColor: tokens.shadow,
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.3,
        shadowRadius: 24,
        elevation: 8,
      },
    },
  };
}

export type NativeTheme = ReturnType<typeof createNativeTheme>;

export const Theme = createNativeTheme();
