export function useMeetingRoomUiState(..._args: any[]): any {
  return {
    activePanel: null,
    setActivePanel: () => {},
    togglePanel: () => {},
    layout: "grid",
    setLayout: () => {},
    isSettingsOpen: false,
    setIsSettingsOpen: () => {},
    showTour: false,
    setShowTour: () => {},
    isExiting: false,
    setIsExiting: () => {},
    isFilmstripOpen: false,
    setIsFilmstripOpen: () => {},
    isReactionPickerOpen: false,
    setIsReactionPickerOpen: () => {},
    isMobileSheetOpen: false,
    setIsMobileSheetOpen: () => {},
    showInviteModal: false,
    setShowInviteModal: () => {},
    showInviteToast: false,
    setShowInviteToast: () => {},
  };
}
