import { areas, groupOutcomes, sizes, states } from "./tracker-data.mjs";

const html = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const label = (item) => [states[item.state], item.priority, areas[item.area]].filter(Boolean).join(" · ");

const sizeSummary = (items) => sizes.map((size) => `${size}: ${items.filter((item) => item.size === size).length}`).join(" · ");

const evidenceLabel = (e) => (e.kind === "prior_assessment" ? "Prior assessment — not rerun" : `${e.kind.replaceAll("_", " ")} · ${e.result} · ${e.environment} · ${e.date}`);

const textLines = (text, prefix = "", continuation = " ".repeat(prefix.length)) => {
  const lines = [];
  let line = prefix;
  for (const word of text.replaceAll("<", "‹").replaceAll(">", "›").split(/\s+/u)) {
    if (line.length > prefix.length && line.length + word.length + 1 > 88) {
      lines.push(line);
      line = continuation;
    }
    line += `${line.trim() && line !== prefix && line !== continuation ? " " : ""}${word}`;
  }
  if (line.trim()) lines.push(line);
  return lines;
};

export const renderMarkdown = ({ outcomes, principle, sizing }) => {
  const lines = ["# Chalk: what works and what remains", "", ...textLines(principle), "", ...textLines(sizing), "", "Generated from tracker.yaml. Do not edit this file; run pnpm generate:tracker.", "", "Details, code references and evidence stay in tracker.yaml.", ""];
  const progress = {
    planned: "Not started",
    in_progress: "Partly working",
    blocked: "Blocked",
    unknown: "Unclear",
  };
  const groups = [
    ["First (P0)", outcomes.filter((item) => item.priority === "P0" && item.state !== "working")],
    ["Next (P1)", outcomes.filter((item) => item.priority === "P1" && item.state !== "working")],
    ["Later (P2)", outcomes.filter((item) => item.priority === "P2" && item.state !== "working")],
    ["Working", outcomes.filter((item) => item.state === "working")],
  ];
  for (const [title, items] of groups) {
    if (!items.length) continue;
    lines.push(`## ${title}`, "");
    if (title !== "Working") {
      lines.push(...textLines(`${items.length} ${items.length === 1 ? "item" : "items"} — ${sizeSummary(items)}`), "");
    }
    for (const [area, areaTitle] of Object.entries(areas)) {
      const local = items.filter((item) => item.area === area);
      if (!local.length) continue;
      lines.push(`### ${areaTitle}`, "");
      for (const item of local) {
        const status = item.state === "working" ? "" : `[${progress[item.state]}] `;
        lines.push(...textLines(`${status}${item.title}`, "- ", "  "));
        if (item.size) {
          lines.push(...textLines(`${item.size} — ${item.size_reason}`, "    **Size**: "));
        }
        if (item.state === "blocked") {
          lines.push(...textLines(item.blocked_by, "    **Waiting on**: "));
        }
        if (item.uncertainty) {
          lines.push(...textLines(item.uncertainty, "    **Unclear**: "));
        }
        if (item.remaining?.length) {
          for (const gap of item.remaining) lines.push(...textLines(gap, "    **Left**: "));
        }
        if (item.state !== "working") lines.push("");
      }
      if (lines.at(-1) !== "") lines.push("");
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
};

const evidenceHtml = (item) => {
  if (!item.evidence?.length && !item.code.length) return "";
  return `<details><summary>Assessment and implementation references</summary>${(item.evidence ?? [])
    .map(
      (e) =>
        `<h4>${html(evidenceLabel(e))}</h4>${e.scope ? `<p>${html(e.scope)}</p>` : ""}${e.detail ? `<p>${html(e.detail)}</p>` : ""}${e.artifact ? `<p>Artifact: <code>${html(e.artifact)}</code><br>Revision: <code>${html(e.revision)}</code></p>` : ""}${e.from ? `<p>Previous IDs: ${e.from.map((id) => `<code>${html(id)}</code>`).join(", ")}</p>` : ""}`,
    )
    .join("")}${item.code.length ? `<p>Source navigation, not execution proof:</p><ul>${item.code.map((file) => `<li><code>${html(file)}</code></li>`).join("")}</ul>` : ""}</details>`;
};

export const renderHtml = (tracker) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Chalk delivery</title>
<style>
:root{color-scheme:light;--ink:#1b1917;--muted:#6b655c;--paper:#faf9f7;--line:#e3dfd7;--accent:#8a6400}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}main{max-width:880px;margin:auto;padding:48px 24px 96px}a{color:var(--accent)}h1{font-size:2.5rem;line-height:1.1;margin:12px 0 24px}h2{margin-top:52px;border-bottom:1px solid var(--line);padding-bottom:12px}h3{font-size:1.18rem;margin:0 0 10px}h4{font-size:1rem}p{margin:12px 0}.eyebrow,.meta{color:var(--muted);font-size:.86rem}.eyebrow{letter-spacing:.12em;text-transform:uppercase}.card{overflow-wrap:anywhere;border:1px solid var(--line);border-radius:12px;background:white;padding:24px;margin:20px 0}.card[data-state=blocked]{border-inline-start:4px solid #a66a35}.card[data-state=unknown]{border-inline-start:4px solid #85847a}.meta{font-weight:600}label{display:block;font-weight:600;margin:24px 0 6px}input{width:100%;padding:12px;font:inherit;border:1px solid var(--line);border-radius:8px;background:white}input:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}details{margin-top:20px;border-top:1px solid var(--line);padding-top:14px;font-size:.9rem}summary{cursor:pointer;font-weight:600}code{overflow-wrap:anywhere;font-size:.82em}li+li{margin-top:6px}[hidden]{display:none!important}.empty{padding:24px 0}@media(max-width:520px){main{padding:28px 16px 64px}.card{padding:18px}h1{font-size:2rem}}@media print{input,label,.search-count{display:none}details{display:block}.card{break-inside:avoid}}
</style></head><body><main>
<p class="eyebrow">Chalk · Delivery</p><h1>What works. What remains.</h1>
<p>Read the outcomes below, or open <a href="tracker-human.md">the Markdown view</a>. Edit <a href="tracker.yaml">tracker.yaml</a> and run <code>pnpm generate:tracker</code> to update these views.</p>
<p class="meta">${html(tracker.principle)}</p>
<p>${html(tracker.sizing)}</p>
${["P0", "P1", "P2"].map((priority) => `<p class="meta">${priority} — ${html(sizeSummary(tracker.outcomes.filter((item) => item.priority === priority && item.state !== "working")))}</p>`).join("\n")}
<label for="search">Find an outcome</label><input id="search" type="search" placeholder="Search outcome, area, state, priority or size"><p class="search-count meta" id="count" aria-live="polite">${tracker.outcomes.length} outcomes</p>
${groupOutcomes(tracker)
  .filter((g) => g.items.length)
  .map(
    (g) =>
      `<section><h2>${html(g.title)}</h2>${g.items.map((item) => `<article class="card" id="${item.id}" data-state="${item.state}" data-search="${html([item.title, item.summary, item.uncertainty ?? "", item.size ? `size ${item.size}` : "", item.size_reason ?? "", ...(item.remaining ?? []), label(item)].join(" ").toLowerCase())}"><h3>${html(item.title)}</h3><p class="meta">${html(label(item))}</p><p>${html(item.summary)}</p>${item.size ? `<p><strong>Size:</strong> ${html(item.size)} — ${html(item.size_reason)}</p>` : ""}${item.blocked_by ? `<p><strong>Blocked by:</strong> ${html(item.blocked_by)}</p>` : ""}${item.remaining?.length ? `<p><strong>Remaining</strong></p><ul>${item.remaining.map((gap) => `<li>${html(gap)}</li>`).join("")}</ul>` : ""}${item.uncertainty ? `<p><strong>Uncertain:</strong> ${html(item.uncertainty)}</p>` : ""}${item.theory ? `<p><a href="${html(encodeURI(item.theory))}">Why this matters</a></p>` : ""}${evidenceHtml(item)}</article>`).join("")}</section>`,
  )
  .join("\n")}
<p class="empty" id="empty" hidden>No matching outcomes.</p></main>
<script type="module">
const input=document.getElementById('search');
const cards=[...document.querySelectorAll('.card')];
input.addEventListener('input',()=>{
 const query=input.value.trim().toLowerCase();let visible=0;
 for(const card of cards){card.hidden=!card.dataset.search.includes(query);if(!card.hidden)visible++;}
 for(const section of document.querySelectorAll('section'))section.hidden=![...section.querySelectorAll('.card')].some(card=>!card.hidden);
 document.getElementById('count').textContent=visible+' matching outcomes';
 document.getElementById('empty').hidden=visible!==0;
});
</script></body></html>\n`;
