import { areas, groupOutcomes, sizes, states } from "./tracker-data.mjs";

const html = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const label = (item) => [states[item.state], item.priority, areas[item.area]].filter(Boolean).join(" · ");
const sizeSummary = (items) => sizes.map((size) => `${size}: ${items.filter((item) => item.size === size).length}`).join(" · ");
const evidenceLabel = (evidence) => {
  if (evidence.kind === "prior_assessment") return "Prior assessment — not rerun";
  return `${evidence.kind.replaceAll("_", " ")} · ${evidence.result} · ${evidence.environment} · ${evidence.date}`;
};

const appendWord = (line, word, prefix, continuation) => {
  if (line === prefix || line === continuation) return `${line}${word}`;
  return `${line} ${word}`;
};
const lineFits = (candidate, line, prefix, continuation) => candidate.length <= 88 || line === prefix || line === continuation;

const textLines = (text, prefix = "", continuation = " ".repeat(prefix.length)) => {
  const lines = [];
  let line = prefix;
  for (const word of text.replaceAll("<", "‹").replaceAll(">", "›").split(/\s+/u)) {
    const candidate = appendWord(line, word, prefix, continuation);
    if (lineFits(candidate, line, prefix, continuation)) {
      line = candidate;
      continue;
    }
    lines.push(line);
    line = `${continuation}${word}`;
  }
  if (line.trim()) lines.push(line);
  return lines;
};

const progress = {
  planned: "Not started",
  in_progress: "Partly working",
  blocked: "Blocked",
  unknown: "Unclear",
};

const markdownGroups = (outcomes) => [
  ["First (P0)", outcomes.filter((item) => item.priority === "P0" && item.state !== "working")],
  ["Next (P1)", outcomes.filter((item) => item.priority === "P1" && item.state !== "working")],
  ["Later (P2)", outcomes.filter((item) => item.priority === "P2" && item.state !== "working")],
  ["Working", outcomes.filter((item) => item.state === "working")],
];

const itemTitleLines = (item) => {
  const status = item.state === "working" ? "" : `[${progress[item.state]}] `;
  return textLines(`${status}${item.title}`, "- ", "  ");
};
const itemSizeLines = (item) => (item.size ? textLines(`${item.size} — ${item.size_reason}`, "    **Size**: ") : []);
const itemBlockerLines = (item) => (item.state === "blocked" ? textLines(item.blocked_by, "    **Waiting on**: ") : []);
const itemUncertaintyLines = (item) => (item.uncertainty ? textLines(item.uncertainty, "    **Unclear**: ") : []);
const itemRemainingLines = (item) => (item.remaining ?? []).flatMap((gap) => textLines(gap, "    **Left**: "));
const itemTrailingLines = (item) => (item.state === "working" ? [] : [""]);
const markdownItem = (item) => [...itemTitleLines(item), ...itemSizeLines(item), ...itemBlockerLines(item), ...itemUncertaintyLines(item), ...itemRemainingLines(item), ...itemTrailingLines(item)];

const markdownArea = (items, area, areaTitle) => {
  const local = items.filter((item) => item.area === area);
  if (local.length === 0) return [];
  const lines = [`### ${areaTitle}`, "", ...local.flatMap(markdownItem)];
  if (lines.at(-1) !== "") lines.push("");
  return lines;
};
const itemCount = (items) => `${items.length} ${items.length === 1 ? "item" : "items"} — ${sizeSummary(items)}`;

const markdownGroup = ([title, items]) => {
  if (items.length === 0) return [];
  const lines = [`## ${title}`, ""];
  if (title !== "Working") {
    lines.push(...textLines(itemCount(items)), "");
  }
  for (const [area, areaTitle] of Object.entries(areas)) {
    lines.push(...markdownArea(items, area, areaTitle));
  }
  return lines;
};

export const renderMarkdown = ({ outcomes, principle, sizing }) => {
  const heading = ["# Chalk: what works and what remains", "", ...textLines(principle), "", ...textLines(sizing), "", "Generated from tracker.yaml. Do not edit this file; run pnpm generate:tracker.", "", "Details, code references and evidence stay in tracker.yaml.", ""];
  const lines = [...heading, ...markdownGroups(outcomes).flatMap(markdownGroup)];
  return `${lines.join("\n").trimEnd()}\n`;
};

const optionalParagraph = (labelText, value) => (value ? `<p>${labelText}${html(value)}</p>` : "");

const evidenceEntryHtml = (evidence) => {
  const heading = `<h4>${html(evidenceLabel(evidence))}</h4>`;
  const scope = optionalParagraph("", evidence.scope);
  const detail = optionalParagraph("", evidence.detail);
  const artifact = evidence.artifact ? `<p>Artifact: <code>${html(evidence.artifact)}</code><br>Revision: <code>${html(evidence.revision)}</code></p>` : "";
  const previous = evidence.from ? `<p>Previous IDs: ${evidence.from.map((id) => `<code>${html(id)}</code>`).join(", ")}</p>` : "";
  return `${heading}${scope}${detail}${artifact}${previous}`;
};

const codeReferencesHtml = (code) => {
  if (code.length === 0) return "";
  const items = code.map((file) => `<li><code>${html(file)}</code></li>`).join("");
  return `<p>Source navigation, not execution proof:</p><ul>${items}</ul>`;
};

const itemEvidence = (item) => item.evidence ?? [];
const evidenceHtml = (item) => {
  const entries = itemEvidence(item);
  if (entries.length === 0 && item.code.length === 0) return "";
  const evidence = entries.map(evidenceEntryHtml).join("");
  return `<details><summary>Assessment and implementation references</summary>${evidence}${codeReferencesHtml(item.code)}</details>`;
};

const remainingHtml = (remaining) => {
  if (!remaining?.length) return "";
  return `<p><strong>Remaining</strong></p><ul>${remaining.map((gap) => `<li>${html(gap)}</li>`).join("")}</ul>`;
};

const optionalSearchText = (value) => value ?? "";
const sizeSearchText = (item) => (item.size ? `size ${item.size}` : "");
const remainingSearchText = (item) => item.remaining ?? [];
const searchText = (item) => [item.title, item.summary, optionalSearchText(item.uncertainty), sizeSearchText(item), optionalSearchText(item.size_reason), ...remainingSearchText(item), label(item)].join(" ").toLowerCase();

const cardHtml = (item) => {
  const size = item.size ? `<p><strong>Size:</strong> ${html(item.size)} — ${html(item.size_reason)}</p>` : "";
  const blocker = optionalParagraph("<strong>Blocked by:</strong> ", item.blocked_by);
  const uncertainty = optionalParagraph("<strong>Uncertain:</strong> ", item.uncertainty);
  const theory = item.theory ? `<p><a href="${html(encodeURI(item.theory))}">Why this matters</a></p>` : "";
  return `<article class="card" id="${item.id}" data-state="${item.state}" data-search="${html(searchText(item))}"><h3>${html(item.title)}</h3><p class="meta">${html(label(item))}</p><p>${html(item.summary)}</p>${size}${blocker}${remainingHtml(item.remaining)}${uncertainty}${theory}${evidenceHtml(item)}</article>`;
};

const sectionHtml = (group) => `<section><h2>${html(group.title)}</h2>${group.items.map(cardHtml).join("")}</section>`;
const prioritySummaryHtml = (tracker, priority) => {
  const items = tracker.outcomes.filter((item) => item.priority === priority && item.state !== "working");
  return `<p class="meta">${priority} — ${html(sizeSummary(items))}</p>`;
};

export const renderHtml = (tracker) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Chalk delivery</title>
<style>
:root{color-scheme:light;--ink:#1b1917;--muted:#6b655c;--paper:#faf9f7;--line:#e3dfd7;--accent:#8a6400}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}main{max-width:880px;margin:auto;padding:48px 24px 96px}a{color:var(--accent)}h1{font-size:2.5rem;line-height:1.1;margin:12px 0 24px}h2{margin-top:52px;border-bottom:1px solid var(--line);padding-bottom:12px}h3{font-size:1.18rem;margin:0 0 10px}h4{font-size:1rem}p{margin:12px 0}.eyebrow,.meta{color:var(--muted);font-size:.86rem}.eyebrow{letter-spacing:.12em;text-transform:uppercase}.card{overflow-wrap:anywhere;border:1px solid var(--line);border-radius:12px;background:white;padding:24px;margin:20px 0}.card[data-state=blocked]{border-inline-start:4px solid #a66a35}.card[data-state=unknown]{border-inline-start:4px solid #85847a}.meta{font-weight:600}label{display:block;font-weight:600;margin:24px 0 6px}input{width:100%;padding:12px;font:inherit;border:1px solid var(--line);border-radius:8px;background:white}input:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}details{margin-top:20px;border-top:1px solid var(--line);padding-top:14px;font-size:.9rem}summary{cursor:pointer;font-weight:600}code{overflow-wrap:anywhere;font-size:.82em}li+li{margin-top:6px}[hidden]{display:none!important}.empty{padding:24px 0}@media(max-width:520px){main{padding:28px 16px 64px}.card{padding:18px}h1{font-size:2rem}}@media print{input,label,.search-count{display:none}details{display:block}.card{break-inside:avoid}}
</style></head><body><main>
<p class="eyebrow">Chalk · Delivery</p><h1>What works. What remains.</h1>
<p>Read the outcomes below, or open <a href="tracker-human.md">the Markdown view</a>. Edit <a href="tracker.yaml">tracker.yaml</a> and run <code>pnpm generate:tracker</code> to update these views.</p>
<p class="meta">${html(tracker.principle)}</p>
<p>${html(tracker.sizing)}</p>
${["P0", "P1", "P2"].map((priority) => prioritySummaryHtml(tracker, priority)).join("\n")}
<label for="search">Find an outcome</label><input id="search" type="search" placeholder="Search outcome, area, state, priority or size"><p class="search-count meta" id="count" aria-live="polite">${tracker.outcomes.length} outcomes</p>
${groupOutcomes(tracker)
  .filter((group) => group.items.length)
  .map(sectionHtml)
  .join("\n")}
<p class="empty" id="empty" hidden>No matching outcomes.</p></main>
<script type="module">
const input=document.getElementById('search');
const cards=[...document.querySelectorAll('.card')];
input.addEventListener('input',()=>{
 const query=input.value.trim().toLowerCase();let visible=0;
 for(const card of cards){card.hidden=!card.dataset.search.includes(query);if(!card.hidden)visible++;}
 for(const section of document.querySelectorAll('section'))section.hidden=![...section.querySelectorAll('.card')].some(card=>!card.hidden);
 document.getElementById('count').textContent=visible+' matching outcomes';
 document.getElementById('empty').hidden=visible!==0;
});
</script></body></html>\n`;
