from __future__ import annotations

import os

from .env_utils import env_bool, env_float, env_int

JOB_QUEUE = "transcription:jobs"
PROCESSING_QUEUE = "transcription:jobs:processing"
RESULT_KEY_PREFIX = "transcription:result:"
DONE_KEY_PREFIX = "transcription:done:"
PROCESSING_LOCK_KEY_PREFIX = "transcription:lock:"
PROCESSING_RECOVERY_LOCK_KEY = "transcription:jobs:recovery-lock"
RESULT_TTL_SECONDS = 24 * 60 * 60  # 24 hours
DONE_TTL_SECONDS = env_int("WHISPER_DONE_TTL_SECONDS", 7 * 24 * 60 * 60)
PROCESSING_LOCK_TTL_SECONDS = env_int("WHISPER_PROCESSING_LOCK_TTL_SECONDS", 15 * 60)
PROCESSING_HEARTBEAT_INTERVAL_SECONDS = env_int(
    "WHISPER_PROCESSING_HEARTBEAT_INTERVAL_SECONDS", 30
)
PROCESSING_RECOVERY_INTERVAL_SECONDS = env_int(
    "WHISPER_PROCESSING_RECOVERY_INTERVAL_SECONDS", 60
)
PROCESSING_RECOVERY_LOCK_TTL_SECONDS = env_int(
    "WHISPER_PROCESSING_RECOVERY_LOCK_TTL_SECONDS", 55
)
POLL_TIMEOUT_SECONDS = 30

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
REDIS_CONNECT_TIMEOUT = env_float("REDIS_CONNECT_TIMEOUT", 5.0)
REDIS_SOCKET_TIMEOUT = env_float("REDIS_SOCKET_TIMEOUT", POLL_TIMEOUT_SECONDS + 5)
REDIS_RETRY_ON_TIMEOUT = env_bool("REDIS_RETRY_ON_TIMEOUT", True)
REDIS_HEALTHCHECK_INTERVAL = env_int("REDIS_HEALTHCHECK_INTERVAL", 30)

LOG_TRANSCRIPT = env_bool("WHISPER_LOG_TRANSCRIPT", False)
LOG_TRANSCRIPT_MAX_CHARS = env_int("WHISPER_LOG_TRANSCRIPT_MAX_CHARS", 4000)
GPU_METRICS_ENABLED = env_bool("WHISPER_GPU_METRICS_ENABLED", True)
