run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - os.Setenv
      - os.Unsetenv

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value of .*.Close.*is not checked"
