run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write
      - os.Setenv
      - os.Unsetenv

issues:
  exclude-use-default: false
